import { PrismaClient } from '@prisma/client';
import * as bcrypt from 'bcrypt';

const prisma = new PrismaClient();

const CAREER_PATHS = [
  { slug: 'product-design', name: 'Product Design', description: 'Design digital products that solve real user problems', tags: ['Design', 'UX', 'Figma', 'Research', 'Prototyping'] },
  { slug: 'frontend-engineering', name: 'Frontend Engineering', description: 'Build the interfaces users interact with on the web', tags: ['React', 'JavaScript', 'CSS', 'TypeScript', 'Web'] },
  { slug: 'data-analysis', name: 'Data Analysis', description: 'Turn raw data into insights that drive business decisions', tags: ['SQL', 'Python', 'Excel', 'Visualisation', 'Statistics'] },
  { slug: 'product-management', name: 'Product Management', description: 'Define what gets built and why, bridging tech and business', tags: ['Strategy', 'Roadmapping', 'Stakeholders', 'Agile', 'Metrics'] },
  { slug: 'content-strategy', name: 'Content Strategy', description: 'Shape how brands communicate and connect with audiences', tags: ['Writing', 'SEO', 'Brand', 'Editorial', 'Distribution'] },
  { slug: 'backend-engineering', name: 'Backend Engineering', description: 'Build robust APIs, database structures, and server logic', tags: ['Node.js', 'SQL', 'APIs', 'Docker', 'System Design'] },
  { slug: 'cybersecurity', name: 'Cybersecurity', description: 'Protect digital systems, networks, and data from cyber threats', tags: ['Linux', 'Networking', 'Security', 'Penetration Testing', 'IAM'] },
  { slug: 'cloud-engineering', name: 'Cloud Engineering', description: 'Design, deploy, and manage scalable cloud infrastructure', tags: ['AWS', 'Terraform', 'CI/CD', 'Docker', 'Kubernetes'] },
  { slug: 'digital-marketing', name: 'Digital Marketing', description: 'Drive user acquisition, growth, and brand visibility online', tags: ['SEO', 'Analytics', 'SEM', 'Social Media', 'Copywriting'] },
  { slug: 'machine-learning-engineering', name: 'Machine Learning Engineering', description: 'Design, build, and deploy machine learning models to production', tags: ['Python', 'PyTorch', 'scikit-learn', 'MLOps', 'Data Science'] },
];

const ROADMAP_STAGES = [
  // Generate 3 stages (Foundation = 1, Intermediate = 2, Advanced = 3) for each of the 10 paths
  ...CAREER_PATHS.flatMap((path) => [
    {
      pathSlug: path.slug,
      stageNumber: 1,
      title: 'Foundation Phase',
      outcomes: ['Understand core concepts and terms', 'Master primary industry-standard tools', 'Complete beginner portfolio projects'],
      resources: [
        { title: 'Introductory Course', url: 'https://www.coursera.org', type: 'course' },
        { title: 'Industry Handbook', url: 'https://www.gitbook.com', type: 'book' },
      ],
    },
    {
      pathSlug: path.slug,
      stageNumber: 2,
      title: 'Intermediate Phase',
      outcomes: ['Develop applied professional skills', 'Work with collaborative development workflows', 'Solve moderately complex problem statements'],
      resources: [
        { title: 'Intermediate Guidebook', url: 'https://medium.com', type: 'article' },
        { title: 'Applied Project Guide', url: 'https://github.com', type: 'tool' },
      ],
    },
    {
      pathSlug: path.slug,
      stageNumber: 3,
      title: 'Advanced Phase',
      outcomes: ['Design production-ready architectures', 'Implement professional system design patterns', 'Prepare advanced industry-level deliverables'],
      resources: [
        { title: 'System Design Interview Guide', url: 'https://www.tryexponent.com', type: 'course' },
        { title: 'Advanced Reference Docs', url: 'https://developer.mozilla.org', type: 'article' },
      ],
    },
  ]),
];

const TASKS = [
  // ── Product Design ──
  {
    pathSlug: 'product-design',
    stageNumber: 1,
    title: 'Mobile App Screen Redesign',
    description: 'Pick a mobile app you use daily and redesign one of its core screens in Figma to improve layout and usability.',
    deliverables: ['High-fidelity Figma frame of the redesign', 'Before/after screen comparison', 'Written rationale of your UX decisions (200 words)'],
    acceptanceCriteria: ['Must submit a public Figma file link', 'All font styles and colors must be standardized', 'Rationale must explain why visual hierarchy was changed'],
    difficulty: 1,
    expectedOutput: 'A clean, modernized high-fidelity mobile UI screen in Figma with organized layers and auto-layout.',
    skillsExercised: ['Figma UI Design', 'Visual Hierarchy', 'Typography', 'Color Theory'],
    suggestedTools: ['Figma', 'Contrast Checker'],
    presentationTips: 'Group your elements using Figma Auto-layout and rename all frames cleanly so employers can see your organized workflow.',
  },
  {
    pathSlug: 'product-design',
    stageNumber: 1,
    title: 'Create a Simple Design System',
    description: 'Build a foundational component library with buttons, text fields, and dropdowns using Figma styles.',
    deliverables: ['Figma library with at least 6 components', 'Light/dark mode color palettes defined'],
    acceptanceCriteria: ['All components must support hover, active, and disabled variants', 'Uses Figma components with properties'],
    difficulty: 2,
    expectedOutput: 'A shareable Figma file serving as a UI kit with typography guidelines, color variables, and interactive components.',
    skillsExercised: ['Figma Components', 'Design Systems', 'UI Kit Creation'],
    suggestedTools: ['Figma', 'Tailwind Colors'],
    presentationTips: 'Organize components in clean grids and label each state explicitly (default, hover, disabled).',
  },
  {
    pathSlug: 'product-design',
    stageNumber: 2,
    title: '4-Screen Interactive Prototype',
    description: 'Design a complete user flow (e.g. signup to checkout) using interactive components and state transitions in Figma.',
    deliverables: ['Working interactive prototype link', 'User flow diagram mapping user actions'],
    acceptanceCriteria: ['Prototype flow must connect at least 4 distinct pages/actions', 'Smart Animate transitions used correctly'],
    difficulty: 2,
    expectedOutput: 'A fully clickable interactive Figma prototype showing smooth transitions and micro-animations.',
    skillsExercised: ['Prototyping', 'Interaction Design', 'User Flow Mapping'],
    suggestedTools: ['Figma Prototype', 'Whimsical'],
    presentationTips: 'Make sure there are no dead-ends in your flow; every screen should offer an action to return or proceed.',
  },
  {
    pathSlug: 'product-design',
    stageNumber: 2,
    title: 'Usability Testing & Iteration Case Study',
    description: 'Run a usability test on your interactive prototype with at least 3 participants and write an iteration report.',
    deliverables: ['Usability testing guide', 'Summary of findings', 'Updated designs showing changes based on feedback'],
    acceptanceCriteria: ['Report outlines at least 3 usability friction points discovered', 'Designs are modified based on feedback'],
    difficulty: 3,
    expectedOutput: 'A usability report document with feedback summaries and side-by-side screenshots of the design iterations.',
    skillsExercised: ['User Research', 'Usability Testing', 'Design Iteration'],
    suggestedTools: ['Maze', 'Notion', 'Figma'],
    presentationTips: 'Use direct quotes from users and bar charts or tables to visually show their success rates or points of confusion.',
  },
  {
    pathSlug: 'product-design',
    stageNumber: 3,
    title: 'Full Product Design Specification & Brief',
    description: 'Write a comprehensive product specification doc for a new feature, outlining user problems, user stories, and feature designs.',
    deliverables: ['Detailed product design spec (PDF or Notion link)', 'Interactive high-fidelity prototype'],
    acceptanceCriteria: ['Includes at least 8 user stories with clear design requirements', 'Prototype handles complex edge cases'],
    difficulty: 4,
    expectedOutput: 'A production-ready design brief detailing scope, accessibility guidelines, and developer hand-off assets.',
    skillsExercised: ['Product Thinking', 'Developer Hand-off', 'Accessibility Design (WCAG)', 'Specification Writing'],
    suggestedTools: ['Notion', 'Figma Inspect', 'Zeplin'],
    presentationTips: 'Include an accessibility section checking color contrast ratios and explaining keyboard navigation flows for screen-readers.',
  },
  {
    pathSlug: 'product-design',
    stageNumber: 3,
    title: 'Complete SaaS Web App Interface Design',
    description: 'Design a dashboard layout for a complex SaaS application, displaying multiple data visualizations and settings screens.',
    deliverables: ['High-fidelity SaaS design link', 'Responsive grid system layout presentation'],
    acceptanceCriteria: ['Design includes a side navigation, stats charts, and responsive layouts for mobile and desktop'],
    difficulty: 5,
    expectedOutput: 'A complete desktop and mobile responsive UI layout of a web portal showing structured data dashboards.',
    skillsExercised: ['Dashboard Design', 'Information Architecture', 'Responsive Design', 'SaaS UX'],
    suggestedTools: ['Figma', 'Charts Plugin'],
    presentationTips: 'Focus on clear data hierarchy. Use distinct card layouts and subtle borders instead of heavy colorful backgrounds.',
  },

  // ── Frontend Engineering ──
  {
    pathSlug: 'frontend-engineering',
    stageNumber: 1,
    title: 'Responsive Portfolio Website',
    description: 'Build a responsive personal portfolio website from scratch using semantic HTML and Vanilla CSS. No frameworks allowed.',
    deliverables: ['Link to public GitHub repository', 'Live site deployment URL'],
    acceptanceCriteria: ['Valid HTML5 syntax', 'Fully responsive on screens from 320px to 1440px wide', 'Includes contact form and project listings'],
    difficulty: 1,
    expectedOutput: 'A clean, fast-loading, mobile-friendly landing page with animations deployed to a public hosting service.',
    skillsExercised: ['HTML5', 'CSS Flexbox/Grid', 'Responsive Layouts', 'Git & Hosting'],
    suggestedTools: ['VS Code', 'GitHub Pages', 'Netlify', 'W3C Validator'],
    presentationTips: 'Host your code on GitHub and write a clean README containing details on the styling methodology used.',
  },
  {
    pathSlug: 'frontend-engineering',
    stageNumber: 1,
    title: 'JavaScript Interactive Calculator',
    description: 'Develop an interactive calculator app utilizing vanilla JavaScript for logic and operations.',
    deliverables: ['GitHub Repository', 'Live deployment URL'],
    acceptanceCriteria: ['Handles decimal calculations, clear operations, and error states (division by zero)', 'Interface styled cleanly with custom CSS'],
    difficulty: 2,
    expectedOutput: 'A fully functional desktop/mobile browser calculator that handles arithmetic operations correctly.',
    skillsExercised: ['Vanilla JavaScript', 'DOM Manipulation', 'Event Listeners', 'Logic Handling'],
    suggestedTools: ['VS Code', 'Google Chrome DevTools'],
    presentationTips: 'Add keyboard event support (e.g. pressing numbers or Enter triggers the calculation) to show attention to usability.',
  },
  {
    pathSlug: 'frontend-engineering',
    stageNumber: 2,
    title: 'Dynamic Weather Dashboard API Integration',
    description: 'Build a weather dashboard in React or vanilla JS that calls a third-party weather API and shows forecast data dynamically.',
    deliverables: ['GitHub Repository link', 'Live website URL'],
    acceptanceCriteria: ['Performs API fetch requests and handles loading/error states', 'Displays current weather and 5-day forecasts'],
    difficulty: 2,
    expectedOutput: 'A responsive dashboard displaying dynamically fetched data with location search capabilities.',
    skillsExercised: ['API Integration', 'Async JavaScript (Fetch/Axios)', 'React Hooks', 'State Management'],
    suggestedTools: ['React', 'Vite', 'OpenWeatherMap API'],
    presentationTips: 'Implement search input debouncing to prevent excessive API calls and optimize loading times.',
  },
  {
    pathSlug: 'frontend-engineering',
    stageNumber: 2,
    title: 'Full-Featured Task Management App',
    description: 'Create a task manager app in React with tasks stored in localStorage. Implement task lists, categories, edit options, and filter controls.',
    deliverables: ['GitHub Repository', 'Live demo link'],
    acceptanceCriteria: ['Supports full CRUD operations (Create, Read, Update, Delete)', 'Persistent data storage in local storage', 'Filters for completed/pending tasks'],
    difficulty: 3,
    expectedOutput: 'A React application featuring robust interactive state management and data persistence.',
    skillsExercised: ['React Component Design', 'Local Storage Persistence', 'Conditional Rendering', 'TailwindCSS / CSS Modules'],
    suggestedTools: ['React', 'TailwindCSS', 'Lucide React Icons'],
    presentationTips: 'Design a detailed dashboard layout with progress indicators displaying the ratio of completed tasks.',
  },
  {
    pathSlug: 'frontend-engineering',
    stageNumber: 3,
    title: 'Deploy a Full-Stack Next.js Application',
    description: 'Develop a full-stack Next.js web application utilizing App Router, Server Actions, and a backend database integration.',
    deliverables: ['GitHub repository', 'Live URL deployed to Vercel'],
    acceptanceCriteria: ['Uses database storage for records', 'Protected user routes requiring session/auth', 'Optimized build with server-side page render support'],
    difficulty: 4,
    expectedOutput: 'A production-deployed Next.js application showing server-side rendering and database integration.',
    skillsExercised: ['Next.js App Router', 'Server Actions', 'Database Integration (Prisma)', 'Vercel Deployment'],
    suggestedTools: ['Next.js', 'Prisma ORM', 'Supabase PostgreSQL', 'NextAuth.js'],
    presentationTips: 'Enable Next.js route optimizations and provide a README detailing the architecture structure.',
  },
  {
    pathSlug: 'frontend-engineering',
    stageNumber: 3,
    title: 'React Performance Audit & Component Suite',
    description: 'Audit and optimize an existing slow React application, refactoring it to prevent re-renders, and implementing a suite of unit tests.',
    deliverables: ['Optimized GitHub repository link', 'Performance comparison audit report (lighthouse scores, Profiler traces)'],
    acceptanceCriteria: ['App displays lighthouse performance score above 90', 'Includes at least 10 React unit and integration tests (React Testing Library)'],
    difficulty: 5,
    expectedOutput: 'A highly optimized, fully tested React component suite with zero unnecessary re-renders.',
    skillsExercised: ['React Performance Tuning', 'useMemo / useCallback', 'Unit Testing (Jest/Vitest)', 'Lighthouse Audits'],
    suggestedTools: ['React DevTools Profiler', 'Vitest', 'Testing Library', 'Google Lighthouse'],
    presentationTips: 'Show clear before/after metrics of page load speeds and JavaScript bundle sizes in your README.',
  },

  // ── Data Analysis ──
  {
    pathSlug: 'data-analysis',
    stageNumber: 1,
    title: 'Spreadsheet Exploratory Analysis',
    description: 'Analyze a public sales dataset in Google Sheets or Excel, building pivot tables, cleaning records, and creating charts.',
    deliverables: ['Link to shared online spreadsheet', 'Summary report detailing 3 key observations (300 words)'],
    acceptanceCriteria: ['Dataset contains >500 rows', 'Includes at least 2 distinct pivot charts', 'Data cleaning steps are documented'],
    difficulty: 1,
    expectedOutput: 'An organized spreadsheet workbook containing clean structured data, formulas, and dashboards.',
    skillsExercised: ['Spreadsheet Formulas', 'Pivot Tables', 'Data Visualization', 'Data Cleaning'],
    suggestedTools: ['Google Sheets', 'Microsoft Excel'],
    presentationTips: 'Use a clean corporate color theme for your charts and avoid overly colorful formatting in the data grid.',
  },
  {
    pathSlug: 'data-analysis',
    stageNumber: 1,
    title: 'SQL Business Metrics Queries',
    description: 'Write complex SQL queries on a business schema to extract metrics like Monthly Recurring Revenue (MRR), Customer Acquisition Cost (CAC), and user retention.',
    deliverables: ['SQL script file containing annotated queries', 'Query results outputs (screenshots or CSVs)'],
    acceptanceCriteria: ['Queries utilize JOINs, aggregations, CTEs, and window functions', 'Queries answer specific business performance questions'],
    difficulty: 2,
    expectedOutput: 'A SQL script answering business performance questions through complex database queries.',
    skillsExercised: ['SQL Query Writing', 'Relational Databases', 'CTEs & Window Functions', 'Business Metrics'],
    suggestedTools: ['PostgreSQL', 'DBeaver', 'BigQuery'],
    presentationTips: 'Write comments in your SQL files explaining the logic of your calculations (especially around complex aggregates).',
  },
  {
    pathSlug: 'data-analysis',
    stageNumber: 2,
    title: 'Python Explanatory Data Study',
    description: 'Perform an Exploratory Data Analysis (EDA) on a dataset using Jupyter Notebook, pandas, and matplotlib, outputting key trends.',
    deliverables: ['Jupyter Notebook file on GitHub', 'Clean PDF export of the notebook'],
    acceptanceCriteria: ['Uses pandas for dataset cleaning and descriptive stats', 'Includes at least 5 meaningful data visualizations'],
    difficulty: 2,
    expectedOutput: 'A clean Jupyter notebook showing documented python steps for loading, cleaning, and visualizing data.',
    skillsExercised: ['Python Programming', 'pandas DataFrames', 'matplotlib / seaborn', 'EDA Workflow'],
    suggestedTools: ['Jupyter Notebook', 'pandas', 'seaborn', 'Kaggle Datasets'],
    presentationTips: 'Format the notebook professionally with Markdown headers to structure the analytical flow like a story.',
  },
  {
    pathSlug: 'data-analysis',
    stageNumber: 2,
    title: 'Interactive BI Dashboard Project',
    description: 'Build an interactive BI dashboard (Tableau or Power BI) showing business operations, enabling user filters and drill-downs.',
    deliverables: ['Link to published Tableau Public workbook or Power BI file'],
    acceptanceCriteria: ['Dashboard displays at least 4 coordinated charts', 'Includes filters for time, region, and categories'],
    difficulty: 3,
    expectedOutput: 'A publicly viewable interactive data portal showing key performance indicators.',
    skillsExercised: ['BI Tooling', 'Dashboard Layouts', 'Interactive Filters', 'KPI Tracking'],
    suggestedTools: ['Tableau Public', 'Power BI'],
    presentationTips: 'Position your primary KPI cards in the top-left area where users naturally start reading the page.',
  },
  {
    pathSlug: 'data-analysis',
    stageNumber: 3,
    title: 'Production Data Pipeline & ETL',
    description: 'Create an automated data pipeline using Python that extracts data from an API, transforms it, and loads it into a database.',
    deliverables: ['GitHub repository with the ETL python scripts', 'Database schema export', 'Cron schedule setup configuration details'],
    acceptanceCriteria: ['Pipeline runs successfully and handles API response errors', 'Logs database load status and cleans invalid inputs'],
    difficulty: 4,
    expectedOutput: 'A structured python ETL project that runs automatically and persists parsed data.',
    skillsExercised: ['ETL Pipelines', 'Python Scripting', 'API Consumption', 'Database Upserts'],
    suggestedTools: ['Python', 'SQLAlchemy', 'PostgreSQL', 'GitHub Actions'],
    presentationTips: 'Use object-relational mapping (ORM) and connection pooling to show industry-standard backend habits.',
  },
  {
    pathSlug: 'data-analysis',
    stageNumber: 3,
    title: 'Cohort Analysis & Retention Report',
    description: 'Perform a comprehensive cohort analysis on transaction logs to evaluate monthly customer retention rates.',
    deliverables: ['Analytical report document (PDF or Notion link)', 'Jupyter Notebook with Python calculations'],
    acceptanceCriteria: ['Includes retention cohort heatmap visualization', 'Contains actionable recommendations to increase retention based on data findings'],
    difficulty: 5,
    expectedOutput: 'A professional executive report containing structured cohort analyses and business logic recommendations.',
    skillsExercised: ['Cohort Analysis', 'User Retention Logic', 'Advanced pandas', 'Executive Reporting'],
    suggestedTools: ['Python pandas', 'seaborn heatmap', 'Notion'],
    presentationTips: 'Highlight the distinction between organic growth and retention drop-offs, giving concrete product suggestions for improvement.',
  },

  // ── Product Management ──
  {
    pathSlug: 'product-management',
    stageNumber: 1,
    title: 'Mobile App Feature Teardown',
    description: 'Deconstruct a feature in a popular mobile app, writing a product teardown detailing its target users, metrics, and gaps.',
    deliverables: ['1-page teardown document (PDF or Notion)'],
    acceptanceCriteria: ['Identifies at least 2 distinct user personas', 'Lists 3 primary telemetry metrics tracked', 'Suggests 1 user-centric UX improvement'],
    difficulty: 1,
    expectedOutput: 'A formatted product breakdown analyzing user behavior, feature mechanics, and potential changes.',
    skillsExercised: ['Product Analysis', 'Persona Mapping', 'Feature Telemetry', 'UX Critique'],
    suggestedTools: ['Notion', 'Figma (optional)'],
    presentationTips: 'Use structural subheadings like User Persona, Feature Flow, Gaps, and Solutions to keep your critique structured.',
  },
  {
    pathSlug: 'product-management',
    stageNumber: 1,
    title: 'User Interview Study & Insights',
    description: 'Run user interviews with at least 3 target customers to explore a specific problem space, synthesising findings.',
    deliverables: ['User interview guide script', 'Raw interview notes summary', 'Synthesis report showing core themes'],
    acceptanceCriteria: ['Interviews last >15 mins', 'Report lists at least 3 recurring customer pain points'],
    difficulty: 2,
    expectedOutput: 'A user research summary showing interview inputs and categorized customer needs.',
    skillsExercised: ['User Interviewing', 'Qualitative Analysis', 'Synthesis', 'Active Listening'],
    suggestedTools: ['Google Docs', 'Otter.ai', 'Notion'],
    presentationTips: 'Add callout boxes displaying direct user quotes to make user needs feel authentic to recruiters.',
  },
  {
    pathSlug: 'product-management',
    stageNumber: 2,
    title: 'Product Strategy & Roadmap Project',
    description: 'Create a 6-month product roadmap for a digital product with explicit prioritization frameworks (e.g. RICE).',
    deliverables: ['Visual product roadmap diagram', 'Prioritization matrix documentation page'],
    acceptanceCriteria: ['Roadmap covers at least 3 feature themes', 'RICE scores are calculated and explained for each feature'],
    difficulty: 2,
    expectedOutput: 'A detailed interactive roadmap timeline showing features, horizons, and product strategy goals.',
    skillsExercised: ['Product Roadmapping', 'Prioritization (RICE/Kano)', 'Strategy Definition', 'Timeline Planning'],
    suggestedTools: ['Figma', 'Miro', 'Productboard'],
    presentationTips: 'Design the roadmap around product outcomes (e.g., "Increase checkouts") rather than output lists (e.g., "Build checkout button").',
  },
  {
    pathSlug: 'product-management',
    stageNumber: 2,
    title: 'Feature Specs & PRD Writing',
    description: 'Write a comprehensive Product Requirements Document (PRD) for a new digital product feature.',
    deliverables: ['Detailed PRD document'],
    acceptanceCriteria: ['Includes user stories, acceptance criteria, wireframe flows, telemetry tracking, and edge cases'],
    difficulty: 3,
    expectedOutput: 'A complete spec sheet ready for designers and software developers.',
    skillsExercised: ['PRD Writing', 'User Story Writing', 'Edge Case Mapping', 'Telemetry Specifying'],
    suggestedTools: ['Notion', 'Confluence'],
    presentationTips: 'Outline success metrics as both primary (leading) and guardrail (lagging) indicators to show business focus.',
  },
  {
    pathSlug: 'product-management',
    stageNumber: 3,
    title: 'Product Launch & GTM Plan',
    description: 'Develop a Go-To-Market (GTM) strategy plan for launching a new SaaS product, detailing positioning and metrics.',
    deliverables: ['Go-To-Market launch strategy deck (PDF link)'],
    acceptanceCriteria: ['Defines positioning statement, target pricing tiers, distribution channels, and launch KPIs'],
    difficulty: 4,
    expectedOutput: 'A high-impact business slide deck outlining the GTM launch strategy.',
    skillsExercised: ['Go-To-Market Strategy', 'Product Positioning', 'Pricing Architecture', 'Marketing Channels'],
    suggestedTools: ['Google Slides', 'Canva', 'Notion'],
    presentationTips: 'Include a slide with a week-by-week timeline of launch activities (pre-launch, launch day, post-launch) to demonstrate operational planning.',
  },
  {
    pathSlug: 'product-management',
    stageNumber: 3,
    title: 'A/B Test Design & Metrics Spec',
    description: 'Design a structured A/B test proposal to optimize a conversion funnel, outlining hypotheses and sample size calculations.',
    deliverables: ['A/B testing spec document'],
    acceptanceCriteria: ['Includes baseline metrics, hypothesis, variant UI mocks, sample size, and statistical significance conditions'],
    difficulty: 5,
    expectedOutput: 'A technical testing plan document detailing hypothesis statements and statistical evaluation thresholds.',
    skillsExercised: ['A/B Testing Design', 'Statistical Significance', 'Conversion Funnels', 'Hypothesis Testing'],
    suggestedTools: ['Notion', 'Optimizely Calculator', 'Figma'],
    presentationTips: 'Explain the MDE (Minimum Detectable Effect) and how it affects the runtime duration of your proposed test.',
  },

  // ── Content Strategy ──
  {
    pathSlug: 'content-strategy',
    stageNumber: 1,
    title: 'UX Writing & Copy Refactoring',
    description: 'Critique and rewrite three examples of confusing interface copy (error states, modals, onboarding) from live apps.',
    deliverables: ['Before/after comparison table', 'Explanation of changes (Plain Language guidelines)'],
    acceptanceCriteria: ['Explanations point to readability and tone standards', 'Final copies are clear and accessible'],
    difficulty: 1,
    expectedOutput: 'A side-by-side refactoring study showing improved visual readability and shorter word counts.',
    skillsExercised: ['UX Writing', 'Plain Language Principles', 'Tone Refinement', 'Critique Writing'],
    suggestedTools: ['Notion', 'Figma'],
    presentationTips: 'Provide mockups showing the original vs. rewritten copy in context on a screen overlay.',
  },
  {
    pathSlug: 'content-strategy',
    stageNumber: 1,
    title: 'Content Audit Spreadsheet',
    description: 'Perform a comprehensive content audit of at least 20 articles or pages of a brand, grading readability and metadata.',
    deliverables: ['Audit database spreadsheet link', 'Brief analysis report detailing 3 recommendations (300 words)'],
    acceptanceCriteria: ['Audits at least 20 content assets', 'Categorizes content by format, target audience, and performance'],
    difficulty: 2,
    expectedOutput: 'An structured audit sheet showing graded content scores and SEO recommendations.',
    skillsExercised: ['Content Auditing', 'Grading Frameworks', 'SEO Analysis', 'Content Recommendation'],
    suggestedTools: ['Google Sheets', 'Airtable'],
    presentationTips: 'Use conditional formatting (e.g. red, yellow, green) to color-code content quality scores for quick scanning.',
  },
  {
    pathSlug: 'content-strategy',
    stageNumber: 2,
    title: 'Search Optimization Refactoring',
    description: 'Select two blog articles and optimize their structures, headings, titles, and meta descriptions for search visibility.',
    deliverables: ['SEO optimized copy documents', 'Keyword research map page'],
    acceptanceCriteria: ['Includes targeted keyword mappings, optimized H1/H2 structures, title tags, and meta descriptions'],
    difficulty: 2,
    expectedOutput: 'SEO-ready content documents showing keyword usage and search engine snippet configurations.',
    skillsExercised: ['Search Engine Optimization (SEO)', 'Keyword Mapping', 'Meta Tag Formatting', 'Content Structuring'],
    suggestedTools: ['Google Docs', 'Ahrefs', 'Semrush'],
    presentationTips: 'Write out the title tags and meta descriptions within the character limit guidelines (e.g. titles under 60 chars).',
  },
  {
    pathSlug: 'content-strategy',
    stageNumber: 2,
    title: 'Editorial Calendar & Brand Kit',
    description: 'Build a comprehensive 1-month editorial calendar and content pipeline aligned to a brand voice style guide.',
    deliverables: ['1-month editorial calendar (Notion or Airtable)', 'Brand voice style guide sheet'],
    acceptanceCriteria: ['Calendar schedules at least 8 distinct content assets', 'Style guide details tone descriptors and formatting guidelines'],
    difficulty: 3,
    expectedOutput: 'A complete content production plan detailing timeline, resources, and publishing channels.',
    skillsExercised: ['Editorial Planning', 'Brand Style Guides', 'Content Distribution', 'Resource Planning'],
    suggestedTools: ['Notion', 'Airtable', 'Trello'],
    presentationTips: 'Add a "Do" and "Don\'t" section for writing examples in the style guide to make it highly practical.',
  },
  {
    pathSlug: 'content-strategy',
    stageNumber: 3,
    title: '4-Week Newsletter Launch Campaign',
    description: 'Design, write, and launch a 4-week email newsletter campaign on a specific topic, showing audience growth metrics.',
    deliverables: ['Public newsletter page link', 'PDF copies of all 4 sent newsletters', 'Launch growth report'],
    acceptanceCriteria: ['Each newsletter issue is >300 words of original content', 'Campaign includes growth metrics (subscribers, click rates)'],
    difficulty: 4,
    expectedOutput: 'A series of sent newsletters showing professional email layouts and copywriting strategies.',
    skillsExercised: ['Email Copywriting', 'Newsletter Optimization', 'Audience Growth', 'Performance Metrics'],
    suggestedTools: ['Substack', 'MailerLite', 'ConvertKit'],
    presentationTips: 'Explain the open rates and click rates, detailing what changes you made to the subject lines to boost performance.',
  },
  {
    pathSlug: 'content-strategy',
    stageNumber: 3,
    title: 'Comprehensive Content Marketing Strategy',
    description: 'Formulate an end-to-end content marketing campaign proposal for a brand, detailing strategy, execution channels, and KPIs.',
    deliverables: ['Campaign strategy document (PDF or Notion)'],
    acceptanceCriteria: ['Outlines user personas, funnel stages, content formats, distribution channels, and analytics tracking metrics'],
    difficulty: 5,
    expectedOutput: 'A strategic document mapping content assets to the customer acquisition funnel.',
    skillsExercised: ['Content Marketing', 'Acquisition Funnels', 'Multi-channel Distribution', 'Marketing Analytics'],
    suggestedTools: ['Notion', 'Google Slides'],
    presentationTips: 'Include a visual diagram mapping out how top-of-funnel (TOFU) blog traffic flows to bottom-of-funnel (BOFU) product landing pages.',
  },

  // ── Backend Engineering ──
  {
    pathSlug: 'backend-engineering',
    stageNumber: 1,
    title: 'RESTful API with Node.js & Express',
    description: 'Build a fully operational CRUD REST API using Node.js, Express, and memory storage, verifying endpoints with Postman.',
    deliverables: ['GitHub Repository link', 'Postman collection JSON file'],
    acceptanceCriteria: ['Valid JSON responses', 'Includes proper HTTP status codes for success and error states', 'Implements endpoints for all CRUD actions'],
    difficulty: 1,
    expectedOutput: 'A Node.js web server exposing endpoints with proper error validation.',
    skillsExercised: ['Node.js Programming', 'Express Framework', 'REST Specifications', 'API Endpoint Verification'],
    suggestedTools: ['VS Code', 'Postman', 'JavaScript'],
    presentationTips: 'Include a detailed readme with a table mapping all routes, expected payloads, and responses.',
  },
  {
    pathSlug: 'backend-engineering',
    stageNumber: 1,
    title: 'Relational Database Schema Design',
    description: 'Design a relational database schema for a complex system (e.g. e-commerce, blogging platform) using PostgreSQL.',
    deliverables: ['Entity Relationship Diagram (ERD)', 'SQL DDL script creating tables and relations'],
    acceptanceCriteria: ['Schema in 3rd Normal Form (3NF)', 'Tables must have appropriate keys and foreign key constraints'],
    difficulty: 2,
    expectedOutput: 'An ERD image and SQL scripts creating databases with constraints.',
    skillsExercised: ['Database Schema Design', 'SQL DDL Syntax', 'Normalization Standards', 'ERD Tooling'],
    suggestedTools: ['draw.io', 'dbdiagram.io', 'PostgreSQL'],
    presentationTips: 'Write a description explaining your indexing choices on foreign keys to show performance awareness.',
  },
  {
    pathSlug: 'backend-engineering',
    stageNumber: 2,
    title: 'API Authentication & JWT Authorization',
    description: 'Secure a Node.js REST API with JWT authorization, password hashing, and user roles.',
    deliverables: ['GitHub Repository', 'Endpoints testing screenshots'],
    acceptanceCriteria: ['User passwords hashed using bcrypt', 'Protected endpoints requiring valid Authorization header JWTs', 'Role-based access limits (admin vs. user)'],
    difficulty: 2,
    expectedOutput: 'A secure backend API project implementing password encryption and session token auth.',
    skillsExercised: ['JWT Authentication', 'Password Encryption', 'Role-based Authorization', 'Web Security'],
    suggestedTools: ['Node.js', 'bcryptjs', 'jsonwebtoken', 'Postman'],
    presentationTips: 'Add unit tests checking that access is denied when unauthorized users query protected endpoints.',
  },
  {
    pathSlug: 'backend-engineering',
    stageNumber: 2,
    title: 'Dockerize a Microservices API Suite',
    description: 'Containerize a backend application and database, running them concurrently using Docker Compose.',
    deliverables: ['Dockerfiles for services', 'docker-compose.yml file configurations', 'Setup instructions inside readme'],
    acceptanceCriteria: ['Services start in order with healthcheck guards', 'Database volume configuration saves data between runs'],
    difficulty: 3,
    expectedOutput: 'A multi-container application runnable with a single command.',
    skillsExercised: ['Docker Containerization', 'Docker Compose Routing', 'Environment Configuration', 'Volume Mounts'],
    suggestedTools: ['Docker Desktop', 'Node.js', 'PostgreSQL'],
    presentationTips: 'Write multi-stage Dockerfiles to minimize the size of final production images.',
  },
  {
    pathSlug: 'backend-engineering',
    stageNumber: 3,
    title: 'Real-time Message Broker Integration',
    description: 'Build a background workers queue system using Node.js and Redis (BullMQ or RabbitMQ) to handle heavy tasks asynchronously.',
    deliverables: ['GitHub Repository link', 'Workers log configuration outputs'],
    acceptanceCriteria: ['Worker processes run independently from the main web server', 'Failsafe retries and queue log monitoring are implemented'],
    difficulty: 4,
    expectedOutput: 'A robust microservices system managing async task processing.',
    skillsExercised: ['Message Queues', 'Redis Caching', 'Background Workers', 'Asynchronous Architecture'],
    suggestedTools: ['Node.js', 'Redis', 'BullMQ', 'Docker'],
    presentationTips: 'Document how the system handles database locks and concurrent queries when worker counts scale up.',
  },
  {
    pathSlug: 'backend-engineering',
    stageNumber: 3,
    title: 'Production API Load Optimization & Caching',
    description: 'Implement Redis caching and database indexing optimizations in a slow API to handle high load traffic.',
    deliverables: ['GitHub Repository link', 'Autocannon/k6 load test comparison reports'],
    acceptanceCriteria: ['Lighthouse load response times drop by >50%', 'API handles at least 500 requests per second without errors'],
    difficulty: 5,
    expectedOutput: 'A high-performance backend API with optimized queries and Redis response caching.',
    skillsExercised: ['Database Optimizations', 'Redis Cache Keys', 'Load Testing Tools', 'Index Profiling'],
    suggestedTools: ['k6', 'Redis', 'PostgreSQL EXPLAIN', 'Node.js'],
    presentationTips: 'Provide k6 report graphics displaying latency charts and error rates under stress testing in the repository.',
  },

  // ── Cybersecurity ──
  {
    pathSlug: 'cybersecurity',
    stageNumber: 1,
    title: 'Linux Commands & Server Hardening Script',
    description: 'Create a bash script to perform basic security checks and server hardening steps on a Linux distribution.',
    deliverables: ['Hardening shell script file on GitHub', 'Server audit output log'],
    acceptanceCriteria: ['Script disables SSH root login, audits open ports, and configures a simple firewall (UFW)'],
    difficulty: 1,
    expectedOutput: 'A bash utility script performing server system audits and applying permissions.',
    skillsExercised: ['Linux Scripting', 'Server Hardening', 'Firewall Configurations', 'System Auditing'],
    suggestedTools: ['Ubuntu Server', 'Bash', 'UFW', 'SSH Security'],
    presentationTips: 'Structure your script with verbose console outputs and logs so users know exactly what actions are being run.',
  },
  {
    pathSlug: 'cybersecurity',
    stageNumber: 1,
    title: 'Network Port Auditing & Analysis',
    description: 'Perform a network sweep of a local target machine using Nmap, analyzing open ports and vulnerability vectors.',
    deliverables: ['Nmap audit report (PDF or Markdown)', 'Remediation guidelines document'],
    acceptanceCriteria: ['Sweeps targets and identifies running services and versions', 'Advises concrete patching steps for discovered open ports'],
    difficulty: 2,
    expectedOutput: 'A detailed port mapping security report specifying risk zones.',
    skillsExercised: ['Network Auditing', 'Nmap Syntaxes', 'Risk Assessment', 'Service Version Scan'],
    suggestedTools: ['Nmap', 'Kali Linux', 'Wireshark'],
    presentationTips: 'Write descriptions of the risk for each open port, linking back to official CVE references.',
  },
  {
    pathSlug: 'cybersecurity',
    stageNumber: 2,
    title: 'Web Application Penetration Test',
    description: 'Perform a penetration test on an intentionally vulnerable web application, identifying OWASP Top 10 vulnerabilities.',
    deliverables: ['Security audit findings report (OWASP guidelines)', 'Proof-of-concept exploits'],
    acceptanceCriteria: ['Discovers and documents at least 3 vulnerabilities (e.g. SQLi, XSS, CSRF)', 'Provides remediation code snippets to patch issues'],
    difficulty: 2,
    expectedOutput: 'A web security report detailing vulnerabilities and patch codes.',
    skillsExercised: ['Web Security Audits', 'OWASP Standards', 'Exploit Proofs', 'Code Patching'],
    suggestedTools: ['OWASP ZAP', 'Burp Suite', 'DVWA'],
    presentationTips: 'Show side-by-side code diffs of the vulnerable code and the patched secure code version.',
  },
  {
    pathSlug: 'cybersecurity',
    stageNumber: 2,
    title: 'Secure Code Auditing & Static Review',
    description: 'Review and audit a repository code bundle for vulnerabilities using static code analysis tools (SAST) and manual review.',
    deliverables: ['SAST results output file', 'Manual audit summary detailing security gaps'],
    acceptanceCriteria: ['Identifies hardcoded API keys, SQL injections, and buffer overflows', 'Highlights dangerous dependency updates needed'],
    difficulty: 3,
    expectedOutput: 'A code health security report detailing vulnerability lines.',
    skillsExercised: ['Static Analysis', 'Manual Code Audits', 'Dependency Scans', 'SAST Reporting'],
    suggestedTools: ['SonarQube', 'Snyk', 'GitHub Dependabot'],
    presentationTips: 'Categorize finding alerts by severity tiers (High, Medium, Low) to keep remediation plans structured.',
  },
  {
    pathSlug: 'cybersecurity',
    stageNumber: 3,
    title: 'IAM Policy & Infrastructure Hardening',
    description: 'Formulate a secure Identity and Access Management (IAM) role set for a cloud workspace, enforcing Least Privilege access rules.',
    deliverables: ['JSON IAM policy documents', 'IAM roles organizational chart'],
    acceptanceCriteria: ['Policies restrict access to only required services', 'Includes audit configurations for policy change monitoring'],
    difficulty: 4,
    expectedOutput: 'JSON configurations mapping groups, users, and actions.',
    skillsExercised: ['IAM Configuration', 'Least Privilege Access', 'JSON Policy Formats', 'Cloud Security'],
    suggestedTools: ['AWS IAM', 'Azure Active Directory'],
    presentationTips: 'Write a walkthrough explaining how your IAM design prevents privilege escalation loops.',
  },
  {
    pathSlug: 'cybersecurity',
    stageNumber: 3,
    title: 'Incident Response & Log Analysis Report',
    description: 'Analyze an access log file from a compromised web server, reconstructing the attacker journey and timeline.',
    deliverables: ['Timeline of attack analysis deck (PDF)', 'Remediation plan for future prevention'],
    acceptanceCriteria: ['Report identifies attacker IP, entry vector, commands run, and databases breached'],
    difficulty: 5,
    expectedOutput: 'A detailed forensic analysis document detailing the attack vector.',
    skillsExercised: ['Forensics Log Scan', 'Timeline Reconstruction', 'Attacker Profiling', 'Incident Mitigation'],
    suggestedTools: ['Wireshark', 'Splunk', 'Linux Log Files'],
    presentationTips: 'Outline your findings starting with an Executive Summary (1 page) explaining the business impact of the incident.',
  },

  // ── Cloud Engineering ──
  {
    pathSlug: 'cloud-engineering',
    stageNumber: 1,
    title: 'AWS Static Website Hosting',
    description: 'Deploy a static HTML site to Amazon S3, configuring it for public web access and linking it to CloudFront CDN.',
    deliverables: ['Live website URL', 'Cloud architecture setup notes'],
    acceptanceCriteria: ['Site serves assets correctly over HTTPS using CloudFront', 'Bucket access is blocked except from CloudFront OAC'],
    difficulty: 1,
    expectedOutput: 'A live web domain serving static pages through CloudFront.',
    skillsExercised: ['Amazon S3 Hosting', 'CloudFront Distribution', 'HTTPS Configuration', 'Access Policies'],
    suggestedTools: ['AWS S3', 'AWS CloudFront', 'Route 53'],
    presentationTips: 'Provide a screenshot of the HTTPS padlock and explain how CDN cache caching improves server loads.',
  },
  {
    pathSlug: 'cloud-engineering',
    stageNumber: 1,
    title: 'Terraform Local Server Deploy',
    description: 'Write Terraform scripts to create a local virtual machine or cloud instance automatically.',
    deliverables: ['Terraform configuration script files (.tf)', 'Terraform init and apply outputs logs'],
    acceptanceCriteria: ['Terraform scripts contain variables, provider setup, and outputs', 'Running terraform apply creates resources correctly'],
    difficulty: 2,
    expectedOutput: 'Automated Terraform code scripts deploying virtual nodes.',
    skillsExercised: ['Infrastructure as Code (IaC)', 'Terraform Provider Settings', 'Variable Scoping', 'State Management'],
    suggestedTools: ['Terraform CLI', 'VirtualBox', 'AWS Provider'],
    presentationTips: 'Write descriptions of variables in your Terraform scripts to document what properties they take.',
  },
  {
    pathSlug: 'cloud-engineering',
    stageNumber: 2,
    title: 'Multi-Stage CI/CD Deployment Pipeline',
    description: 'Set up a CI/CD pipeline (GitHub Actions or GitLab CI) that builds, tests, and deploys a web application on commits.',
    deliverables: ['Pipeline configuration files (.yml)', 'Successful build pipeline runner screenshots'],
    acceptanceCriteria: ['Pipeline triggers automatically on code push', 'Fails building if test runners report errors'],
    difficulty: 2,
    expectedOutput: 'A fully functional automated build pipeline executing checks.',
    skillsExercised: ['CI/CD Orchestration', 'GitHub Actions Syntax', 'Automated Testing', 'Continuous Deployment'],
    suggestedTools: ['GitHub Actions', 'Docker', 'Vercel CLI'],
    presentationTips: 'Utilize caching for node_modules in your pipelines to reduce build runtimes.',
  },
  {
    pathSlug: 'cloud-engineering',
    stageNumber: 2,
    title: 'Scale Web Server Cluster behind Load Balancer',
    description: 'Deploy an application cluster behind an ALB (Application Load Balancer) with Auto-Scaling groups triggered by CPU limits.',
    deliverables: ['Infrastructure setup script (Terraform or CloudFormation)', 'Load test monitoring graphics'],
    acceptanceCriteria: ['ALB balances connections between at least 2 nodes', 'Auto-scaling group creates new servers during load tests'],
    difficulty: 3,
    expectedOutput: 'A self-healing scaled server deployment topology.',
    skillsExercised: ['Load Balancing (ALB)', 'Auto-Scaling Groups', 'CPU Trigger Configuration', 'High Availability'],
    suggestedTools: ['AWS EC2', 'AWS ALB', 'Terraform', 'ApacheBench'],
    presentationTips: 'Explain the cooldown period and metrics you chose for auto-scaling triggers in your documentation.',
  },
  {
    pathSlug: 'cloud-engineering',
    stageNumber: 3,
    title: 'Automated Kubernetes Deployment Config',
    description: 'Deploy a multi-tier application using Kubernetes configurations, detailing pods, services, and volume mounts.',
    deliverables: ['Kubernetes manifest YAML files', 'Running kubectl status logs'],
    acceptanceCriteria: ['Pods handle database connectivity with secret configs', 'App includes ingress or service definitions for outer traffic'],
    difficulty: 4,
    expectedOutput: 'Kubernetes configuration YAML files running clustered components.',
    skillsExercised: ['Kubernetes Orchestration', 'YAML Configurations', 'Service Definition', 'Persistent Volume Mounts'],
    suggestedTools: ['Minikube', 'kubectl CLI', 'Docker Hub'],
    presentationTips: 'Highlight the database migration runner container inside your pods to show end-to-end setup planning.',
  },
  {
    pathSlug: 'cloud-engineering',
    stageNumber: 3,
    title: 'Serverless API & Database Architecture',
    description: 'Deploy a serverless backend system using AWS Lambda and DynamoDB, structured via Terraform.',
    deliverables: ['Terraform configs for serverless setup', 'End-to-end API test screenshots'],
    acceptanceCriteria: ['API endpoints trigger Lambda executions', 'Database queries write to DynamoDB tables correctly'],
    difficulty: 5,
    expectedOutput: 'A fully serverless infrastructure topology with zero running server costs when idle.',
    skillsExercised: ['AWS Lambda Settings', 'DynamoDB Design', 'API Gateway Integrations', 'Serverless Terraform'],
    suggestedTools: ['AWS API Gateway', 'Lambda', 'DynamoDB', 'Terraform'],
    presentationTips: 'Outline cold start speed metrics and DynamoDB partition key strategies inside your design doc.',
  },

  // ── Digital Marketing ──
  {
    pathSlug: 'digital-marketing',
    stageNumber: 1,
    title: 'Competitor Digital Presence Audit',
    description: 'Analyze a brand\'s digital presence, comparing it with 2 competitors on SEO, search ads, and social media.',
    deliverables: ['Digital audit report presentation slide deck (PDF link)'],
    acceptanceCriteria: ['Compares 3 channels (SEO, Ads, Social)', 'Identifies 3 competitor gaps and outlines opportunities for growth'],
    difficulty: 1,
    expectedOutput: 'A comprehensive brand performance review deck with competitive insights.',
    skillsExercised: ['Digital Competitor Audit', 'SEO Performance Grades', 'Ad Strategy Analysis', 'Marketing Channel Review'],
    suggestedTools: ['SimilarWeb', 'SEMrush', 'Google Search'],
    presentationTips: 'Use visual tables or charts to compare page ranks and keyword weights side-by-side.',
  },
  {
    pathSlug: 'digital-marketing',
    stageNumber: 1,
    title: 'Search Ads Copywriting & Structuring',
    description: 'Create a Google Search Ad campaign skeleton with keyword match types, ad groups, headlines, and callout extensions.',
    deliverables: ['Campaign outline spreadsheet (Excel/Notion link)'],
    acceptanceCriteria: ['Includes at least 3 distinct ad groups', 'Features 3 headlines and 2 description copies per ad group'],
    difficulty: 2,
    expectedOutput: 'A structured campaign spreadsheet ready for import into Google Ads.',
    skillsExercised: ['Google Ads Copywriting', 'Keyword Match Scoping', 'Ad Group Structuring', 'Headline Writing'],
    suggestedTools: ['Google Ads Keyword Planner', 'Google Sheets'],
    presentationTips: 'Write headlines that directly include the high-intent keywords to improve Quality Scores.',
  },
  {
    pathSlug: 'digital-marketing',
    stageNumber: 2,
    title: 'Organic SEO Keyword Mapping Strategy',
    description: 'Perform search keyword research for a niche brand, mapping terms to content topics across funnel stages (TOFU, MOFU, BOFU).',
    deliverables: ['SEO keyword mapping master sheet', 'Brief strategic memo (400 words)'],
    acceptanceCriteria: ['Audits and lists at least 30 targeted keywords', 'Maps keywords explicitly to user funnel stages'],
    difficulty: 2,
    expectedOutput: 'A structured keyword-to-content map spreadsheet.',
    skillsExercised: ['Keyword Research', 'SEO Intent Mapping', 'Funnel Optimization', 'Strategy Development'],
    suggestedTools: ['Ahrefs', 'Semrush', 'Google Sheets'],
    presentationTips: 'Color-code the keyword search volumes and difficulty scores to highlight high-value targets.',
  },
  {
    pathSlug: 'digital-marketing',
    stageNumber: 2,
    title: 'Email Acquisition Landing Page Copy & Setup',
    description: 'Design and write copy for an email capture landing page, setting up an automated email sequence to engage new leads.',
    deliverables: ['Copywriting docs for landing page', 'Automated email sequence scripts (3 emails)'],
    acceptanceCriteria: ['Landing page copy includes CTA buttons and value propositions', 'Automated emails have custom subject lines and engagement triggers'],
    difficulty: 3,
    expectedOutput: 'An acquisition framework planning copy, conversions, and email workflows.',
    skillsExercised: ['Landing Page Copywriting', 'Lead Generation Systems', 'Email Automations', 'A/B Testing Copy'],
    suggestedTools: ['MailerLite', 'Mailchimp', 'Notion'],
    presentationTips: 'Clearly outline the lead magnet (e.g. ebook, free trial) value in the main header of the landing page.',
  },
  {
    pathSlug: 'digital-marketing',
    stageNumber: 3,
    title: 'Paid Media Budget Allocation Model',
    description: 'Build a spreadsheet calculating budget splits, CPC, CTR, and CPA targets for a $10,000 multi-channel marketing campaign.',
    deliverables: ['Budget allocation model (Google Sheets link)', 'Strategic rationale report (500 words)'],
    acceptanceCriteria: ['Model links CPC, CTR, and CPA targets dynamically using formulas', 'Splits budget across at least 3 paid channels based on KPIs'],
    difficulty: 4,
    expectedOutput: 'A dynamic budget modeling spreadsheet forecasting performance outcomes.',
    skillsExercised: ['Marketing Mathematics', 'Paid Budget Allocation', 'KPI Forecasting', 'ROI Modeling'],
    suggestedTools: ['Google Sheets', 'Excel'],
    presentationTips: 'Include a summary table with simulated scenarios (worst-case, expected, best-case) to show risk planning.',
  },
  {
    pathSlug: 'digital-marketing',
    stageNumber: 3,
    title: 'Comprehensive Growth Marketing Campaign Plan',
    description: 'Create an end-to-end multi-channel growth marketing plan for a product launch, outlining targets, channels, and metrics.',
    deliverables: ['Campaign proposal playbook deck (PDF link)'],
    acceptanceCriteria: [' playbook covers audience definitions, channel strategies, attribution models, and conversion tracking specifications'],
    difficulty: 5,
    expectedOutput: 'A professional marketing campaign deck detailing targets, attribution, and timelines.',
    skillsExercised: ['Growth Marketing Strategy', 'Campaign Orchestration', 'Attribution Modeling', 'Conversion Auditing'],
    suggestedTools: ['Google Slides', 'Canva'],
    presentationTips: 'Include an analytics tagging section detailing custom events and UTM conventions to show tracking competence.',
  },

  // ── Machine Learning Engineering ──
  {
    pathSlug: 'machine-learning-engineering',
    stageNumber: 1,
    title: 'Exploratory Machine Learning Study',
    description: 'Train a basic classification model (e.g., Logistic Regression, Decision Tree) on a tabular dataset using scikit-learn.',
    deliverables: ['Jupyter Notebook on GitHub', 'Confusion matrix and metrics charts'],
    acceptanceCriteria: ['Includes data cleaning, scaling, and feature selection steps', 'Evaluates models using Accuracy, Precision, Recall, and F1-score'],
    difficulty: 1,
    expectedOutput: 'A Jupyter notebook running data prep, model training, and performance evaluations.',
    skillsExercised: ['Exploratory ML', 'scikit-learn Classifiers', 'Feature Scaling', 'Evaluation Metrics'],
    suggestedTools: ['Python', 'scikit-learn', 'pandas', 'Kaggle'],
    presentationTips: 'Explain the business impact of false positives vs. false negatives to show product understanding.',
  },
  {
    pathSlug: 'machine-learning-engineering',
    stageNumber: 1,
    title: 'Housing Price Estimator Model',
    description: 'Train a regression model to estimate housing prices, using feature engineering on spatial and categorical fields.',
    deliverables: ['GitHub Repository link', 'Model weights performance summary'],
    acceptanceCriteria: ['Validates models using RMSE or MAE metrics', 'Implements feature engineering like one-hot encoding'],
    difficulty: 2,
    expectedOutput: 'A model pipeline preprocessing datasets and outputting continuous numeric estimations.',
    skillsExercised: ['Regression Analysis', 'Feature Engineering', 'Cross-Validation Techniques', 'Model Pipelines'],
    suggestedTools: ['Python', 'scikit-learn', 'pandas'],
    presentationTips: 'Compare performance before and after feature engineering to demonstrate its impact.',
  },
  {
    pathSlug: 'machine-learning-engineering',
    stageNumber: 2,
    title: 'Neural Network Image Classifier',
    description: 'Build and train a Convolutional Neural Network (CNN) in PyTorch or TensorFlow to classify images.',
    deliverables: ['GitHub Repository', 'Training loss and evaluation curves charts'],
    acceptanceCriteria: ['Model achieves >80% test accuracy', 'Includes image normalization and augmentation steps'],
    difficulty: 2,
    expectedOutput: 'A PyTorch/TensorFlow project folder containing convolutional neural network models.',
    skillsExercised: ['Deep Learning', 'PyTorch / TensorFlow Syntax', 'Image Augmentations', 'Epoch Evaluations'],
    suggestedTools: ['PyTorch', 'TensorFlow', 'Google Colab'],
    presentationTips: 'Add data visualizations displaying sample images with predicted vs. true labels.',
  },
  {
    pathSlug: 'machine-learning-engineering',
    stageNumber: 2,
    title: 'Text Classification & Sentiment NLP',
    description: 'Build a natural language processing model to analyze sentiment or classify articles into categories.',
    deliverables: ['Jupyter Notebook link', 'Model classification reports'],
    acceptanceCriteria: ['Implements text cleaning, tokenization, and vectorization (TF-IDF or Word Embeddings)', 'Includes model comparison results'],
    difficulty: 3,
    expectedOutput: 'An NLP project preprocessing string variables and scoring text blocks.',
    skillsExercised: ['NLP Preprocessing', 'Text Tokenization', 'Vectorization Methods', 'Model Comparisons'],
    suggestedTools: ['Python', 'NLTK', 'scikit-learn', 'Hugging Face Transformers'],
    presentationTips: 'Explain the choice of embedding vectors and their impact on vocabulary scope.',
  },
  {
    pathSlug: 'machine-learning-engineering',
    stageNumber: 3,
    title: 'Deploy ML Model as Web Service API',
    description: 'Wrap a trained ML model in a FastAPI framework, deploy it as a Docker service, and expose prediction endpoints.',
    deliverables: ['GitHub Repository link', 'Prediction endpoint API logs'],
    acceptanceCriteria: ['FastAPI server serves model predictions in JSON format', 'Includes input validation checks using pydantic schemas'],
    difficulty: 4,
    expectedOutput: 'A Docker container serving predictions over HTTP requests.',
    skillsExercised: ['FastAPI Service Wrappers', 'Model Serialization (Joblib/Pickle)', 'Input Validations', 'Docker Packaging'],
    suggestedTools: ['FastAPI', 'Docker', 'Uvicorn', 'Pydantic'],
    presentationTips: 'Include documentation on how the API manages request batching and prevents memory leaks during high traffic.',
  },
  {
    pathSlug: 'machine-learning-engineering',
    stageNumber: 3,
    title: 'Automated MLOps Pipeline & Monitoring',
    description: 'Build an automated machine learning pipeline (Prefect or Kubeflow) that registers models in a registry (MLflow) and monitors drift.',
    deliverables: ['MLOps pipeline code repository', 'Drift monitoring logs output screenshots'],
    acceptanceCriteria: ['Pipeline executes automated data extraction, model training, and version registering', 'Tracks feature drift metrics'],
    difficulty: 5,
    expectedOutput: 'A production pipeline that automatically retrains and monitors models.',
    skillsExercised: ['MLOps Engineering', 'Model Registries (MLflow)', 'Data Drift Trackers', 'Pipeline Orchestration'],
    suggestedTools: ['MLflow', 'Prefect', 'Evidently AI', 'Docker'],
    presentationTips: 'Provide a system topology diagram illustrating data flow from database tables to MLflow and production nodes.',
  },
];

const SEED_COMPANIES = [
  {
    email: 'hire@buildco.io',
    password: 'Seed1234!',
    company: { name: 'BuildCo', description: 'We build B2B SaaS tools for operations teams.', website: 'https://buildco.io', industry: 'Technology', size: '11–50' },
    roles: [
      { title: 'Junior Frontend Engineer', description: 'Join our product team to build the interfaces our customers use every day. You will work with React, TypeScript, and a modern design system.', tags: ['React', 'TypeScript', 'CSS'], pathSlugs: ['frontend-engineering'], experienceLevel: 'Beginner', region: 'Europe' },
      { title: 'Product Designer', description: 'We are looking for a product designer to own the end-to-end design of our core product. You will run research, create prototypes, and work closely with engineers.', tags: ['Figma', 'UX', 'Research'], pathSlugs: ['product-design'], experienceLevel: 'Intermediate', region: 'Europe' },
    ],
  },
  {
    email: 'talent@dataworks.io',
    password: 'Seed1234!',
    company: { name: 'DataWorks', description: 'A data consultancy helping mid-size businesses make better decisions with their data.', website: 'https://dataworks.io', industry: 'Technology', size: '51–200' },
    roles: [
      { title: 'Data Analyst', description: 'Help our clients answer their most important business questions through data. You will work with SQL, Python, and Tableau to deliver insights and dashboards.', tags: ['SQL', 'Python', 'Tableau'], pathSlugs: ['data-analysis'], experienceLevel: 'Beginner', region: 'West Africa' },
    ],
  },
  {
    email: 'careers@launchpm.co',
    password: 'Seed1234!',
    company: { name: 'LaunchPM', description: 'An early-stage startup building the next generation of project management tools.', website: 'https://launchpm.co', industry: 'Technology', size: '1-10' },
    roles: [
      { title: 'Associate Product Manager', description: 'A rare opportunity to join as an APM at an early-stage startup. You will own features end-to-end, run user research, and write specs that ship.', tags: ['Strategy', 'Agile', 'Roadmapping'], pathSlugs: ['product-management'], experienceLevel: 'Beginner', region: 'North America' },
      { title: 'Content Strategist', description: 'Own our content presence from blog to in-app copy. You will define our voice, build an editorial calendar, and grow our audience from the ground up.', tags: ['Writing', 'SEO', 'Editorial'], pathSlugs: ['content-strategy'], experienceLevel: 'Intermediate', region: 'North America' },
    ],
  },
];

async function main() {
  console.log('Seeding career paths...');
  for (const path of CAREER_PATHS) {
    await prisma.careerPath.upsert({
      where: { slug: path.slug },
      update: {
        name: path.name,
        description: path.description,
        tags: path.tags,
      },
      create: path,
    });
  }

  console.log('Seeding roadmap stages...');
  // We need to clean up old stages to avoid stage number mismatch if there were 5
  await prisma.roadmapStage.deleteMany({});
  for (const stage of ROADMAP_STAGES) {
    await prisma.roadmapStage.create({
      data: stage,
    });
  }

  console.log('Seeding tasks...');
  // Clean up old tasks to support the new schema and 3-tier tasks
  await prisma.task.deleteMany({});
  for (const task of TASKS) {
    await prisma.task.create({
      data: {
        ...task,
        status: 'active',
      },
    });
  }

  console.log('Seeding companies and roles...');
  for (const seed of SEED_COMPANIES) {
    let user = await prisma.user.findUnique({ where: { email: seed.email } });
    if (!user) {
      const passwordHash = await bcrypt.hash(seed.password, 10);
      user = await prisma.user.create({ data: { email: seed.email, passwordHash, role: 'employer' } });
    }

    let company = await prisma.company.findUnique({ where: { userId: user.id } });
    if (!company) {
      company = await prisma.company.create({ data: { userId: user.id, ...seed.company } });
    }

    for (const role of seed.roles) {
      const existing = await prisma.roleOpening.findFirst({
        where: { companyId: company.id, title: role.title },
      });
      if (!existing) {
        await prisma.roleOpening.create({ data: { companyId: company.id, ...role, status: 'open' } });
      }
    }
  }

  console.log(`Seeded ${CAREER_PATHS.length} paths, ${ROADMAP_STAGES.length} stages, ${TASKS.length} tasks, and ${SEED_COMPANIES.length} companies with roles.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
