export const TASKS_PART_2 = [
  // ════════════════════════════════════════════
  // 6. BACKEND ENGINEERING
  // ════════════════════════════════════════════
  // Stage 1 (Beginner)
  {
    pathSlug: 'backend-engineering',
    stageNumber: 1,
    title: 'RESTful API with Node.js & Express',
    description: 'Build a fully operational CRUD REST API using Node.js, Express, and memory storage, verifying endpoints with Postman.',
    deliverables: ['GitHub Repository link', 'Postman collection JSON file'],
    acceptanceCriteria: ['Valid JSON responses', 'Includes proper HTTP status codes for success and error states', 'Implements endpoints for all CRUD actions'],
    difficulty: 1,
    expectedOutput: 'A Node.js web server exposing endpoints with proper error validation.',
    skillsExercised: ['Node.js Programming', 'Express Framework', 'REST Specifications', 'API Endpoint Verification'],
    suggestedTools: ['VS Code', 'Postman', 'JavaScript'],
    presentationTips: 'Include a detailed readme with a table mapping all routes, expected payloads, and responses.',
  },
  {
    pathSlug: 'backend-engineering',
    stageNumber: 1,
    title: 'Relational Database Schema Design',
    description: 'Design a relational database schema for a complex system (e.g. e-commerce, blogging platform) using PostgreSQL.',
    deliverables: ['Entity Relationship Diagram (ERD)', 'SQL DDL script creating tables and relations'],
    acceptanceCriteria: ['Schema in 3rd Normal Form (3NF)', 'Tables must have appropriate keys and foreign key constraints'],
    difficulty: 2,
    expectedOutput: 'An ERD image and SQL scripts creating databases with constraints.',
    skillsExercised: ['Database Schema Design', 'SQL DDL Syntax', 'Normalization Standards', 'ERD Tooling'],
    suggestedTools: ['draw.io', 'dbdiagram.io', 'PostgreSQL'],
    presentationTips: 'Write a description explaining your indexing choices on foreign keys to show performance awareness.',
  },
  {
    pathSlug: 'backend-engineering',
    stageNumber: 1,
    title: 'CLI Application: Data Fetcher',
    description: 'Build a Command Line Interface (CLI) tool using Node.js or Python that fetches data from a public API (like GitHub user activity) and formats the output in the terminal.',
    deliverables: ['GitHub Repository link', 'Screenshot of the terminal execution'],
    acceptanceCriteria: ['Takes command line arguments (e.g., username)', 'Handles API rate limits and connection errors gracefully'],
    difficulty: 1,
    expectedOutput: 'A functional terminal application that interacts with external APIs.',
    skillsExercised: ['CLI Tooling', 'API Consumption', 'Error Handling', 'Argument Parsing'],
    suggestedTools: ['Node.js (Commander.js)', 'Python (Argparse)'],
    presentationTips: 'Add color-coded terminal outputs (e.g., red for errors, green for success) using chalk or similar libraries.',
  },
  {
    pathSlug: 'backend-engineering',
    stageNumber: 1,
    title: 'File Upload & Processing API',
    description: 'Create an endpoint that allows users to upload an image, resizes the image on the server, and saves it locally.',
    deliverables: ['GitHub repository', 'Postman testing screenshot showing the upload'],
    acceptanceCriteria: ['Accepts multipart/form-data requests', 'Rejects non-image files and files over 5MB', 'Resizes images successfully'],
    difficulty: 2,
    expectedOutput: 'A robust file handling API that processes binaries safely.',
    skillsExercised: ['File Uploads (Multer/Busboy)', 'Binary Processing', 'Validation', 'Image Manipulation'],
    suggestedTools: ['Node.js', 'Multer', 'Sharp'],
    presentationTips: 'Show how you structure your `/uploads` directory to avoid naming collisions (e.g., using UUIDs for filenames).',
  },

  // Stage 2 (Intermediate)
  {
    pathSlug: 'backend-engineering',
    stageNumber: 2,
    title: 'API Authentication & JWT Authorization',
    description: 'Secure a Node.js REST API with JWT authorization, password hashing, and user roles.',
    deliverables: ['GitHub Repository', 'Endpoints testing screenshots'],
    acceptanceCriteria: ['User passwords hashed using bcrypt', 'Protected endpoints requiring valid Authorization header JWTs', 'Role-based access limits (admin vs. user)'],
    difficulty: 2,
    expectedOutput: 'A secure backend API project implementing password encryption and session token auth.',
    skillsExercised: ['JWT Authentication', 'Password Encryption', 'Role-based Authorization', 'Web Security'],
    suggestedTools: ['Node.js', 'bcryptjs', 'jsonwebtoken', 'Postman'],
    presentationTips: 'Add unit tests checking that access is denied when unauthorized users query protected endpoints.',
  },
  {
    pathSlug: 'backend-engineering',
    stageNumber: 2,
    title: 'Dockerize a Microservices API Suite',
    description: 'Containerize a backend application and database, running them concurrently using Docker Compose.',
    deliverables: ['Dockerfiles for services', 'docker-compose.yml file configurations', 'Setup instructions inside readme'],
    acceptanceCriteria: ['Services start in order with healthcheck guards', 'Database volume configuration saves data between runs'],
    difficulty: 3,
    expectedOutput: 'A multi-container application runnable with a single command.',
    skillsExercised: ['Docker Containerization', 'Docker Compose Routing', 'Environment Configuration', 'Volume Mounts'],
    suggestedTools: ['Docker Desktop', 'Node.js', 'PostgreSQL'],
    presentationTips: 'Write multi-stage Dockerfiles to minimize the size of final production images.',
  },
  {
    pathSlug: 'backend-engineering',
    stageNumber: 2,
    title: 'Build a URL Shortener Service',
    description: 'Develop an API that takes long URLs and generates a unique, short alias that redirects to the original link.',
    deliverables: ['GitHub Repository link', 'Live API deployment URL'],
    acceptanceCriteria: ['Generates short alphanumeric hashes', 'Redirects (HTTP 301/302) to the original URL when the short link is hit', 'Tracks click counts'],
    difficulty: 3,
    expectedOutput: 'A fully functional URL shortening service demonstrating database lookups and HTTP redirection.',
    skillsExercised: ['Hashing Algorithms', 'HTTP Redirects', 'Database Indexing', 'API Design'],
    suggestedTools: ['Node.js', 'MongoDB / Redis'],
    presentationTips: 'Explain your collision handling logic—what happens if the hashing algorithm generates the same hash twice?',
  },
  {
    pathSlug: 'backend-engineering',
    stageNumber: 2,
    title: 'Implement ORM & Database Migrations',
    description: 'Refactor a raw SQL backend to use an ORM (Prisma or TypeORM), implementing seed scripts and migration files.',
    deliverables: ['GitHub repository with the refactored code', 'Screenshots of the migration execution logs'],
    acceptanceCriteria: ['Database schema defined purely via code', 'Includes up/down migration capabilities', 'Seed script generates dummy data'],
    difficulty: 3,
    expectedOutput: 'A maintainable backend leveraging modern Object-Relational Mapping strategies.',
    skillsExercised: ['ORM Implementation', 'Database Migrations', 'Data Seeding', 'TypeScript Interfaces'],
    suggestedTools: ['Prisma ORM', 'TypeORM', 'PostgreSQL'],
    presentationTips: 'Highlight the type-safety benefits of using an ORM by showing how IDE autocomplete works for your queries.',
  },

  // Stage 3 (Advanced)
  {
    pathSlug: 'backend-engineering',
    stageNumber: 3,
    title: 'Real-time Message Broker Integration',
    description: 'Build a background workers queue system using Node.js and Redis (BullMQ or RabbitMQ) to handle heavy tasks asynchronously.',
    deliverables: ['GitHub Repository link', 'Workers log configuration outputs'],
    acceptanceCriteria: ['Worker processes run independently from the main web server', 'Failsafe retries and queue log monitoring are implemented'],
    difficulty: 4,
    expectedOutput: 'A robust microservices system managing async task processing.',
    skillsExercised: ['Message Queues', 'Redis Caching', 'Background Workers', 'Asynchronous Architecture'],
    suggestedTools: ['Node.js', 'Redis', 'BullMQ', 'Docker'],
    presentationTips: 'Document how the system handles database locks and concurrent queries when worker counts scale up.',
  },
  {
    pathSlug: 'backend-engineering',
    stageNumber: 3,
    title: 'Production API Load Optimization & Caching',
    description: 'Implement Redis caching and database indexing optimizations in a slow API to handle high load traffic.',
    deliverables: ['GitHub Repository link', 'Autocannon/k6 load test comparison reports'],
    acceptanceCriteria: ['Lighthouse/k6 load response times drop by >50%', 'API handles at least 500 requests per second without errors'],
    difficulty: 5,
    expectedOutput: 'A high-performance backend API with optimized queries and Redis response caching.',
    skillsExercised: ['Database Optimizations', 'Redis Cache Keys', 'Load Testing Tools', 'Index Profiling'],
    suggestedTools: ['k6', 'Redis', 'PostgreSQL EXPLAIN', 'Node.js'],
    presentationTips: 'Provide k6 report graphics displaying latency charts and error rates under stress testing in the repository.',
  },
  {
    pathSlug: 'backend-engineering',
    stageNumber: 3,
    title: 'Build a WebSockets Chat API',
    description: 'Create a scalable real-time chat server supporting multiple rooms and private messages using WebSockets.',
    deliverables: ['GitHub Repository link', 'Architecture diagram detailing WebSocket connections'],
    acceptanceCriteria: ['Users can join specific rooms (channels)', 'Messages are broadcasted only to users within the room', 'Connection drop handling'],
    difficulty: 5,
    expectedOutput: 'A concurrent networking application demonstrating persistent connections rather than REST.',
    skillsExercised: ['WebSockets', 'Pub/Sub Architecture', 'Real-time Networking', 'Concurrency'],
    suggestedTools: ['Socket.io', 'Redis Pub/Sub (for scaling)'],
    presentationTips: 'Show how you would scale the chat server across multiple instances using Redis Pub/Sub adapter.',
  },
  {
    pathSlug: 'backend-engineering',
    stageNumber: 3,
    title: 'API Security Hardening & Rate Limiting',
    description: 'Audit and secure a vulnerable API by implementing rate limiting, CORS restrictions, helmet headers, and input sanitization.',
    deliverables: ['GitHub Repository link with patched code', 'Security audit document'],
    acceptanceCriteria: ['Rate limiter blocks IPs exceeding 100 requests/min', 'SQL injection attempts are sanitized', 'Secure HTTP headers configured'],
    difficulty: 5,
    expectedOutput: 'A production-hardened API fortified against common OWASP top 10 web vulnerabilities.',
    skillsExercised: ['API Security', 'Rate Limiting', 'Sanitization', 'CORS Policies'],
    suggestedTools: ['Express Rate Limit', 'Helmet.js', 'Joi Validation'],
    presentationTips: 'Provide curl commands in your readme that explicitly trigger the rate limiter to prove it works.',
  },

  // ════════════════════════════════════════════
  // 7. CYBERSECURITY
  // ════════════════════════════════════════════
  // Stage 1 (Beginner)
  {
    pathSlug: 'cybersecurity',
    stageNumber: 1,
    title: 'Linux Commands & Server Hardening Script',
    description: 'Create a bash script to perform basic security checks and server hardening steps on a Linux distribution.',
    deliverables: ['Hardening shell script file on GitHub', 'Server audit output log'],
    acceptanceCriteria: ['Script disables SSH root login, audits open ports, and configures a simple firewall (UFW)'],
    difficulty: 1,
    expectedOutput: 'A bash utility script performing server system audits and applying permissions.',
    skillsExercised: ['Linux Scripting', 'Server Hardening', 'Firewall Configurations', 'System Auditing'],
    suggestedTools: ['Ubuntu Server', 'Bash', 'UFW', 'SSH Security'],
    presentationTips: 'Structure your script with verbose console outputs and logs so users know exactly what actions are being run.',
  },
  {
    pathSlug: 'cybersecurity',
    stageNumber: 1,
    title: 'Network Port Auditing & Analysis',
    description: 'Perform a network sweep of a local target machine using Nmap, analyzing open ports and vulnerability vectors.',
    deliverables: ['Nmap audit report (PDF or Markdown)', 'Remediation guidelines document'],
    acceptanceCriteria: ['Sweeps targets and identifies running services and versions', 'Advises concrete patching steps for discovered open ports'],
    difficulty: 2,
    expectedOutput: 'A detailed port mapping security report specifying risk zones.',
    skillsExercised: ['Network Auditing', 'Nmap Syntaxes', 'Risk Assessment', 'Service Version Scan'],
    suggestedTools: ['Nmap', 'Kali Linux', 'Wireshark'],
    presentationTips: 'Write descriptions of the risk for each open port, linking back to official CVE references.',
  },
  {
    pathSlug: 'cybersecurity',
    stageNumber: 1,
    title: 'Setup a Secure Virtual Lab Environment',
    description: 'Install and configure a Type 2 hypervisor with an attacking machine (Kali Linux) and a vulnerable target (Metasploitable).',
    deliverables: ['Screenshot documentation of the lab setup', 'Network configuration showing host-only isolation'],
    acceptanceCriteria: ['Machines can ping each other but are isolated from the main internet', 'Kali Linux tools are successfully updated'],
    difficulty: 1,
    expectedOutput: 'A safe, isolated sandbox environment for practicing penetration testing.',
    skillsExercised: ['Virtualization', 'Network Isolation', 'Environment Setup'],
    suggestedTools: ['VirtualBox / VMware', 'Kali Linux', 'Metasploitable'],
    presentationTips: 'Clearly explain why you chose Host-Only networking versus Bridged networking for security reasons.',
  },
  {
    pathSlug: 'cybersecurity',
    stageNumber: 1,
    title: 'Wireshark Packet Analysis',
    description: 'Capture and analyze a PCAP file to extract cleartext passwords transmitted over HTTP or FTP.',
    deliverables: ['Annotated PCAP file screenshots', 'Summary report of the findings'],
    acceptanceCriteria: ['Successfully identifies the malicious packets', 'Extracts credentials or sensitive data from the capture'],
    difficulty: 2,
    expectedOutput: 'A packet analysis report demonstrating understanding of unencrypted protocols.',
    skillsExercised: ['Packet Sniffing', 'Wireshark Filters', 'Protocol Analysis (HTTP/FTP)'],
    suggestedTools: ['Wireshark', 'Sample PCAP files'],
    presentationTips: 'Highlight the specific Wireshark display filters you used (e.g., `http.request.method == "POST"`) to quickly locate the data.',
  },

  // Stage 2 (Intermediate)
  {
    pathSlug: 'cybersecurity',
    stageNumber: 2,
    title: 'Web Application Penetration Test',
    description: 'Perform a penetration test on an intentionally vulnerable web application, identifying OWASP Top 10 vulnerabilities.',
    deliverables: ['Security audit findings report (OWASP guidelines)', 'Proof-of-concept exploits'],
    acceptanceCriteria: ['Discovers and documents at least 3 vulnerabilities (e.g. SQLi, XSS, CSRF)', 'Provides remediation code snippets to patch issues'],
    difficulty: 2,
    expectedOutput: 'A web security report detailing vulnerabilities and patch codes.',
    skillsExercised: ['Web Security Audits', 'OWASP Standards', 'Exploit Proofs', 'Code Patching'],
    suggestedTools: ['OWASP ZAP', 'Burp Suite', 'DVWA'],
    presentationTips: 'Show side-by-side code diffs of the vulnerable code and the patched secure code version.',
  },
  {
    pathSlug: 'cybersecurity',
    stageNumber: 2,
    title: 'Secure Code Auditing & Static Review',
    description: 'Review and audit a repository code bundle for vulnerabilities using static code analysis tools (SAST) and manual review.',
    deliverables: ['SAST results output file', 'Manual audit summary detailing security gaps'],
    acceptanceCriteria: ['Identifies hardcoded API keys, SQL injections, and buffer overflows', 'Highlights dangerous dependency updates needed'],
    difficulty: 3,
    expectedOutput: 'A code health security report detailing vulnerability lines.',
    skillsExercised: ['Static Analysis', 'Manual Code Audits', 'Dependency Scans', 'SAST Reporting'],
    suggestedTools: ['SonarQube', 'Snyk', 'GitHub Dependabot'],
    presentationTips: 'Categorize finding alerts by severity tiers (High, Medium, Low) to keep remediation plans structured.',
  },
  {
    pathSlug: 'cybersecurity',
    stageNumber: 2,
    title: 'Phishing Simulation & Awareness Campaign',
    description: 'Design and deploy a safe, simulated phishing campaign for a small group (with permission) using GoPhish to track click rates.',
    deliverables: ['GoPhish campaign report', 'Awareness training email template'],
    acceptanceCriteria: ['Simulated phishing email bypasses basic spam filters legitimately', 'Tracks open rates, click rates, and credential submission rates safely'],
    difficulty: 3,
    expectedOutput: 'A social engineering campaign analysis showing the human risk factor in security.',
    skillsExercised: ['Social Engineering', 'GoPhish Framework', 'Email Spoofing Concepts', 'Security Awareness'],
    suggestedTools: ['GoPhish', 'Mailgun (SMTP)'],
    presentationTips: 'Keep the focus on education, not trickery—explain how the findings justify investing in employee training.',
  },
  {
    pathSlug: 'cybersecurity',
    stageNumber: 2,
    title: 'Exploiting Active Directory (Lab Simulation)',
    description: 'Run privilege escalation attacks within a lab Active Directory environment to achieve Domain Admin access.',
    deliverables: ['Penetration test timeline document', 'Screenshots of successful ticket extraction (e.g., Mimikatz)'],
    acceptanceCriteria: ['Demonstrates lateral movement techniques', 'Identifies misconfigured AD permissions (e.g., BloodHound)'],
    difficulty: 3,
    expectedOutput: 'A structured exploitation path report of an enterprise Windows environment.',
    skillsExercised: ['Active Directory Security', 'Lateral Movement', 'Privilege Escalation', 'Kerberos Exploits'],
    suggestedTools: ['BloodHound', 'Mimikatz', 'Impacket'],
    presentationTips: 'Present the attack path visually using the graphs generated by BloodHound to show the chain of vulnerabilities.',
  },

  // Stage 3 (Advanced)
  {
    pathSlug: 'cybersecurity',
    stageNumber: 3,
    title: 'IAM Policy & Infrastructure Hardening',
    description: 'Formulate a secure Identity and Access Management (IAM) role set for a cloud workspace, enforcing Least Privilege access rules.',
    deliverables: ['JSON IAM policy documents', 'IAM roles organizational chart'],
    acceptanceCriteria: ['Policies restrict access to only required services', 'Includes audit configurations for policy change monitoring'],
    difficulty: 4,
    expectedOutput: 'JSON configurations mapping groups, users, and actions.',
    skillsExercised: ['IAM Configuration', 'Least Privilege Access', 'JSON Policy Formats', 'Cloud Security'],
    suggestedTools: ['AWS IAM', 'Azure Active Directory'],
    presentationTips: 'Write a walkthrough explaining how your IAM design prevents privilege escalation loops.',
  },
  {
    pathSlug: 'cybersecurity',
    stageNumber: 3,
    title: 'Incident Response & Log Analysis Report',
    description: 'Analyze an access log file from a compromised web server, reconstructing the attacker journey and timeline.',
    deliverables: ['Timeline of attack analysis deck (PDF)', 'Remediation plan for future prevention'],
    acceptanceCriteria: ['Report identifies attacker IP, entry vector, commands run, and databases breached'],
    difficulty: 5,
    expectedOutput: 'A detailed forensic analysis document detailing the attack vector.',
    skillsExercised: ['Forensics Log Scan', 'Timeline Reconstruction', 'Attacker Profiling', 'Incident Mitigation'],
    suggestedTools: ['Wireshark', 'Splunk', 'Linux Log Files'],
    presentationTips: 'Outline your findings starting with an Executive Summary (1 page) explaining the business impact of the incident.',
  },
  {
    pathSlug: 'cybersecurity',
    stageNumber: 3,
    title: 'Reverse Engineering Malware Sample',
    description: 'Use static and dynamic analysis tools to dissect a known safe malware sample (e.g., WannaCry in a secure lab) to determine its indicators of compromise (IoCs).',
    deliverables: ['Malware analysis report', 'List of Extracted IoCs (Hashes, IPs, Domains)'],
    acceptanceCriteria: ['Safely detonates malware in an isolated sandbox', 'Identifies exactly how the malware achieves persistence in the OS'],
    difficulty: 5,
    expectedOutput: 'A highly technical forensic breakdown of malicious software behavior.',
    skillsExercised: ['Malware Analysis', 'Reverse Engineering', 'Dynamic Detonation', 'IoC Extraction'],
    suggestedTools: ['Ghidra', 'Cuckoo Sandbox', 'Process Monitor'],
    presentationTips: 'Document the exact MD5/SHA256 hashes of the file so that threat intelligence teams could feed it into their firewalls.',
  },
  {
    pathSlug: 'cybersecurity',
    stageNumber: 3,
    title: 'Automate Security Scans in CI/CD Pipeline',
    description: 'Integrate dynamic (DAST) and static (SAST) security testing tools into a GitHub Actions CI/CD pipeline.',
    deliverables: ['GitHub Actions YAML file', 'Pipeline execution screenshots showing security gates blocking vulnerable code'],
    acceptanceCriteria: ['Pipeline fails the build if critical vulnerabilities are detected in the code or Docker image'],
    difficulty: 5,
    expectedOutput: 'A DevSecOps pipeline that automates security compliance during the software build phase.',
    skillsExercised: ['DevSecOps', 'CI/CD Pipelines', 'Automated DAST/SAST', 'Container Scanning'],
    suggestedTools: ['GitHub Actions', 'Trivy', 'SonarQube'],
    presentationTips: 'Explain the concept of "Shifting Left" in your README to demonstrate your understanding of modern DevSecOps philosophies.',
  },

  // ════════════════════════════════════════════
  // 8. CLOUD ENGINEERING
  // ════════════════════════════════════════════
  // Stage 1 (Beginner)
  {
    pathSlug: 'cloud-engineering',
    stageNumber: 1,
    title: 'AWS Static Website Hosting',
    description: 'Deploy a static HTML site to Amazon S3, configuring it for public web access and linking it to CloudFront CDN.',
    deliverables: ['Live website URL', 'Cloud architecture setup notes'],
    acceptanceCriteria: ['Site serves assets correctly over HTTPS using CloudFront', 'Bucket access is blocked except from CloudFront OAC'],
    difficulty: 1,
    expectedOutput: 'A live web domain serving static pages through CloudFront.',
    skillsExercised: ['Amazon S3 Hosting', 'CloudFront Distribution', 'HTTPS Configuration', 'Access Policies'],
    suggestedTools: ['AWS S3', 'AWS CloudFront', 'Route 53'],
    presentationTips: 'Provide a screenshot of the HTTPS padlock and explain how CDN cache caching improves server loads.',
  },
  {
    pathSlug: 'cloud-engineering',
    stageNumber: 1,
    title: 'Terraform Local Server Deploy',
    description: 'Write Terraform scripts to create a local virtual machine or cloud instance automatically.',
    deliverables: ['Terraform configuration script files (.tf)', 'Terraform init and apply outputs logs'],
    acceptanceCriteria: ['Terraform scripts contain variables, provider setup, and outputs', 'Running terraform apply creates resources correctly'],
    difficulty: 2,
    expectedOutput: 'Automated Terraform code scripts deploying virtual nodes.',
    skillsExercised: ['Infrastructure as Code (IaC)', 'Terraform Provider Settings', 'Variable Scoping', 'State Management'],
    suggestedTools: ['Terraform CLI', 'VirtualBox', 'AWS Provider'],
    presentationTips: 'Write descriptions of variables in your Terraform scripts to document what properties they take.',
  },
  {
    pathSlug: 'cloud-engineering',
    stageNumber: 1,
    title: 'Configure a VPC with Public and Private Subnets',
    description: 'Design and deploy a Virtual Private Cloud (VPC) in AWS containing both public subnets (for web servers) and private subnets (for databases).',
    deliverables: ['Architecture diagram of the VPC', 'CloudFormation or Terraform scripts'],
    acceptanceCriteria: ['Private subnet has no direct internet access but can route outbound via a NAT Gateway', 'Public subnet has an Internet Gateway'],
    difficulty: 2,
    expectedOutput: 'A secure, logically isolated network foundation ready for enterprise applications.',
    skillsExercised: ['VPC Architecture', 'Subnetting / CIDR', 'NAT Gateways', 'Route Tables'],
    suggestedTools: ['AWS VPC', 'draw.io', 'Terraform'],
    presentationTips: 'Clearly map out your CIDR blocks (e.g. 10.0.0.0/16) and explain why you sized the subnets the way you did.',
  },
  {
    pathSlug: 'cloud-engineering',
    stageNumber: 1,
    title: 'Set up Cloud Monitoring & Billing Alerts',
    description: 'Configure CloudWatch dashboards to monitor CPU usage of an instance and set up SNS billing alerts if costs exceed $10.',
    deliverables: ['Screenshots of the CloudWatch dashboard', 'Evidence of the SNS email alert configuration'],
    acceptanceCriteria: ['Dashboard displays metrics for at least 2 distinct AWS services', 'Billing alert triggers an email notification'],
    difficulty: 1,
    expectedOutput: 'A proactive monitoring system ensuring infrastructure health and cost control.',
    skillsExercised: ['Cloud Monitoring', 'Alerting (SNS)', 'Cost Management (FinOps)', 'Dashboard Creation'],
    suggestedTools: ['AWS CloudWatch', 'AWS SNS', 'AWS Budgets'],
    presentationTips: 'Emphasize cost control—FinOps is a critical skill for junior cloud engineers to prove they won\'t waste company money.',
  },

  // Stage 2 (Intermediate)
  {
    pathSlug: 'cloud-engineering',
    stageNumber: 2,
    title: 'Multi-Stage CI/CD Deployment Pipeline',
    description: 'Set up a CI/CD pipeline (GitHub Actions or GitLab CI) that builds, tests, and deploys a web application on commits.',
    deliverables: ['Pipeline configuration files (.yml)', 'Successful build pipeline runner screenshots'],
    acceptanceCriteria: ['Pipeline triggers automatically on code push', 'Fails building if test runners report errors'],
    difficulty: 2,
    expectedOutput: 'A fully functional automated build pipeline executing checks.',
    skillsExercised: ['CI/CD Orchestration', 'GitHub Actions Syntax', 'Automated Testing', 'Continuous Deployment'],
    suggestedTools: ['GitHub Actions', 'Docker', 'Vercel CLI'],
    presentationTips: 'Utilize caching for node_modules in your pipelines to reduce build runtimes.',
  },
  {
    pathSlug: 'cloud-engineering',
    stageNumber: 2,
    title: 'Scale Web Server Cluster behind Load Balancer',
    description: 'Deploy an application cluster behind an ALB (Application Load Balancer) with Auto-Scaling groups triggered by CPU limits.',
    deliverables: ['Infrastructure setup script (Terraform or CloudFormation)', 'Load test monitoring graphics'],
    acceptanceCriteria: ['ALB balances connections between at least 2 nodes', 'Auto-scaling group creates new servers during load tests'],
    difficulty: 3,
    expectedOutput: 'A self-healing scaled server deployment topology.',
    skillsExercised: ['Load Balancing (ALB)', 'Auto-Scaling Groups', 'CPU Trigger Configuration', 'High Availability'],
    suggestedTools: ['AWS EC2', 'AWS ALB', 'Terraform', 'ApacheBench'],
    presentationTips: 'Explain the cooldown period and metrics you chose for auto-scaling triggers in your documentation.',
  },
  {
    pathSlug: 'cloud-engineering',
    stageNumber: 2,
    title: 'Automate Database Backups using Lambda',
    description: 'Write an AWS Lambda function in Python that triggers via EventBridge daily to take snapshots of an RDS database instance.',
    deliverables: ['Lambda function Python code', 'EventBridge cron rule setup screenshots'],
    acceptanceCriteria: ['Lambda successfully calls the RDS snapshot API', 'IAM role for the Lambda follows least privilege'],
    difficulty: 3,
    expectedOutput: 'An automated serverless script ensuring data disaster recovery compliance.',
    skillsExercised: ['Serverless Compute (Lambda)', 'Cron Scheduling (EventBridge)', 'Disaster Recovery Automation', 'Boto3 SDK'],
    suggestedTools: ['AWS Lambda', 'Python Boto3', 'AWS RDS'],
    presentationTips: 'Implement a retention policy in your script to delete snapshots older than 30 days to save storage costs.',
  },
  {
    pathSlug: 'cloud-engineering',
    stageNumber: 2,
    title: 'Deploy a Dockerized App to ECS Fargate',
    description: 'Take a Docker container image stored in ECR and deploy it to a serverless AWS Elastic Container Service (Fargate) cluster.',
    deliverables: ['Terraform or ECS Task Definition JSON', 'Live URL of the deployed container application'],
    acceptanceCriteria: ['Container runs in Fargate (no EC2 instances managed)', 'Container exposes a web port successfully mapped to an ALB'],
    difficulty: 3,
    expectedOutput: 'A production-grade container deployment utilizing serverless compute resources.',
    skillsExercised: ['Container Orchestration (ECS)', 'Serverless Containers (Fargate)', 'Container Registries (ECR)', 'Networking'],
    suggestedTools: ['AWS ECS Fargate', 'Docker', 'AWS ECR'],
    presentationTips: 'Detail the exact CPU and memory allocations you chose for your Fargate tasks and why.',
  },

  // Stage 3 (Advanced)
  {
    pathSlug: 'cloud-engineering',
    stageNumber: 3,
    title: 'Automated Kubernetes Deployment Config',
    description: 'Deploy a multi-tier application using Kubernetes configurations, detailing pods, services, and volume mounts.',
    deliverables: ['Kubernetes manifest YAML files', 'Running kubectl status logs'],
    acceptanceCriteria: ['Pods handle database connectivity with secret configs', 'App includes ingress or service definitions for outer traffic'],
    difficulty: 4,
    expectedOutput: 'Kubernetes configuration YAML files running clustered components.',
    skillsExercised: ['Kubernetes Orchestration', 'YAML Configurations', 'Service Definition', 'Persistent Volume Mounts'],
    suggestedTools: ['Minikube', 'kubectl CLI', 'Docker Hub'],
    presentationTips: 'Highlight the database migration runner container inside your pods to show end-to-end setup planning.',
  },
  {
    pathSlug: 'cloud-engineering',
    stageNumber: 3,
    title: 'Serverless API & Database Architecture',
    description: 'Deploy a serverless backend system using AWS Lambda and DynamoDB, structured via Terraform.',
    deliverables: ['Terraform configs for serverless setup', 'End-to-end API test screenshots'],
    acceptanceCriteria: ['API endpoints trigger Lambda executions', 'Database queries write to DynamoDB tables correctly'],
    difficulty: 5,
    expectedOutput: 'A fully serverless infrastructure topology with zero running server costs when idle.',
    skillsExercised: ['AWS Lambda Settings', 'DynamoDB Design', 'API Gateway Integrations', 'Serverless Terraform'],
    suggestedTools: ['AWS API Gateway', 'Lambda', 'DynamoDB', 'Terraform'],
    presentationTips: 'Outline cold start speed metrics and DynamoDB partition key strategies inside your design doc.',
  },
  {
    pathSlug: 'cloud-engineering',
    stageNumber: 3,
    title: 'Design a Multi-Region Disaster Recovery Plan',
    description: 'Architect a cross-region failover strategy (e.g., us-east-1 to eu-west-1) utilizing Route 53 health checks and database read replicas.',
    deliverables: ['Architecture diagrams detailing the failover flow', 'Disaster Recovery Runbook document'],
    acceptanceCriteria: ['Defines RTO (Recovery Time Objective) and RPO (Recovery Point Objective)', 'Architecture supports automatic failover via DNS routing'],
    difficulty: 5,
    expectedOutput: 'An enterprise-level disaster recovery design document ensuring high availability across continents.',
    skillsExercised: ['Disaster Recovery (DR)', 'Multi-Region Architecture', 'Route 53 Failover Routing', 'Database Replication'],
    suggestedTools: ['draw.io', 'AWS Route 53', 'AWS RDS Global'],
    presentationTips: 'Clearly distinguish between Active-Active and Active-Passive DR strategies and justify your choice based on cost vs. availability.',
  },
  {
    pathSlug: 'cloud-engineering',
    stageNumber: 3,
    title: 'Write a Custom Terraform Provider',
    description: 'Develop a custom Terraform provider in Go that interfaces with a third-party API (like a mock SaaS service) to manage its resources via IaC.',
    deliverables: ['GitHub repository containing the Go code for the provider', 'Example `.tf` file utilizing the custom provider'],
    acceptanceCriteria: ['Provider supports full CRUD operations (Create, Read, Update, Delete)', 'Passes Terraform acceptance tests (`acctest`)'],
    difficulty: 5,
    expectedOutput: 'A highly advanced infrastructure tooling project demonstrating deep understanding of the Terraform plugin SDK.',
    skillsExercised: ['Go Programming', 'Terraform Plugin SDK', 'API Integration', 'Advanced IaC'],
    suggestedTools: ['Go', 'Terraform CLI', 'SaaS API'],
    presentationTips: 'Explain the state management logic—how your provider detects drift between the API state and the local Terraform state.',
  },

  // ════════════════════════════════════════════
  // 9. DIGITAL MARKETING
  // ════════════════════════════════════════════
  // Stage 1 (Beginner)
  {
    pathSlug: 'digital-marketing',
    stageNumber: 1,
    title: 'Competitor Digital Presence Audit',
    description: 'Analyze a brand\'s digital presence, comparing it with 2 competitors on SEO, search ads, and social media.',
    deliverables: ['Digital audit report presentation slide deck (PDF link)'],
    acceptanceCriteria: ['Compares 3 channels (SEO, Ads, Social)', 'Identifies 3 competitor gaps and outlines opportunities for growth'],
    difficulty: 1,
    expectedOutput: 'A comprehensive brand performance review showing strategic growth potential.',
    skillsExercised: ['Competitive Research', 'SEO Basics', 'Social Media Auditing', 'Strategic Growth'],
    suggestedTools: ['SimilarWeb', 'SEMrush (Free)', 'Canva'],
    presentationTips: 'Utilize screenshots of competitor ads (from Facebook Ad Library) to visually back up your claims.',
  },
  {
    pathSlug: 'digital-marketing',
    stageNumber: 1,
    title: 'Social Media Organic Content Calendar',
    description: 'Build a 30-day content calendar for a specific brand across Instagram and LinkedIn, writing copy and specifying assets.',
    deliverables: ['Content Calendar Spreadsheet', '3 sample designed assets (Canva/Figma)'],
    acceptanceCriteria: ['Varies content themes (Educational, Promotional, Entertaining)', 'Includes optimized hashtags and posting times'],
    difficulty: 1,
    expectedOutput: 'A structured, actionable publishing schedule for a social media manager.',
    skillsExercised: ['Social Media Strategy', 'Copywriting', 'Content Scheduling', 'Asset Curation'],
    suggestedTools: ['Google Sheets', 'Canva', 'Later (optional)'],
    presentationTips: 'Format the spreadsheet clearly so the columns for "Image Link", "Copy", and "Publish Date" are easily readable by clients.',
  },
  {
    pathSlug: 'digital-marketing',
    stageNumber: 1,
    title: 'On-Page SEO Optimization',
    description: 'Optimize a sample 1,000-word blog post for a specific target keyword, adjusting headers, meta descriptions, and image alt text.',
    deliverables: ['Word document containing the optimized copy and HTML tags', 'Keyword density report'],
    acceptanceCriteria: ['Target keyword is used naturally in H1, H2, and meta description', 'Readability score is high'],
    difficulty: 2,
    expectedOutput: 'A perfectly formatted, search-engine-ready piece of content.',
    skillsExercised: ['On-Page SEO', 'Keyword Placement', 'Meta Tag Optimization', 'Readability'],
    suggestedTools: ['Yoast SEO', 'Hemingway App'],
    presentationTips: 'Highlight the exact changes you made to the document so reviewers can easily see the "before and after".',
  },
  {
    pathSlug: 'digital-marketing',
    stageNumber: 1,
    title: 'Define Customer Buyer Personas',
    description: 'Create 2 detailed buyer personas for a B2B or B2C product, detailing their demographics, pain points, and preferred channels.',
    deliverables: ['Visual Persona Slide Deck (1 slide per persona)'],
    acceptanceCriteria: ['Includes demographic data, job titles, pain points, and objections to buying', 'Specifies which marketing channels reach them best'],
    difficulty: 1,
    expectedOutput: 'Strategic audience profiles that inform ad targeting and copywriting.',
    skillsExercised: ['Audience Research', 'Persona Mapping', 'Market Segmentation', 'Empathy Mapping'],
    suggestedTools: ['Make My Persona (HubSpot)', 'Canva'],
    presentationTips: 'Give the personas a realistic name and photo to make them feel tangible during strategic discussions.',
  },

  // Stage 2 (Intermediate)
  {
    pathSlug: 'digital-marketing',
    stageNumber: 2,
    title: 'Google Search Ads Campaign Build',
    description: 'Design a Google Search campaign structure, defining ad groups, keyword match types, and writing ad copy with extensions.',
    deliverables: ['Campaign structure spreadsheet', 'Ad copy preview documents'],
    acceptanceCriteria: ['Uses Exact, Phrase, and Broad match types strategically', 'Includes negative keyword lists to prevent wasted spend'],
    difficulty: 2,
    expectedOutput: 'A structured Google Ads account blueprint ready for upload into the Ads Editor.',
    skillsExercised: ['PPC Strategy', 'Keyword Match Types', 'Ad Copywriting', 'Negative Keyword Mapping'],
    suggestedTools: ['Google Keyword Planner', 'Google Ads Editor', 'Excel'],
    presentationTips: 'Calculate an estimated CPC (Cost Per Click) and project how much traffic a $1,000 budget would acquire.',
  },
  {
    pathSlug: 'digital-marketing',
    stageNumber: 2,
    title: 'Web Analytics & Conversion Tracking Setup',
    description: 'Document a tracking plan utilizing Google Tag Manager to track button clicks and form submissions in Google Analytics 4 (GA4).',
    deliverables: ['Tracking specification document detailing events and triggers'],
    acceptanceCriteria: ['Identifies at least 5 key events (e.g. `generate_lead`, `add_to_cart`)', 'Maps GTM triggers and variables required for each event'],
    difficulty: 3,
    expectedOutput: 'A technical analytics implementation guide for web developers to follow.',
    skillsExercised: ['Google Tag Manager (GTM)', 'Event Tracking (GA4)', 'Conversion Goals', 'Analytics Architecture'],
    suggestedTools: ['Google Analytics 4', 'Google Tag Manager', 'Notion'],
    presentationTips: 'Explain the difference between a pageview and a custom event to show deep understanding of GA4\'s event-based model.',
  },
  {
    pathSlug: 'digital-marketing',
    stageNumber: 2,
    title: 'Email Marketing Automation Flow',
    description: 'Design and write a 5-part automated email welcome sequence for new subscribers or SaaS trial users.',
    deliverables: ['Email copy document', 'Flowchart diagram of the automation logic'],
    acceptanceCriteria: ['Includes dynamic tags (e.g., First Name)', 'Flowchart utilizes conditional splits (e.g., Did they open Email 1?)'],
    difficulty: 3,
    expectedOutput: 'A strategic email drip campaign focused on lead nurturing and activation.',
    skillsExercised: ['Email Automation Logic', 'Drip Campaigns', 'Copywriting for Conversions', 'Lead Nurturing'],
    suggestedTools: ['Mailchimp', 'Klaviyo', 'Whimsical'],
    presentationTips: 'State the specific goal of each email clearly at the top (e.g., Email 2 Goal: Get user to complete profile setup).',
  },
  {
    pathSlug: 'digital-marketing',
    stageNumber: 2,
    title: 'Paid Social (Meta) Campaign Strategy',
    description: 'Build a full-funnel Facebook/Instagram ad strategy, detailing Prospecting (Lookalike audiences) and Retargeting campaigns.',
    deliverables: ['Strategy deck detailing audiences, budgets, and creative formats'],
    acceptanceCriteria: ['Clearly separates TOFU (Prospecting) and BOFU (Retargeting) audiences', 'Proposes different ad creatives for each stage'],
    difficulty: 3,
    expectedOutput: 'A comprehensive paid social media media plan capable of driving profitable customer acquisition.',
    skillsExercised: ['Media Planning', 'Audience Targeting (Lookalikes/Retargeting)', 'Full-Funnel Strategy', 'Meta Ads Manager'],
    suggestedTools: ['Facebook Ads Library', 'Google Slides'],
    presentationTips: 'Assign a budget split percentage (e.g., 70% Prospecting / 30% Retargeting) to show financial management skills.',
  },

  // Stage 3 (Advanced)
  {
    pathSlug: 'digital-marketing',
    stageNumber: 3,
    title: 'End-to-End Campaign ROI Analysis',
    description: 'Analyze an export of marketing campaign data (spend, clicks, conversions) to calculate CAC, ROAS, and LTV, presenting optimization steps.',
    deliverables: ['Excel data analysis workbook', 'Executive summary presentation deck'],
    acceptanceCriteria: ['Accurately calculates Customer Acquisition Cost (CAC) and Return on Ad Spend (ROAS)', 'Reallocates budget based on performance data'],
    difficulty: 4,
    expectedOutput: 'A financial marketing report connecting advertising spend directly to business revenue.',
    skillsExercised: ['Marketing Analytics', 'ROAS / CAC Calculation', 'Budget Reallocation', 'Executive Reporting'],
    suggestedTools: ['Excel Pivot Tables', 'Google Data Studio / Looker'],
    presentationTips: 'Visualize the diminishing returns of scaling campaigns—explain why doubling the budget doesn\'t always double the sales.',
  },
  {
    pathSlug: 'digital-marketing',
    stageNumber: 3,
    title: 'Technical SEO Site Audit',
    description: 'Perform a deep technical SEO crawl of a website to identify indexation issues, canonical errors, and core web vitals drops.',
    deliverables: ['Technical SEO Audit Report', 'Prioritized fix list for engineering'],
    acceptanceCriteria: ['Analyzes robots.txt, XML sitemaps, and 404 error logs', 'Grades site speed metrics (LCP, FID, CLS)'],
    difficulty: 5,
    expectedOutput: 'An advanced technical diagnostic report improving search engine crawlability.',
    skillsExercised: ['Technical SEO', 'Crawl Analysis', 'Core Web Vitals', 'Indexation Strategy'],
    suggestedTools: ['Screaming Frog SEO Spider', 'Google Search Console', 'PageSpeed Insights'],
    presentationTips: 'Prioritize the engineering tickets heavily; don\'t give developers 50 tasks, give them the 5 that move the needle.',
  },
  {
    pathSlug: 'digital-marketing',
    stageNumber: 3,
    title: 'Conversion Rate Optimization (A/B Test Design)',
    description: 'Design a comprehensive CRO experiment for an e-commerce checkout page, detailing the hypothesis, mockups, and significance targets.',
    deliverables: ['A/B test proposal document', 'Figma mockups of the Control vs. Variant'],
    acceptanceCriteria: ['Hypothesis is rooted in psychological principles or heuristic data', 'Specifies the Minimum Detectable Effect (MDE)'],
    difficulty: 5,
    expectedOutput: 'A scientific testing proposal aimed at increasing conversion rates and revenue.',
    skillsExercised: ['Conversion Rate Optimization (CRO)', 'A/B Test Design', 'Statistical Significance', 'UX/UI Hypotheses'],
    suggestedTools: ['VWO Calculator', 'Figma', 'Google Optimize (concept)'],
    presentationTips: 'Explain the risk of "peeking" at test results too early and why statistical significance requires patience.',
  },
  {
    pathSlug: 'digital-marketing',
    stageNumber: 3,
    title: 'Develop a Multi-Channel Attribution Strategy',
    description: 'Design an attribution model (e.g., Data-Driven, Position-Based) for a brand spending across Google Ads, Meta, and Organic Search to solve tracking overlap.',
    deliverables: ['Attribution Strategy Document (PDF)'],
    acceptanceCriteria: ['Explains the flaws of Last-Click attribution', 'Proposes how to merge GA4 data with CRM data to track actual sales, not just leads'],
    difficulty: 5,
    expectedOutput: 'A high-level data strategy solving one of marketing\'s hardest problems: proving ROI across multiple touches.',
    skillsExercised: ['Marketing Attribution Models', 'Cross-Channel Tracking', 'Data Strategy', 'CRM Integrations'],
    suggestedTools: ['Google Analytics 4', 'HubSpot/Salesforce mapping'],
    presentationTips: 'Address the impact of iOS 14+ tracking restrictions (ITP) and how your model relies on first-party data.',
  },

  // ════════════════════════════════════════════
  // 10. MACHINE LEARNING ENGINEERING
  // ════════════════════════════════════════════
  // Stage 1 (Beginner)
  {
    pathSlug: 'machine-learning-engineering',
    stageNumber: 1,
    title: 'Linear Regression Modeling Basics',
    description: 'Train a basic linear regression model on a dataset (like housing prices) using scikit-learn, optimizing for error rates.',
    deliverables: ['Jupyter Notebook file link', 'Model evaluation report'],
    acceptanceCriteria: ['Preprocesses data correctly (handles missing values, scaling)', 'Evaluates model using R-squared and Mean Absolute Error (MAE)'],
    difficulty: 1,
    expectedOutput: 'A clean notebook showing foundational ML principles of training and testing data splits.',
    skillsExercised: ['Linear Regression', 'scikit-learn', 'Train/Test Splits', 'Error Evaluation'],
    suggestedTools: ['Python', 'scikit-learn', 'Jupyter', 'pandas'],
    presentationTips: 'Print the coefficients of your regression model and explain which feature had the largest impact on the prediction.',
  },
  {
    pathSlug: 'machine-learning-engineering',
    stageNumber: 1,
    title: 'Classification Model Evaluation',
    description: 'Build a classification model (e.g., Logistic Regression or Random Forest) to predict churn, generating a confusion matrix.',
    deliverables: ['Jupyter Notebook file link', 'Confusion Matrix and classification report plots'],
    acceptanceCriteria: ['Evaluates Precision, Recall, and F1-Score', 'Explains the trade-off between False Positives and False Negatives'],
    difficulty: 2,
    expectedOutput: 'A classification notebook demonstrating understanding of evaluation metrics beyond just "Accuracy".',
    skillsExercised: ['Classification Algorithms', 'Confusion Matrix Analysis', 'Precision vs Recall', 'scikit-learn'],
    suggestedTools: ['Python', 'scikit-learn', 'Seaborn (for plotting)'],
    presentationTips: 'Explain why Accuracy is a misleading metric if the dataset is highly imbalanced (e.g., 99% of users don\'t churn).',
  },
  {
    pathSlug: 'machine-learning-engineering',
    stageNumber: 1,
    title: 'Feature Engineering & Data Preprocessing',
    description: 'Take a raw dataset and apply advanced feature engineering techniques: One-Hot Encoding, Min-Max Scaling, and creating polynomial features.',
    deliverables: ['Jupyter Notebook detailing the transformations'],
    acceptanceCriteria: ['Categorical variables are encoded correctly without dummy variable traps', 'Continuous variables are scaled uniformly'],
    difficulty: 1,
    expectedOutput: 'A transformed dataset ready for ingestion by sensitive algorithms like SVMs or Neural Networks.',
    skillsExercised: ['Feature Engineering', 'Data Scaling', 'Categorical Encoding', 'Dimensionality Reduction basics'],
    suggestedTools: ['Python', 'scikit-learn preprocessing'],
    presentationTips: 'Show the distribution histograms of a variable before and after scaling to visually prove the transformation.',
  },
  {
    pathSlug: 'machine-learning-engineering',
    stageNumber: 1,
    title: 'K-Means Clustering Analysis',
    description: 'Apply K-Means clustering to an unlabeled dataset (unsupervised learning) to discover natural groupings.',
    deliverables: ['Jupyter Notebook with scatter plots showing the clusters'],
    acceptanceCriteria: ['Uses the Elbow Method or Silhouette Score to determine the optimal number of clusters (K)', 'Visualizes clusters in 2D using PCA if needed'],
    difficulty: 2,
    expectedOutput: 'An unsupervised learning report discovering hidden patterns in raw data.',
    skillsExercised: ['Unsupervised Learning', 'K-Means Clustering', 'Elbow Method', 'Principal Component Analysis (PCA)'],
    suggestedTools: ['Python', 'scikit-learn', 'matplotlib'],
    presentationTips: 'Interpret the clusters—what real-world characteristics define "Cluster 1" versus "Cluster 2"?',
  },

  // Stage 2 (Intermediate)
  {
    pathSlug: 'machine-learning-engineering',
    stageNumber: 2,
    title: 'Deep Learning Image Classifier (CNN)',
    description: 'Build a Convolutional Neural Network (CNN) using PyTorch or TensorFlow to classify images (e.g., MNIST or CIFAR-10).',
    deliverables: ['GitHub repository containing model training scripts', 'Graph of training vs validation loss'],
    acceptanceCriteria: ['Implements multiple convolutional and pooling layers', 'Applies dropout to prevent overfitting on the training data'],
    difficulty: 3,
    expectedOutput: 'A functioning neural network capable of recognizing patterns in image matrices.',
    skillsExercised: ['Deep Learning', 'Convolutional Neural Networks (CNNs)', 'PyTorch / TensorFlow', 'Overfitting Prevention'],
    suggestedTools: ['PyTorch', 'TensorFlow/Keras', 'Google Colab'],
    presentationTips: 'Plot the training loss against the validation loss over epochs to visually demonstrate that the model is learning, not memorizing.',
  },
  {
    pathSlug: 'machine-learning-engineering',
    stageNumber: 2,
    title: 'Natural Language Processing (NLP) Sentiment Analysis',
    description: 'Train an NLP model to classify text reviews as positive or negative using TF-IDF or word embeddings (Word2Vec).',
    deliverables: ['Jupyter Notebook with text preprocessing and model training'],
    acceptanceCriteria: ['Implements text cleaning (stop words, stemming/lemmatization)', 'Achieves an F1 score > 0.80 on validation data'],
    difficulty: 3,
    expectedOutput: 'A text-based classifier interpreting human language sentiment.',
    skillsExercised: ['Natural Language Processing (NLP)', 'Text Vectorization', 'Tokenization', 'Classification Models'],
    suggestedTools: ['NLTK', 'spaCy', 'scikit-learn'],
    presentationTips: 'Output the top 10 words with the highest TF-IDF weights for positive versus negative reviews.',
  },
  {
    pathSlug: 'machine-learning-engineering',
    stageNumber: 2,
    title: 'Hyperparameter Tuning & Cross Validation',
    description: 'Take an existing complex model (like XGBoost or Random Forest) and optimize its performance using Grid Search or Random Search CV.',
    deliverables: ['Jupyter Notebook showing the tuning process and performance gains'],
    acceptanceCriteria: ['Implements K-Fold Cross Validation to ensure robustness', 'Compares baseline model performance against the tuned model'],
    difficulty: 3,
    expectedOutput: 'A highly optimized model demonstrating rigorous scientific tuning processes.',
    skillsExercised: ['Hyperparameter Optimization', 'K-Fold Cross Validation', 'XGBoost', 'GridSearchCV'],
    suggestedTools: ['scikit-learn GridSearchCV', 'XGBoost', 'Hyperopt'],
    presentationTips: 'Log the time it takes to run the grid search, explaining the computational trade-off of searching too many parameters.',
  },
  {
    pathSlug: 'machine-learning-engineering',
    stageNumber: 2,
    title: 'Deploy ML Model as a REST API',
    description: 'Serialize a trained scikit-learn model and wrap it in a Python web framework (FastAPI or Flask) to serve predictions via HTTP.',
    deliverables: ['GitHub repository with the API code', 'Postman screenshot showing a successful prediction request'],
    acceptanceCriteria: ['API accepts JSON payloads matching the feature schema', 'Returns a predicted class and confidence probability'],
    difficulty: 4,
    expectedOutput: 'A production-ready microservice serving machine learning inferences.',
    skillsExercised: ['Model Serialization', 'API Development (FastAPI)', 'Inference Serving', 'JSON Payloads'],
    suggestedTools: ['FastAPI', 'Docker', 'Uvicorn', 'Pydantic'],
    presentationTips: 'Include documentation on how the API manages request batching and prevents memory leaks during high traffic.',
  },

  // Stage 3 (Advanced)
  {
    pathSlug: 'machine-learning-engineering',
    stageNumber: 3,
    title: 'Automated MLOps Pipeline & Monitoring',
    description: 'Build an automated machine learning pipeline (Prefect or Kubeflow) that registers models in a registry (MLflow) and monitors drift.',
    deliverables: ['MLOps pipeline code repository', 'Drift monitoring logs output screenshots'],
    acceptanceCriteria: ['Pipeline executes automated data extraction, model training, and version registering', 'Tracks feature drift metrics'],
    difficulty: 5,
    expectedOutput: 'A production pipeline that automatically retrains and monitors models.',
    skillsExercised: ['MLOps Engineering', 'Model Registries (MLflow)', 'Data Drift Trackers', 'Pipeline Orchestration'],
    suggestedTools: ['MLflow', 'Prefect', 'Evidently AI', 'Docker'],
    presentationTips: 'Provide a system topology diagram illustrating data flow from database tables to MLflow and production nodes.',
  },
  {
    pathSlug: 'machine-learning-engineering',
    stageNumber: 3,
    title: 'Fine-Tune a Large Language Model (LLM)',
    description: 'Use LoRA (Low-Rank Adaptation) or QLoRA to fine-tune an open-source LLM (e.g., Llama 3 or Mistral) on a specific domain dataset.',
    deliverables: ['Hugging Face model repository link', 'Notebook demonstrating the fine-tuning process'],
    acceptanceCriteria: ['Successfully loads a quantized model to fit in consumer GPU memory', 'Demonstrates the model answering domain-specific prompts correctly after training'],
    difficulty: 5,
    expectedOutput: 'A custom-trained Generative AI model adapted for a specific business use case.',
    skillsExercised: ['LLM Fine-Tuning', 'PEFT (LoRA/QLoRA)', 'Hugging Face Transformers', 'Quantization'],
    suggestedTools: ['Hugging Face AutoTrain', 'PyTorch', 'Google Colab (A100/T4)'],
    presentationTips: 'Include side-by-side prompt responses showing the base model failing and your fine-tuned model succeeding on the same question.',
  },
  {
    pathSlug: 'machine-learning-engineering',
    stageNumber: 3,
    title: 'Build an End-to-End Recommendation System',
    description: 'Develop a hybrid recommendation engine using Collaborative Filtering and Content-Based Filtering to suggest products or movies to users.',
    deliverables: ['GitHub Repository', 'Jupyter Notebook with evaluation metrics (NDCG or MAP)'],
    acceptanceCriteria: ['Solves the "Cold Start" problem for new users', 'Matrix Factorization techniques are applied'],
    difficulty: 5,
    expectedOutput: 'A highly complex personalization engine similar to those used by Netflix or Amazon.',
    skillsExercised: ['Recommendation Systems', 'Collaborative Filtering', 'Matrix Factorization', 'Information Retrieval Metrics'],
    suggestedTools: ['Surprise Library', 'scikit-learn', 'TensorFlow Recommenders'],
    presentationTips: 'Explain exactly how the hybrid approach balances popular items against highly niche, personalized items.',
  },
  {
    pathSlug: 'machine-learning-engineering',
    stageNumber: 3,
    title: 'Deploy Model to Edge / Browser (TensorFlow.js)',
    description: 'Convert a trained deep learning model and deploy it directly into a web browser using TensorFlow.js or ONNX Web to run client-side inferences.',
    deliverables: ['Live webpage URL running the model', 'GitHub repository containing the conversion scripts'],
    acceptanceCriteria: ['Model runs locally in the browser utilizing WebGL or WebAssembly', 'Inference latency is under 100ms'],
    difficulty: 5,
    expectedOutput: 'A lightning-fast, privacy-preserving AI application running entirely on the user\'s device.',
    skillsExercised: ['Edge AI', 'TensorFlow.js / ONNX', 'Model Compression', 'Client-side Architecture'],
    suggestedTools: ['TensorFlow.js', 'ONNX Runtime Web', 'React / Vanilla JS'],
    presentationTips: 'Highlight the privacy benefits of your architecture—explain how no user data is sent to a backend server during inference.',
  }
];
