export const TASKS_PART_3 = [
  // ════════════════════════════════════════════
  // 1. PRODUCT DESIGN
  // ════════════════════════════════════════════
  // Stage 4 (Metrics, Analytics & Experimentation)
  {
    pathSlug: 'product-design',
    stageNumber: 4,
    title: 'A/B Test Variant Design',
    description: 'Design two contrasting variations of a high-conversion screen (e.g. checkout or sign-up) formulated specifically for an A/B split test.',
    deliverables: ['Figma file with Control and Variant screens', 'Hypothesis document detailing what change drives the expected lift'],
    acceptanceCriteria: ['Variant introduces only one major change (e.g., layout or CTA hierarchy) to ensure statistical validity', 'Designs must accommodate identical copy'],
    difficulty: 4,
    expectedOutput: 'Production-ready variant designs primed for development and split testing.',
    skillsExercised: ['Conversion Rate Optimization (CRO)', 'A/B Testing Methodology', 'Interaction Design'],
    suggestedTools: ['Figma', 'VWO (concept)'],
    presentationTips: 'Clearly state your hypothesis: "By changing X to Y, we expect metric Z to increase because..."',
  },
  {
    pathSlug: 'product-design',
    stageNumber: 4,
    title: 'Heatmap & Click-Tracking Analysis',
    description: 'Analyze provided qualitative data (e.g., Hotjar heatmaps or session recordings) to identify UI friction points and design a solution.',
    deliverables: ['Audit report mapping friction points to video timestamps', 'Redesigned UI mockups solving the discovered issues'],
    acceptanceCriteria: ['Redesign directly addresses "rage clicks" or high drop-off zones', 'Reduces cognitive load of the interface'],
    difficulty: 4,
    expectedOutput: 'A data-informed redesign that directly solves documented user frustration.',
    skillsExercised: ['Qualitative Data Analysis', 'UX Auditing', 'Behavioral Design'],
    suggestedTools: ['Hotjar/Clarity', 'Figma'],
    presentationTips: 'Use screenshots of the heatmaps overlaid next to your redesign to visually prove why the change was made.',
  },
  {
    pathSlug: 'product-design',
    stageNumber: 4,
    title: 'Design for Accessibility (WCAG 2.1 AA Audit)',
    description: 'Perform a comprehensive WCAG accessibility audit on a complex web app, redesigning inaccessible components.',
    deliverables: ['Accessibility audit spreadsheet', 'Accessible component library update in Figma'],
    acceptanceCriteria: ['Checks for color contrast, focus states, and screen reader semantic ordering', 'Redesigned components pass WCAG 2.1 AA standards'],
    difficulty: 4,
    expectedOutput: 'An inclusive design framework ensuring usability for visually or motor-impaired users.',
    skillsExercised: ['WCAG Compliance', 'Inclusive Design', 'Color Contrast Tooling'],
    suggestedTools: ['Stark (Figma Plugin)', 'WAVE Tool'],
    presentationTips: 'Document the expected keyboard navigation order (Tab index mapping) for the developers.',
  },
  {
    pathSlug: 'product-design',
    stageNumber: 4,
    title: 'Design Metric Dashboard Configuration',
    description: 'Define the core UX metrics (e.g., Time on Task, Success Rate, System Usability Scale) for a product and design the internal dashboard that tracks them.',
    deliverables: ['UX Metrics specification document', 'Internal dashboard wireframes for the product team'],
    acceptanceCriteria: ['Defines both behavioral (what they do) and attitudinal (what they say) metrics', 'Dashboard provides a holistic view of product health'],
    difficulty: 4,
    expectedOutput: 'A strategic measurement framework translating subjective user experience into objective data.',
    skillsExercised: ['UX Metrics (HEART framework)', 'Data Visualization Design', 'Strategic Measurement'],
    suggestedTools: ['Amplitude/Mixpanel', 'Figma'],
    presentationTips: 'Explain how the Google HEART framework applies to your specific design choices.',
  },
  // Stage 5 (Go-To-Market, Growth & Product Leadership)
  {
    pathSlug: 'product-design',
    stageNumber: 5,
    title: 'DesignOps Workflow Architecture',
    description: 'Architect a DesignOps workflow detailing how design requests are triaged, how files are structured, and how handoffs to engineering occur.',
    deliverables: ['DesignOps playbook document', 'Visual flowchart of the design lifecycle'],
    acceptanceCriteria: ['Defines file naming conventions, branching strategies in Figma, and Jira integration steps', 'Establishes SLA expectations for design reviews'],
    difficulty: 5,
    expectedOutput: 'A highly operational playbook that scales design teams efficiently.',
    skillsExercised: ['Design Operations (DesignOps)', 'Cross-functional Collaboration', 'Process Engineering'],
    suggestedTools: ['Notion', 'Lucidchart', 'Figma Branching'],
    presentationTips: 'Highlight how this process reduces "design debt" and prevents engineers from building outdated mockups.',
  },
  {
    pathSlug: 'product-design',
    stageNumber: 5,
    title: 'Product Vision & North Star Design',
    description: 'Create a "North Star" conceptual prototype showing the 3-year future vision of a product to secure executive buy-in.',
    deliverables: ['High-fidelity conceptual video or prototype', 'Slide deck pitching the future vision'],
    acceptanceCriteria: ['Pushes beyond current technical constraints to inspire innovation', 'Aligns with long-term business strategy'],
    difficulty: 5,
    expectedOutput: 'A visionary, high-impact presentation used to align entire companies on a product direction.',
    skillsExercised: ['Visionary Thinking', 'Executive Storytelling', 'Advanced Prototyping'],
    suggestedTools: ['Protopie', 'After Effects', 'Figma'],
    presentationTips: 'Frame the pitch as a story—start with the current user pain, introduce the paradigm shift, and reveal the North Star solution.',
  },
  {
    pathSlug: 'product-design',
    stageNumber: 5,
    title: 'Cross-Platform Design System Governance',
    description: 'Define the governance model for an enterprise design system spanning Web, iOS, and Android platforms.',
    deliverables: ['Governance model document detailing contribution guidelines', 'Cross-platform component mapping spreadsheet'],
    acceptanceCriteria: ['Establishes a process for proposing, reviewing, and deprecating components', 'Accounts for native OS guidelines (Material Design vs HIG)'],
    difficulty: 5,
    expectedOutput: 'An enterprise-grade management strategy ensuring UI consistency across entirely different codebases.',
    skillsExercised: ['Design System Governance', 'Platform Guidelines (HIG/Material)', 'Change Management'],
    suggestedTools: ['Zeroheight', 'Notion'],
    presentationTips: 'Create a clear flowchart showing how an engineer or designer can submit a "New Component Request".',
  },
  {
    pathSlug: 'product-design',
    stageNumber: 5,
    title: 'Growth Design & Viral Loop Implementation',
    description: 'Design a growth-focused feature (like a referral program or gamified onboarding) intended to drastically lower Customer Acquisition Cost (CAC).',
    deliverables: ['Interactive prototype of the growth loop', 'Growth mechanics specification document'],
    acceptanceCriteria: ['Incorporates behavioral psychology (e.g., variable rewards, social proof)', 'Seamlessly integrates into the existing product ecosystem'],
    difficulty: 5,
    expectedOutput: 'A strategic, psychology-driven design that acts as a marketing engine within the product.',
    skillsExercised: ['Growth Design', 'Behavioral Psychology', 'Viral Loops', 'Gamification'],
    suggestedTools: ['Figma', 'Miro'],
    presentationTips: 'Identify the exact "Aha! moment" in your onboarding flow and explain how the design accelerates the user toward it.',
  },

  // ════════════════════════════════════════════
  // 2. FRONTEND ENGINEERING
  // ════════════════════════════════════════════
  // Stage 4 (Metrics, Analytics & Experimentation)
  {
    pathSlug: 'frontend-engineering',
    stageNumber: 4,
    title: 'Implement Micro-Frontends Architecture',
    description: 'Split a monolithic frontend application into two independent micro-frontends using Webpack Module Federation.',
    deliverables: ['GitHub repository containing the host and remote apps', 'Architecture diagram detailing the federation'],
    acceptanceCriteria: ['Host application dynamically loads the remote application at runtime', 'Shared dependencies (like React) are not downloaded twice'],
    difficulty: 5,
    expectedOutput: 'A scalable enterprise frontend architecture allowing independent team deployments.',
    skillsExercised: ['Micro-frontends', 'Webpack Module Federation', 'Build Tooling Architecture'],
    suggestedTools: ['Webpack 5', 'React', 'Nx (optional)'],
    presentationTips: 'Demonstrate how you handle routing across the different federated modules without breaking browser history.',
  },
  {
    pathSlug: 'frontend-engineering',
    stageNumber: 4,
    title: 'Advanced WebGL / Three.js Interactive Scene',
    description: 'Build an interactive 3D scene using Three.js or React Three Fiber that responds to user scroll and mouse movements.',
    deliverables: ['Live deployed URL of the 3D experience', 'GitHub repository link'],
    acceptanceCriteria: ['Scene maintains a consistent 60 FPS frame rate', 'Includes custom shaders, lighting, and shadow mapping'],
    difficulty: 5,
    expectedOutput: 'A highly engaging, performant 3D web experience demonstrating graphics programming.',
    skillsExercised: ['WebGL', 'Three.js / React Three Fiber', 'Graphics Rendering', 'Shaders (GLSL)'],
    suggestedTools: ['React Three Fiber', 'Blender (for models)', 'Vite'],
    presentationTips: 'Explain the optimization techniques used to prevent memory leaks when disposing of 3D geometries and materials.',
  },
  {
    pathSlug: 'frontend-engineering',
    stageNumber: 4,
    title: 'Offline-First Progressive Web App (PWA)',
    description: 'Convert a standard web application into a fully offline-capable PWA using Service Workers and IndexedDB.',
    deliverables: ['Live PWA deployment link', 'Lighthouse PWA audit report'],
    acceptanceCriteria: ['App installs to home screen on mobile', 'Content remains accessible when device is completely offline', 'Background sync implemented'],
    difficulty: 4,
    expectedOutput: 'A resilient web application that functions like a native mobile app without an internet connection.',
    skillsExercised: ['Service Workers', 'IndexedDB', 'PWA Manifests', 'Cache Storage API'],
    suggestedTools: ['Workbox', 'React/Next.js'],
    presentationTips: 'Record a video demonstrating the app being used, data being entered, and syncing properly while the network tab is set to "Offline".',
  },
  {
    pathSlug: 'frontend-engineering',
    stageNumber: 4,
    title: 'Custom State Management Library',
    description: 'Build a lightweight, highly optimized state management library from scratch (similar to Zustand or Redux) and use it in an app.',
    deliverables: ['NPM package or local library code', 'Sample application utilizing the custom store'],
    acceptanceCriteria: ['Supports reactive subscriptions without unnecessary component re-renders', 'Includes a mechanism for middleware or DevTools logging'],
    difficulty: 5,
    expectedOutput: 'A deep demonstration of JavaScript closures, proxies, and React architectural patterns.',
    skillsExercised: ['Advanced JavaScript Patterns', 'React Hooks Architecture', 'Performance Optimization'],
    suggestedTools: ['TypeScript', 'ReactHooks', 'ES6 Proxies'],
    presentationTips: 'Compare your library’s bundle size and render performance against established libraries like Redux to prove its value.',
  },
  // Stage 5 (Go-To-Market, Growth & Product Leadership)
  {
    pathSlug: 'frontend-engineering',
    stageNumber: 5,
    title: 'Server-Driven UI Architecture',
    description: 'Implement a Server-Driven UI (SDUI) system where the backend API completely dictates the frontend layout, components, and content.',
    deliverables: ['GitHub repository with both frontend and backend mocking the JSON structure', 'Live deployment showing dynamic rendering'],
    acceptanceCriteria: ['Frontend contains no hardcoded page layouts, only a component registry mapping JSON nodes to React components'],
    difficulty: 5,
    expectedOutput: 'A highly dynamic frontend architecture favored by companies like Airbnb and Uber for immediate UI updates without app store reviews.',
    skillsExercised: ['Server-Driven UI', 'Component Registries', 'Dynamic Rendering', 'Schema Design'],
    suggestedTools: ['Next.js', 'TypeScript', 'Node.js'],
    presentationTips: 'Show how changing the JSON payload instantly swaps a "Hero Banner" for a "Carousel" without touching frontend code.',
  },
  {
    pathSlug: 'frontend-engineering',
    stageNumber: 5,
    title: 'Compile C/Rust to WebAssembly (Wasm)',
    description: 'Write a computationally heavy algorithm in Rust or C, compile it to WebAssembly, and execute it within a JavaScript frontend.',
    deliverables: ['GitHub repository containing Rust/C source and JS bindings', 'Live demo comparing JS performance vs Wasm performance'],
    acceptanceCriteria: ['Wasm module loads asynchronously', 'Performance benchmark shows significant execution speed improvement over pure JS'],
    difficulty: 5,
    expectedOutput: 'A blazing fast web application offloading heavy computation (e.g., image processing or physics) to WebAssembly.',
    skillsExercised: ['WebAssembly (Wasm)', 'Rust/C++', 'JavaScript Interop', 'Low-level Optimization'],
    suggestedTools: ['Rust', 'wasm-pack', 'Vite'],
    presentationTips: 'Include a visual graph comparing the execution time (in milliseconds) of the Wasm function versus the JS equivalent.',
  },
  {
    pathSlug: 'frontend-engineering',
    stageNumber: 5,
    title: 'Architect a Frontend Testing Strategy',
    description: 'Design and implement a comprehensive, multi-layered testing strategy (Unit, Integration, E2E, and Visual Regression) for a large codebase.',
    deliverables: ['Testing architecture document', 'Configured CI pipeline running Cypress, Jest, and Chromatic'],
    acceptanceCriteria: ['Unit tests cover isolated logic, Cypress covers critical user flows, Chromatic prevents unintended CSS changes'],
    difficulty: 4,
    expectedOutput: 'A mature quality assurance pipeline that guarantees code reliability before deployment.',
    skillsExercised: ['End-to-End Testing', 'Visual Regression Testing', 'Test-Driven Development (TDD)', 'CI Integration'],
    suggestedTools: ['Cypress/Playwright', 'Jest/Vitest', 'Chromatic / Storybook'],
    presentationTips: 'Explain the "Testing Trophy" concept and why you allocated specific percentages of testing to Integration versus E2E.',
  },
  {
    pathSlug: 'frontend-engineering',
    stageNumber: 5,
    title: 'Frontend CI/CD & Infrastructure as Code',
    description: 'Deploy a complex Next.js application using strictly Infrastructure as Code (Terraform) on AWS, bypassing Vercel.',
    deliverables: ['Terraform scripts (.tf)', 'Architecture diagram of the AWS setup'],
    acceptanceCriteria: ['Application utilizes AWS CloudFront, S3 for static assets, and Lambda@Edge for server-side rendering', 'Fully automated via GitHub Actions'],
    difficulty: 5,
    expectedOutput: 'An enterprise-grade deployment demonstrating full control over the hosting infrastructure.',
    skillsExercised: ['Infrastructure as Code (Terraform)', 'AWS Hosting', 'Serverless SSR', 'DevOps'],
    suggestedTools: ['Terraform', 'AWS Lambda@Edge', 'GitHub Actions'],
    presentationTips: 'Detail the cost-saving benefits and security controls gained by hosting on raw AWS versus a PaaS like Vercel.',
  },

  // ════════════════════════════════════════════
  // 3. DATA ANALYSIS
  // ════════════════════════════════════════════
  // Stage 4 (Metrics, Analytics & Experimentation)
  {
    pathSlug: 'data-analysis',
    stageNumber: 4,
    title: 'Distributed Data Processing with PySpark',
    description: 'Process a massive dataset (e.g., 10GB+ of logs) using Apache Spark (PySpark) to perform aggregations that would crash pandas.',
    deliverables: ['PySpark script/notebook', 'Execution logs showing processing time and cluster setup'],
    acceptanceCriteria: ['Successfully executes transformations (Map/Reduce) across a distributed dataset', 'Outputs aggregated results to a Parquet file'],
    difficulty: 4,
    expectedOutput: 'A scalable big data pipeline handling volumes impossible for local memory.',
    skillsExercised: ['Big Data Processing', 'Apache Spark / PySpark', 'Distributed Computing', 'Parquet Formats'],
    suggestedTools: ['Databricks Community Edition', 'PySpark', 'Google Colab'],
    presentationTips: 'Explain the concept of "lazy evaluation" in Spark and how it optimizes the execution plan.',
  },
  {
    pathSlug: 'data-analysis',
    stageNumber: 4,
    title: 'Design a Data Warehouse Schema (dbt)',
    description: 'Design a star-schema data warehouse and use dbt (data build tool) to transform raw data into analytical models.',
    deliverables: ['dbt project repository', 'Lineage graph generated by dbt docs'],
    acceptanceCriteria: ['Implements dimensional modeling (Fact and Dimension tables)', 'Includes data quality tests (e.g., uniqueness, non-null) in dbt'],
    difficulty: 5,
    expectedOutput: 'A modern data stack implementation ensuring reliable, tested, and documented analytics.',
    skillsExercised: ['Analytics Engineering', 'dbt (data build tool)', 'Dimensional Modeling', 'Data Testing'],
    suggestedTools: ['dbt Core', 'Snowflake / BigQuery / Postgres'],
    presentationTips: 'Show the DAG (Directed Acyclic Graph) of your models to demonstrate how data flows from raw sources to final aggregates.',
  },
  {
    pathSlug: 'data-analysis',
    stageNumber: 4,
    title: 'Advanced Machine Learning Integration',
    description: 'Integrate a predictive machine learning model (e.g., predicting customer churn) directly into a BI dashboard so stakeholders can adjust input parameters.',
    deliverables: ['Live Tableau/PowerBI/Streamlit dashboard', 'Python model training script'],
    acceptanceCriteria: ['Dashboard displays the "Probability of Churn" for customers', 'Allows stakeholders to filter segments and see predicted outcomes'],
    difficulty: 5,
    expectedOutput: 'A predictive analytics dashboard shifting from "what happened" to "what will happen".',
    skillsExercised: ['Predictive Analytics', 'Dashboard Integration', 'Model Deployment for BI'],
    suggestedTools: ['Tableau (TabPy)', 'Power BI (Python script)', 'Streamlit'],
    presentationTips: 'Keep the machine learning jargon out of the dashboard—present the predictions as simple percentage risks for business users.',
  },
  {
    pathSlug: 'data-analysis',
    stageNumber: 4,
    title: 'Automated Anomaly Detection System',
    description: 'Build a Python script that continuously scans daily metric logs and triggers a Slack/Email alert if a statistically significant anomaly is detected.',
    deliverables: ['GitHub repository with the anomaly detection logic', 'Screenshot of the triggered alert in Slack/Email'],
    acceptanceCriteria: ['Utilizes Isolation Forests or Moving Average Z-Scores to flag outliers', 'Avoids false positives through seasonal adjustments'],
    difficulty: 4,
    expectedOutput: 'A proactive data monitoring system that alerts businesses to issues before customers report them.',
    skillsExercised: ['Anomaly Detection', 'Time Series Monitoring', 'Alerting Integrations', 'Statistical Process Control'],
    suggestedTools: ['Python', 'Slack Webhooks', 'scikit-learn'],
    presentationTips: 'Explain how you tuned the sensitivity threshold to prevent "alert fatigue" among the engineering team.',
  },
  // Stage 5 (Go-To-Market, Growth & Product Leadership)
  {
    pathSlug: 'data-analysis',
    stageNumber: 5,
    title: 'Data Governance & Data Quality Framework',
    description: 'Draft an enterprise Data Governance policy detailing data ownership, access controls, compliance (GDPR), and quality SLAs.',
    deliverables: ['Data Governance Policy Document', 'Data Catalog template'],
    acceptanceCriteria: ['Defines PII (Personally Identifiable Information) masking procedures', 'Establishes clear SLAs for data freshness and accuracy'],
    difficulty: 5,
    expectedOutput: 'A strategic compliance and quality framework required for scaling data teams in enterprise environments.',
    skillsExercised: ['Data Governance', 'Compliance (GDPR/CCPA)', 'Data Cataloging', 'Data Quality SLAs'],
    suggestedTools: ['Notion', 'Collibra (concept)'],
    presentationTips: 'Treat data as a product—explain how this governance framework guarantees the "SLA" of the data product to internal stakeholders.',
  },
  {
    pathSlug: 'data-analysis',
    stageNumber: 5,
    title: 'Executive Data Storytelling & Strategy',
    description: 'Translate a complex 50-page analytical deep-dive into a high-impact, 5-slide presentation tailored strictly for C-level executives.',
    deliverables: ['5-slide Executive Presentation (PDF)', 'Presenter notes explaining the narrative arc'],
    acceptanceCriteria: ['Eliminates all exploratory charts, focusing purely on business impact and required decisions', 'Slide titles state the conclusion, not the topic'],
    difficulty: 4,
    expectedOutput: 'A masterful demonstration of communication, distilling complex math into millions of dollars of business value.',
    skillsExercised: ['Executive Communication', 'Data Storytelling', 'Strategic Influence', 'Information Synthesis'],
    suggestedTools: ['Google Slides', 'Think-Cell / Canva'],
    presentationTips: 'Start with the recommendation on Slide 1. Executives want the bottom line up front (BLUF).',
  },
  {
    pathSlug: 'data-analysis',
    stageNumber: 5,
    title: 'Marketing Mix Modeling (MMM)',
    description: 'Build a statistical Marketing Mix Model (MMM) using historical sales and ad spend data to determine the true ROI of different marketing channels.',
    deliverables: ['Jupyter Notebook with MMM regression analysis', 'Budget reallocation recommendation report'],
    acceptanceCriteria: ['Accounts for adstock (carryover effects) and diminishing returns', 'Outputs a concrete recommendation for next quarter\'s budget split'],
    difficulty: 5,
    expectedOutput: 'An advanced econometric model solving multi-channel attribution without relying on tracking cookies.',
    skillsExercised: ['Econometrics', 'Marketing Mix Modeling', 'Advanced Regression', 'Budget Optimization'],
    suggestedTools: ['Python (Statsmodels)', 'Robyn (Meta MMM library)'],
    presentationTips: 'Address the difference between correlation and causation in your presentation, explaining how you handled external variables like seasonality.',
  },
  {
    pathSlug: 'data-analysis',
    stageNumber: 5,
    title: 'Design a Real-Time Streaming Architecture',
    description: 'Architect and deploy a proof-of-concept pipeline that processes streaming data (e.g., website clicks) in real-time rather than batches.',
    deliverables: ['Architecture diagram of the streaming setup', 'Code repository for the stream processor'],
    acceptanceCriteria: ['Uses Kafka, Kinesis, or Pub/Sub to ingest messages', 'Processes and outputs aggregations (like "clicks per minute") continuously'],
    difficulty: 5,
    expectedOutput: 'A high-velocity data pipeline enabling instant business reactions to user behavior.',
    skillsExercised: ['Streaming Data Architecture', 'Apache Kafka / Kinesis', 'Real-time Aggregation'],
    suggestedTools: ['Apache Kafka', 'ksqlDB', 'AWS Kinesis'],
    presentationTips: 'Explain the trade-offs between "exactly-once" and "at-least-once" message delivery semantics in your architecture.',
  },

  // ════════════════════════════════════════════
  // 4. PRODUCT MANAGEMENT
  // ════════════════════════════════════════════
  // Stage 4 (Metrics, Analytics & Experimentation)
  {
    pathSlug: 'product-management',
    stageNumber: 4,
    title: 'Design an Advanced Experimentation Strategy',
    description: 'Design a multivariate test (MVT) or sequential testing plan for a complex feature where standard A/B testing is insufficient.',
    deliverables: ['Experimentation strategy document', 'Statistical significance calculation models'],
    acceptanceCriteria: ['Accounts for interaction effects between multiple variables', 'Defines guardrail metrics to prevent long-term degradation'],
    difficulty: 5,
    expectedOutput: 'A rigorous scientific testing plan suitable for high-traffic, mature products.',
    skillsExercised: ['Multivariate Testing (MVT)', 'Statistical Analysis', 'Experimentation Culture'],
    suggestedTools: ['Optimizely', 'Amplitude', 'Excel/Google Sheets'],
    presentationTips: 'Explain how you mitigate the "Novelty Effect" (users clicking things just because they are new) in your test duration planning.',
  },
  {
    pathSlug: 'product-management',
    stageNumber: 4,
    title: 'Product Pricing & Packaging Overhaul',
    description: 'Conduct a pricing analysis for a SaaS product and propose a new tiered pricing model based on value metrics rather than feature gating.',
    deliverables: ['Pricing strategy memo', 'Value metric mapping spreadsheet'],
    acceptanceCriteria: ['Identifies the core value metric (e.g., seats, API calls, storage)', 'Proposes Good/Better/Best tiers with clear upgrade paths'],
    difficulty: 5,
    expectedOutput: 'A fundamental business strategy document that directly impacts MRR and customer expansion.',
    skillsExercised: ['Pricing Strategy', 'Packaging/Tiering', 'Value Metric Identification', 'Revenue Modeling'],
    suggestedTools: ['Excel', 'Notion'],
    presentationTips: 'Include an analysis of how existing legacy customers will be migrated to the new pricing tiers without causing massive churn.',
  },
  {
    pathSlug: 'product-management',
    stageNumber: 4,
    title: 'Platform Strategy & API Productization',
    description: 'Design a strategy to transition a standalone product into a platform ecosystem by exposing public APIs and developer tools.',
    deliverables: ['Platform strategy PRD', 'API developer portal wireframes'],
    acceptanceCriteria: ['Defines the monetization model for API usage', 'Includes user stories specifically for external developers (not end-users)'],
    difficulty: 5,
    expectedOutput: 'A strategic shift enabling third-party integrations and massive ecosystem growth.',
    skillsExercised: ['Platform Strategy', 'API Product Management', 'Developer Experience (DX)', 'Ecosystem Building'],
    suggestedTools: ['Postman', 'Notion', 'Figma'],
    presentationTips: 'Treat the API documentation as the primary UI for this product; explain how you will optimize the "Time to First API Call".',
  },
  {
    pathSlug: 'product-management',
    stageNumber: 4,
    title: 'Mergers & Acquisitions (M&A) Product Due Diligence',
    description: 'Evaluate a hypothetical acquisition target, writing a due diligence report on their tech stack, product debt, and integration feasibility.',
    deliverables: ['Product Due Diligence Memo (PDF)'],
    acceptanceCriteria: ['Assesses technical debt and architectural overlap', 'Outlines a 90-day post-acquisition integration roadmap'],
    difficulty: 5,
    expectedOutput: 'An executive-level analysis guiding multi-million dollar corporate development decisions.',
    skillsExercised: ['M&A Due Diligence', 'Technical Debt Assessment', 'Strategic Integration', 'Corporate Strategy'],
    suggestedTools: ['Google Docs', 'Miro'],
    presentationTips: 'Highlight the risk factors—what happens to the target’s existing customer base during the platform migration?',
  },
  // Stage 5 (Go-To-Market, Growth & Product Leadership)
  {
    pathSlug: 'product-management',
    stageNumber: 5,
    title: 'Build a Product Portfolio Strategy',
    description: 'Manage a portfolio of 3-5 distinct products, making resource allocation decisions across Horizon 1 (core), Horizon 2 (growth), and Horizon 3 (innovation) initiatives.',
    deliverables: ['Portfolio Allocation Matrix', 'Executive resource request presentation'],
    acceptanceCriteria: ['Allocates engineering headcount logically across the 3 horizons', 'Justifies cutting funding from a "cash cow" to fund a risky innovation'],
    difficulty: 5,
    expectedOutput: 'A master-level demonstration of product leadership, balancing short-term revenue with long-term survival.',
    skillsExercised: ['Portfolio Management', 'Three Horizons of Growth', 'Resource Allocation', 'Executive Leadership'],
    suggestedTools: ['Miro', 'Excel', 'Google Slides'],
    presentationTips: 'Defend your decision to kill a beloved but unprofitable product—executives look for PMs who can make hard, objective cuts.',
  },
  {
    pathSlug: 'product-management',
    stageNumber: 5,
    title: 'Establish Product Operations (ProdOps)',
    description: 'Design a Product Operations framework to standardize roadmapping, user research synthesis, and cross-functional communication across a 50+ person PM team.',
    deliverables: ['ProdOps Playbook Document', 'Tooling architecture diagram'],
    acceptanceCriteria: ['Standardizes the intake process for feature requests from Sales and Support', 'Automates the generation of executive status reports'],
    difficulty: 5,
    expectedOutput: 'An operational scaling framework that acts as the connective tissue for large product organizations.',
    skillsExercised: ['Product Operations (ProdOps)', 'Process Scaling', 'Tooling Architecture', 'Cross-functional Alignment'],
    suggestedTools: ['Productboard', 'Jira', 'Notion'],
    presentationTips: 'Focus on eliminating "shadow roadmaps" (sales teams keeping their own feature lists) through transparency and centralized tooling.',
  },
  {
    pathSlug: 'product-management',
    stageNumber: 5,
    title: 'Lead a Cross-Functional Crisis Resolution',
    description: 'Simulate a major PR or security crisis (e.g., massive data breach). Draft the external communication strategy, the internal engineering pivot plan, and the stakeholder management playbook.',
    deliverables: ['Crisis Management Playbook', 'Drafted public statements and internal memos'],
    acceptanceCriteria: ['Pauses non-critical roadmap items effectively', 'Communication is transparent, legally compliant, and empathetic'],
    difficulty: 5,
    expectedOutput: 'A leadership simulation proving the ability to maintain composure and direction during chaotic, high-stakes events.',
    skillsExercised: ['Crisis Management', 'Stakeholder Communication', 'Rapid Reprioritization', 'PR Strategy'],
    suggestedTools: ['Google Docs'],
    presentationTips: 'Emphasize cross-functional coordination—how do you keep Legal, Marketing, and Engineering perfectly aligned hour-by-hour?',
  },
  {
    pathSlug: 'product-management',
    stageNumber: 5,
    title: 'Define Organizational OKRs',
    description: 'Draft the Objectives and Key Results (OKRs) for an entire 100-person product and engineering department, ensuring alignment with corporate financial goals.',
    deliverables: ['Departmental OKR Spreadsheet', 'Cascade diagram showing how individual team goals roll up into the departmental OKRs'],
    acceptanceCriteria: ['Objectives are qualitative and inspiring; Key Results are strictly quantitative and measurable', 'Avoids "shipping a feature" as a Key Result (focuses on outcomes)'],
    difficulty: 5,
    expectedOutput: 'A strategic alignment tool that directs the daily work of dozens of squads toward a unified business objective.',
    skillsExercised: ['OKR Framework', 'Goal Cascading', 'Strategic Alignment', 'Outcome-Oriented Planning'],
    suggestedTools: ['Excel', 'Perdoo / Lattice (concept)'],
    presentationTips: 'Explain the difference between a committed OKR (must hit 100%) and an aspirational OKR (hitting 70% is a success) in your briefing.',
  },

  // ════════════════════════════════════════════
  // 5. CONTENT STRATEGY
  // ════════════════════════════════════════════
  // Stage 4 (Metrics, Analytics & Experimentation)
  {
    pathSlug: 'content-strategy',
    stageNumber: 4,
    title: 'Content Operations (ContentOps) Setup',
    description: 'Design an enterprise-level ContentOps framework detailing how content is requested, created, approved, published, and maintained across a global organization.',
    deliverables: ['Content Lifecycle Flowchart', 'RACI Matrix for the content team'],
    acceptanceCriteria: ['Defines roles (e.g., SME, Writer, Legal Reviewer) explicitly', 'Establishes SLAs for review cycles to prevent bottlenecks'],
    difficulty: 4,
    expectedOutput: 'A scalable operational machine that produces high-quality content consistently at scale.',
    skillsExercised: ['Content Operations', 'Workflow Design', 'RACI Frameworks', 'Process Scaling'],
    suggestedTools: ['Lucidchart', 'Airtable', 'Notion'],
    presentationTips: 'Highlight the legal/compliance review step, a critical chokepoint in enterprise content creation, and how your process optimizes it.',
  },
  {
    pathSlug: 'content-strategy',
    stageNumber: 4,
    title: 'Implement an AI Content Workflow',
    description: 'Design a workflow that ethically and efficiently integrates Generative AI (LLMs) into the content production process without sacrificing brand voice or accuracy.',
    deliverables: ['AI Usage Guidelines Document', 'Custom prompt library for writers'],
    acceptanceCriteria: ['Mandates human-in-the-loop editing for all AI-generated drafts', 'Prompts are highly engineered to enforce the specific brand tone and style guide'],
    difficulty: 4,
    expectedOutput: 'A modern, forward-looking content strategy that leverages AI for scale while mitigating hallucination and plagiarism risks.',
    skillsExercised: ['AI Prompt Engineering', 'Content Automation', 'Editorial Guidelines', 'Risk Mitigation'],
    suggestedTools: ['ChatGPT / Claude', 'Notion'],
    presentationTips: 'Include strict rules on what data cannot be fed into the AI (e.g., proprietary customer data) to show security awareness.',
  },
  {
    pathSlug: 'content-strategy',
    stageNumber: 4,
    title: 'Enterprise Taxonomy & Metadata Design',
    description: 'Architect a global taxonomy and tagging system for a massive content repository (e.g., a corporate intranet or help center) to drastically improve searchability.',
    deliverables: ['Taxonomy Hierarchy Spreadsheet', 'Metadata Schema Document'],
    acceptanceCriteria: ['Categories are Mutually Exclusive and Collectively Exhaustive (MECE)', 'Defines controlled vocabularies and synonyms for internal search engines'],
    difficulty: 5,
    expectedOutput: 'A robust structural foundation that powers faceted search and personalized content delivery.',
    skillsExercised: ['Taxonomy Design', 'Metadata Architecture', 'Information Architecture', 'Faceted Search'],
    suggestedTools: ['Excel', 'PoolParty (concept)'],
    presentationTips: 'Demonstrate how applying this metadata schema allows for dynamic content recommendations (e.g., "Related Articles" blocks).',
  },
  {
    pathSlug: 'content-strategy',
    stageNumber: 4,
    title: 'Advanced Content Attribution Modeling',
    description: 'Analyze complex multi-touch analytics data to prove the ROI of a top-of-funnel (TOFU) educational blog series on bottom-of-funnel (BOFU) enterprise sales.',
    deliverables: ['Attribution Analysis Report', 'Executive ROI Presentation'],
    acceptanceCriteria: ['Moves beyond First-Click or Last-Click attribution', 'Correlates content consumption with increased deal velocity or larger deal sizes'],
    difficulty: 5,
    expectedOutput: 'A deeply analytical report that justifies multi-million dollar content budgets to the CFO.',
    skillsExercised: ['Marketing Attribution', 'Data Analysis', 'ROI Calculation', 'Executive Reporting'],
    suggestedTools: ['Google Analytics 4', 'Salesforce/HubSpot', 'Excel'],
    presentationTips: 'Focus on the "Assisted Conversions" metric to prove that while the blog didn\'t close the sale directly, it influenced the buyer journey.',
  },
  // Stage 5 (Go-To-Market, Growth & Product Leadership)
  {
    pathSlug: 'content-strategy',
    stageNumber: 5,
    title: 'Internationalization (i18n) Content Strategy',
    description: 'Develop a strategy to localize an English-first content platform into 3 new languages, addressing cultural nuances, SEO, and translation workflows.',
    deliverables: ['Localization Strategy Playbook', 'hreflang SEO mapping document'],
    acceptanceCriteria: ['Differentiates between translation (literal) and transcreation (cultural adaptation)', 'Defines technical SEO requirements for multi-regional sites'],
    difficulty: 5,
    expectedOutput: 'A global expansion plan ensuring brand resonance and search visibility in foreign markets.',
    skillsExercised: ['Localization / Transcreation', 'International SEO (hreflang)', 'Global Workflow Management'],
    suggestedTools: ['Notion', 'Crowdin / Smartling (concept)'],
    presentationTips: 'Highlight the importance of localizing images and idioms, not just text, to truly connect with regional audiences.',
  },
  {
    pathSlug: 'content-strategy',
    stageNumber: 5,
    title: 'Lead a Major Brand Re-positioning',
    description: 'Orchestrate the content rollout for a complete corporate rebranding, ensuring a seamless transition of messaging across thousands of existing assets.',
    deliverables: ['Rebranding Content Rollout Plan', 'Before/After Brand Messaging Matrix'],
    acceptanceCriteria: ['Includes a comprehensive content audit to flag outdated messaging', 'Defines a strict timeline for updating web, social, and product copy simultaneously'],
    difficulty: 5,
    expectedOutput: 'A massive logistical and creative orchestration demonstrating senior leadership capabilities.',
    skillsExercised: ['Brand Strategy', 'Change Management', 'Large-scale Content Auditing', 'Cross-functional Leadership'],
    suggestedTools: ['Airtable', 'Google Sheets', 'Miro'],
    presentationTips: 'Address the SEO risks of a rebrand (URL changes, 301 redirects) and how the content team will work with engineering to mitigate traffic loss.',
  },
  {
    pathSlug: 'content-strategy',
    stageNumber: 5,
    title: 'Design a Developer Relations (DevRel) Content Ecosystem',
    description: 'Architect a highly technical content ecosystem (API Docs, SDK guides, technical blogs, and community forums) aimed at acquiring and retaining software developers.',
    deliverables: ['DevRel Content Strategy PRD', 'Sample API reference documentation layout'],
    acceptanceCriteria: ['Prioritizes "Time to First Hello World"', 'Strategy integrates deeply with GitHub, StackOverflow, and Discord communities'],
    difficulty: 5,
    expectedOutput: 'A specialized content strategy targeting a highly skeptical, ad-averse audience (developers).',
    skillsExercised: ['Technical Writing', 'Developer Experience (DX)', 'Community Building', 'API Documentation'],
    suggestedTools: ['Readme.io', 'Markdown', 'Stoplight'],
    presentationTips: 'Explain why standard marketing copy fails with developers and how "code-first" educational content drives DevRel growth.',
  },
  {
    pathSlug: 'content-strategy',
    stageNumber: 5,
    title: 'Content Acquisition & M&A Integration',
    description: 'Evaluate the content assets of a recently acquired competitor and design the strategy to merge, migrate, or sunset their domains and blogs into the parent brand.',
    deliverables: ['Content Migration Strategy Memo', 'Domain Authority Consolidation Plan'],
    acceptanceCriteria: ['Identifies duplicate content for pruning', 'Strategizes 301 redirects to transfer SEO link juice to the parent domain'],
    difficulty: 5,
    expectedOutput: 'A high-stakes corporate integration plan protecting organic traffic and brand consistency during a merger.',
    skillsExercised: ['M&A Content Strategy', 'SEO Migration', 'Content Consolidation', 'Executive Strategy'],
    suggestedTools: ['Ahrefs', 'Screaming Frog', 'Excel'],
    presentationTips: 'Emphasize the risk of breaking millions of inbound links; the migration plan must be flawless to preserve domain authority.',
  }
];
