export const TASKS_PART_4 = [
  // ════════════════════════════════════════════
  // 6. BACKEND ENGINEERING
  // ════════════════════════════════════════════
  // Stage 4 (Metrics, Analytics & Experimentation)
  {
    pathSlug: 'backend-engineering',
    stageNumber: 4,
    title: 'Implement Event-Driven Architecture (Kafka)',
    description: 'Deconstruct a synchronous REST API into an asynchronous Event-Driven Architecture using Apache Kafka or AWS EventBridge.',
    deliverables: ['GitHub repository containing publisher and subscriber microservices', 'Docker Compose file running Kafka/Zookeeper'],
    acceptanceCriteria: ['Microservices communicate strictly via message events, not HTTP', 'Implements dead-letter queues (DLQ) for failed message processing'],
    difficulty: 5,
    expectedOutput: 'A highly decoupled, scalable backend system capable of handling massive event throughput.',
    skillsExercised: ['Event-Driven Architecture', 'Apache Kafka / Pub-Sub', 'Dead-Letter Queues', 'Microservices Decoupling'],
    suggestedTools: ['Node.js/Go', 'Apache Kafka', 'Docker'],
    presentationTips: 'Explain how you guarantee message ordering and prevent duplicate processing (idempotency) in your consumer logic.',
  },
  {
    pathSlug: 'backend-engineering',
    stageNumber: 4,
    title: 'Build a Federated GraphQL API',
    description: 'Migrate a collection of disparate REST microservices into a single, unified GraphQL Supergraph using Apollo Federation.',
    deliverables: ['GitHub repository with the GraphQL Gateway and Subgraphs', 'Sample GraphQL queries testing the federation'],
    acceptanceCriteria: ['Gateway successfully stitches schemas from at least 2 independent subgraphs', 'Resolves nested entity relationships across different services'],
    difficulty: 5,
    expectedOutput: 'A modern data-fetching layer that drastically improves frontend developer experience.',
    skillsExercised: ['GraphQL Federation', 'Apollo Gateway', 'Schema Stitching', 'Microservices Integration'],
    suggestedTools: ['Apollo Server', 'GraphQL', 'Node.js'],
    presentationTips: 'Demonstrate how the N+1 query problem is mitigated in your subgraphs using DataLoader.',
  },
  {
    pathSlug: 'backend-engineering',
    stageNumber: 4,
    title: 'Distributed Tracing & Observability',
    description: 'Instrument a complex microservices application with OpenTelemetry to provide distributed tracing and centralize logs.',
    deliverables: ['Codebase injected with OpenTelemetry SDKs', 'Screenshots of Jaeger/Zipkin dashboards showing request traces'],
    acceptanceCriteria: ['A single HTTP request trace can be followed across at least 3 distinct microservices', 'Logs correlate with trace IDs'],
    difficulty: 4,
    expectedOutput: 'An enterprise-grade observability setup essential for debugging distributed systems.',
    skillsExercised: ['Observability', 'Distributed Tracing', 'OpenTelemetry', 'Log Aggregation'],
    suggestedTools: ['OpenTelemetry', 'Jaeger / Zipkin', 'Prometheus'],
    presentationTips: 'Show a specific example of finding a latency bottleneck in one microservice by analyzing the waterfall trace graph.',
  },
  {
    pathSlug: 'backend-engineering',
    stageNumber: 4,
    title: 'Implement gRPC for Internal Microservices',
    description: 'Replace JSON/HTTP communication between two internal microservices with high-performance gRPC and Protocol Buffers.',
    deliverables: ['GitHub repository with `.proto` schema files and generated client/server code', 'Benchmark script comparing JSON REST vs gRPC performance'],
    acceptanceCriteria: ['Services communicate successfully using binary Protobuf payloads', 'Benchmark proves lower latency and CPU usage compared to REST'],
    difficulty: 5,
    expectedOutput: 'A blazing fast internal communication protocol used by massive tech companies.',
    skillsExercised: ['gRPC Protocol', 'Protocol Buffers (Protobuf)', 'RPC Architecture', 'Performance Benchmarking'],
    suggestedTools: ['gRPC', 'Protoc', 'Go / Node.js'],
    presentationTips: 'Highlight the strict type-safety benefits of sharing `.proto` files across different programming languages.',
  },
  // Stage 5 (Go-To-Market, Growth & Product Leadership)
  {
    pathSlug: 'backend-engineering',
    stageNumber: 5,
    title: 'Architect a Multi-Region Active-Active Database',
    description: 'Design and deploy a globally distributed database architecture (e.g., CockroachDB or AWS Aurora Global) ensuring zero downtime during regional outages.',
    deliverables: ['Architecture diagrams', 'Terraform scripts for the global deployment', 'Failover testing logs'],
    acceptanceCriteria: ['Database automatically handles failovers across geographic regions', 'Read latencies are minimized by routing to the closest region'],
    difficulty: 5,
    expectedOutput: 'A planet-scale database infrastructure immune to single-region cloud failures.',
    skillsExercised: ['Distributed Databases', 'High Availability (HA)', 'Active-Active Replication', 'Disaster Recovery'],
    suggestedTools: ['AWS Aurora Global', 'CockroachDB', 'Terraform'],
    presentationTips: 'Discuss the CAP Theorem in your documentation—how did you balance Consistency vs. Availability across regions?',
  },
  {
    pathSlug: 'backend-engineering',
    stageNumber: 5,
    title: 'Design a High-Throughput Rate Limiting Service',
    description: 'Build a centralized, distributed rate-limiting service using Redis + Lua scripting capable of handling millions of requests per minute across a server fleet.',
    deliverables: ['GitHub repository for the rate-limiter middleware', 'Load testing reports (k6)'],
    acceptanceCriteria: ['Implements the Token Bucket or Sliding Window Log algorithm', 'Maintains precision across multiple Node/Go server instances without race conditions'],
    difficulty: 5,
    expectedOutput: 'A highly complex infrastructural component preventing API abuse at scale.',
    skillsExercised: ['Distributed Rate Limiting', 'Redis Lua Scripting', 'Concurrency / Race Conditions', 'Algorithm Design'],
    suggestedTools: ['Redis', 'Lua', 'Go / Node.js', 'k6'],
    presentationTips: 'Explain why executing the rate-limiting logic inside a Lua script on Redis prevents network latency and race conditions.',
  },
  {
    pathSlug: 'backend-engineering',
    stageNumber: 5,
    title: 'Lead a Major Monolith to Microservices Migration',
    description: 'Draft the technical specification and phased migration plan (Strangler Fig pattern) for breaking a massive legacy monolith into domain-driven microservices.',
    deliverables: ['Migration Strategy Document (PDF/Notion)', 'Domain-Driven Design (DDD) Context Map'],
    acceptanceCriteria: ['Identifies Bounded Contexts clearly', 'Proposes an API Gateway routing strategy that allows gradual, zero-downtime migration'],
    difficulty: 5,
    expectedOutput: 'An engineering leadership document tackling the hardest organizational and technical challenge in backend engineering.',
    skillsExercised: ['System Architecture', 'Domain-Driven Design (DDD)', 'Strangler Fig Pattern', 'Technical Leadership'],
    suggestedTools: ['Miro', 'Notion', 'Lucidchart'],
    presentationTips: 'Address the data migration problem—how do you handle distributed transactions or eventual consistency when the database is split?',
  },
  {
    pathSlug: 'backend-engineering',
    stageNumber: 5,
    title: 'Build a Custom Database Engine Core',
    description: 'Write a basic, persistent Key-Value store database engine from scratch in C, Rust, or Go, implementing a Log-Structured Merge (LSM) Tree or B-Tree.',
    deliverables: ['GitHub repository containing the database engine source code', 'CLI tool to interact with the database'],
    acceptanceCriteria: ['Data must be written to disk and persist between restarts', 'Implements basic indexing to ensure read speeds scale sub-linearly'],
    difficulty: 5,
    expectedOutput: 'A profound demonstration of low-level system programming and data structures.',
    skillsExercised: ['Low-level Systems Programming', 'Data Structures (LSM/B-Trees)', 'Disk I/O Management', 'Memory Safety'],
    suggestedTools: ['Rust / Go / C++', 'Hex Editor'],
    presentationTips: 'Write a blog post/README explaining how a crash-recovery mechanism (like a Write-Ahead Log) protects data from power failures.',
  },

  // ════════════════════════════════════════════
  // 7. CYBERSECURITY
  // ════════════════════════════════════════════
  // Stage 4 (Metrics, Analytics & Experimentation)
  {
    pathSlug: 'cybersecurity',
    stageNumber: 4,
    title: 'Develop a Custom C2 (Command and Control) Server',
    description: 'Build a basic, stealthy C2 server and agent framework in Python or Go to understand how advanced persistent threats (APTs) maintain access.',
    deliverables: ['GitHub repository with C2 server and client code', 'Demonstration video of establishing a reverse shell in a lab'],
    acceptanceCriteria: ['Communications between agent and server are fully encrypted (TLS/AES)', 'Agent utilizes jitter/sleep timers to evade behavioral detection'],
    difficulty: 5,
    expectedOutput: 'A deep understanding of offensive tooling development and evasion techniques.',
    skillsExercised: ['C2 Infrastructure', 'Offensive Tooling Development', 'Cryptography', 'Evasion Techniques'],
    suggestedTools: ['Python', 'Go', 'TLS/SSL'],
    presentationTips: 'Disclaimer: Emphasize that this tool was built strictly for educational red-teaming in isolated lab environments.',
  },
  {
    pathSlug: 'cybersecurity',
    stageNumber: 4,
    title: 'Threat Hunting with SIEM (Splunk/Elastic)',
    description: 'Ingest massive log datasets into a SIEM and write advanced query rules to proactively hunt for undetected lateral movement or beaconing.',
    deliverables: ['SIEM query syntax document', 'Threat hunting report detailing findings'],
    acceptanceCriteria: ['Queries utilize MITRE ATT&CK framework techniques', 'Successfully identifies anomalous PowerShell executions or SMB traffic'],
    difficulty: 4,
    expectedOutput: 'Proactive defense analysis, shifting from reactive alert-answering to active threat discovery.',
    skillsExercised: ['Threat Hunting', 'SIEM Query Languages (SPL/KQL)', 'MITRE ATT&CK Framework', 'Log Analysis'],
    suggestedTools: ['Splunk', 'Elastic Security (ELK)', 'Sysmon'],
    presentationTips: 'Map every query and finding directly to a specific MITRE ATT&CK T-Code (e.g., T1059.001).',
  },
  {
    pathSlug: 'cybersecurity',
    stageNumber: 4,
    title: 'Advanced Exploit Development (Buffer Overflows)',
    description: 'Reverse engineer a vulnerable 32-bit Linux or Windows executable, identify a memory corruption vulnerability, and write a custom exploit script.',
    deliverables: ['Python exploit script', 'GDB/Immunity Debugger screenshots of memory registers (EIP overwrite)'],
    acceptanceCriteria: ['Exploit reliably overwrites the instruction pointer to execute shellcode', 'Bypasses basic protections or identifies why they are disabled'],
    difficulty: 5,
    expectedOutput: 'A highly technical demonstration of memory manipulation and low-level exploit crafting.',
    skillsExercised: ['Exploit Development', 'Assembly Language (x86)', 'Buffer Overflows', 'Debugger Usage'],
    suggestedTools: ['Immunity Debugger', 'GDB', 'Python', 'Metasploit Pattern Generator'],
    presentationTips: 'Detail the exact process of calculating the offset needed to perfectly overwrite the return address.',
  },
  {
    pathSlug: 'cybersecurity',
    stageNumber: 4,
    title: 'Automated Vulnerability Management Pipeline',
    description: 'Build an automated pipeline that ingests vulnerability scans (Tenable/Nessus), deduplicates findings, and automatically opens Jira tickets for engineering teams.',
    deliverables: ['Python integration script', 'Flowchart of the vulnerability management process'],
    acceptanceCriteria: ['Script interacts with both the Scanner API and the Jira/Ticketing API', 'Assigns priority based on CVSS scores automatically'],
    difficulty: 4,
    expectedOutput: 'An automated SecOps workflow that drastically reduces manual triage time.',
    skillsExercised: ['Security Automation (SOAR)', 'API Integration', 'Vulnerability Management', 'Python Scripting'],
    suggestedTools: ['Python', 'Jira API', 'Nessus API'],
    presentationTips: 'Explain how you handle "re-opened" tickets if a vulnerability is marked fixed but is detected again in the next scan.',
  },
  // Stage 5 (Go-To-Market, Growth & Product Leadership)
  {
    pathSlug: 'cybersecurity',
    stageNumber: 5,
    title: 'Design a Zero Trust Network Architecture',
    description: 'Architect a comprehensive Zero Trust strategy for a global enterprise, replacing traditional VPN perimeters with identity-aware proxies and micro-segmentation.',
    deliverables: ['Zero Trust Architecture Blueprint', 'Identity & Access Management rollout plan'],
    acceptanceCriteria: ['Removes implicit trust; mandates continuous verification (MFA, device health)', 'Includes micro-segmentation rules for the data center'],
    difficulty: 5,
    expectedOutput: 'A modern, boardroom-ready security architecture capable of defending against insider threats and credential compromise.',
    skillsExercised: ['Zero Trust Architecture', 'Identity-Aware Proxies', 'Micro-segmentation', 'Enterprise Security Strategy'],
    suggestedTools: ['BeyondCorp Concepts', 'draw.io', 'Okta/Azure AD'],
    presentationTips: 'Emphasize how Zero Trust improves the employee user experience by eliminating clunky legacy VPN clients.',
  },
  {
    pathSlug: 'cybersecurity',
    stageNumber: 5,
    title: 'Lead a Red Team Operation Simulation',
    description: 'Plan and execute a full-scope Red Team engagement simulating an Advanced Persistent Threat (APT) targeting a specific business objective (e.g., stealing customer data).',
    deliverables: ['Red Team Operation Plan (RoE, Targets)', 'Execution timeline and final debrief report'],
    acceptanceCriteria: ['Includes OSINT, physical/social engineering, and technical exploitation phases', 'Provides actionable feedback to the Blue Team on why detection failed'],
    difficulty: 5,
    expectedOutput: 'A master-level adversarial simulation testing the holistic security posture of an organization.',
    skillsExercised: ['Red Teaming', 'Adversarial Emulation', 'Rules of Engagement (RoE)', 'Executive Debriefing'],
    suggestedTools: ['Cobalt Strike / Sliver', 'OSINT Frameworks', 'Phishing Infrastructure'],
    presentationTips: 'The final debrief must be ego-free; present the findings as a collaborative effort to improve the Blue Team, not to embarrass them.',
  },
  {
    pathSlug: 'cybersecurity',
    stageNumber: 5,
    title: 'SOC2 / ISO 27001 Compliance Program Build',
    description: 'Draft the foundational policies and control mappings required to achieve SOC 2 Type II or ISO 27001 compliance for a SaaS startup.',
    deliverables: ['Compliance Controls Matrix spreadsheet', 'Sample Information Security Policy document'],
    acceptanceCriteria: ['Maps technical controls (e.g., encryption at rest) directly to compliance framework requirements', 'Establishes vendor risk management procedures'],
    difficulty: 5,
    expectedOutput: 'A Governance, Risk, and Compliance (GRC) framework that enables the business to sell to enterprise customers.',
    skillsExercised: ['Compliance (SOC2/ISO27001)', 'Governance, Risk, and Compliance (GRC)', 'Policy Writing', 'Risk Management'],
    suggestedTools: ['Excel', 'Vanta / Drata (concept)'],
    presentationTips: 'Frame compliance not as an engineering burden, but as a sales enabler that unlocks massive enterprise revenue.',
  },
  {
    pathSlug: 'cybersecurity',
    stageNumber: 5,
    title: 'Build a Threat Intelligence Program',
    description: 'Design a Cyber Threat Intelligence (CTI) program that ingests feeds, analyzes geopolitical threats, and produces actionable intelligence reports for the CISO.',
    deliverables: ['Threat Intelligence Program Charter', 'Sample Strategic Threat Intel Report (PDF)'],
    acceptanceCriteria: ['Integrates tactical IoCs with strategic threat actor profiling', 'Establishes an automated MISP (Malware Information Sharing Platform) workflow'],
    difficulty: 5,
    expectedOutput: 'An advanced intelligence capability that shifts an organization from a reactive to a predictive security posture.',
    skillsExercised: ['Threat Intelligence (CTI)', 'MISP Configuration', 'Actor Profiling', 'Strategic Reporting'],
    suggestedTools: ['MISP', 'OpenCTI', 'MITRE ATT&CK'],
    presentationTips: 'Your sample report should profile a specific APT group relevant to your industry (e.g., APT29 for government, FIN7 for retail).',
  },

  // ════════════════════════════════════════════
  // 8. CLOUD ENGINEERING
  // ════════════════════════════════════════════
  // Stage 4 (Metrics, Analytics & Experimentation)
  {
    pathSlug: 'cloud-engineering',
    stageNumber: 4,
    title: 'Implement a Service Mesh (Istio)',
    description: 'Deploy a Kubernetes cluster and install Istio to manage microservices traffic, implementing mutual TLS (mTLS) and canary deployments.',
    deliverables: ['Istio YAML configuration files', 'Kiali dashboard screenshots showing traffic flow'],
    acceptanceCriteria: ['mTLS is enforced between all pods securely', 'Traffic routing rules execute a 90/10 Canary rollout for a new service version'],
    difficulty: 5,
    expectedOutput: 'An advanced networking layer for Kubernetes ensuring secure, observable microservice communication.',
    skillsExercised: ['Service Mesh', 'Istio / Linkerd', 'mTLS', 'Traffic Routing (Canary)'],
    suggestedTools: ['Kubernetes', 'Istio', 'Kiali', 'Helm'],
    presentationTips: 'Demonstrate how the service mesh handles circuit breaking when a downstream microservice starts failing.',
  },
  {
    pathSlug: 'cloud-engineering',
    stageNumber: 4,
    title: 'Design a Multi-Cloud Architecture',
    description: 'Architect a system that utilizes both AWS (for compute) and GCP (for BigQuery data analytics), establishing a secure Site-to-Site VPN or interconnect.',
    deliverables: ['Multi-Cloud Architecture Diagram', 'Terraform scripts abstracting both AWS and GCP providers'],
    acceptanceCriteria: ['Data flows securely between the two clouds without traversing the public internet', 'Avoids vendor lock-in where strategically beneficial'],
    difficulty: 5,
    expectedOutput: 'A complex hybrid-cloud topology optimizing for the best features of different cloud providers.',
    skillsExercised: ['Multi-Cloud Strategy', 'Site-to-Site VPN', 'Terraform (Multi-Provider)', 'Network Routing'],
    suggestedTools: ['Terraform', 'AWS VPC', 'Google Cloud Platform'],
    presentationTips: 'Acknowledge the data egress cost implications of moving data between AWS and GCP in your financial analysis.',
  },
  {
    pathSlug: 'cloud-engineering',
    stageNumber: 4,
    title: 'Chaos Engineering Implementation',
    description: 'Introduce Chaos Engineering into a staging environment using Gremlin or Chaos Mesh to intentionally terminate pods and network links to test system resilience.',
    deliverables: ['Chaos Experiment Design Document', 'Results report detailing how the system recovered'],
    acceptanceCriteria: ['Executes at least 3 distinct chaos experiments (e.g., CPU spike, network latency, pod deletion)', 'Identifies a previously unknown single point of failure'],
    difficulty: 5,
    expectedOutput: 'A proactive resilience testing program that ensures systems survive real-world outages.',
    skillsExercised: ['Chaos Engineering', 'System Resilience', 'Incident Recovery', 'Chaos Mesh'],
    suggestedTools: ['Chaos Mesh', 'Gremlin', 'Kubernetes'],
    presentationTips: 'Follow the scientific method: state your hypothesis clearly ("If we kill the database primary, the replica will promote in <10 seconds") before showing the result.',
  },
  {
    pathSlug: 'cloud-engineering',
    stageNumber: 4,
    title: 'Serverless Event-Driven ETL Pipeline',
    description: 'Build a serverless pipeline utilizing S3, AWS EventBridge, Step Functions, and Lambda to process massive CSV uploads automatically.',
    deliverables: ['AWS Step Functions state machine JSON', 'Architecture diagram'],
    acceptanceCriteria: ['Pipeline triggers automatically upon S3 file upload', 'Step Functions orchestrate retries and error handling visually'],
    difficulty: 4,
    expectedOutput: 'A robust, highly scalable data ingestion pipeline requiring zero server maintenance.',
    skillsExercised: ['Serverless Orchestration', 'AWS Step Functions', 'EventBridge', 'Serverless ETL'],
    suggestedTools: ['AWS Step Functions', 'AWS Lambda', 'AWS S3'],
    presentationTips: 'Show the visual workflow diagram generated by AWS Step Functions to illustrate the exact success and failure paths.',
  },
  // Stage 5 (Go-To-Market, Growth & Product Leadership)
  {
    pathSlug: 'cloud-engineering',
    stageNumber: 5,
    title: 'Enterprise FinOps & Cloud Cost Optimization',
    description: 'Audit a bloated cloud environment and implement a FinOps strategy utilizing Reserved Instances, Savings Plans, and Right-Sizing to cut costs by 30%.',
    deliverables: ['FinOps Audit Report', 'Cost Projection Spreadsheet (Before vs. After)'],
    acceptanceCriteria: ['Identifies idle resources (unattached EBS volumes, zombie EC2s)', 'Recommends Spot Instances for fault-tolerant batch workloads'],
    difficulty: 5,
    expectedOutput: 'A strategic financial engineering document that directly increases company profitability.',
    skillsExercised: ['Cloud Financial Management (FinOps)', 'Cost Optimization', 'Resource Right-Sizing', 'AWS Cost Explorer'],
    suggestedTools: ['AWS Cost Explorer', 'Excel', 'CloudHealth'],
    presentationTips: 'Explain the break-even point for purchasing a 3-year Reserved Instance versus running On-Demand.',
  },
  {
    pathSlug: 'cloud-engineering',
    stageNumber: 5,
    title: 'Internal Developer Platform (IDP) Build',
    description: 'Architect an Internal Developer Platform using Backstage to provide software engineers with self-service infrastructure provisioning (Golden Paths).',
    deliverables: ['Backstage configuration repository', 'Documentation on how a developer requests a new database'],
    acceptanceCriteria: ['Platform abstracts Terraform complexities behind a simple UI portal', 'Integrates with CI/CD to automatically spin up boilerplates'],
    difficulty: 5,
    expectedOutput: 'A Platform Engineering masterpiece that drastically reduces the DevOps bottleneck and improves developer velocity.',
    skillsExercised: ['Platform Engineering', 'Internal Developer Platforms (IDP)', 'Spotify Backstage', 'Self-Service Infra'],
    suggestedTools: ['Spotify Backstage', 'Terraform', 'Kubernetes'],
    presentationTips: 'Frame this project around reducing the "Time to First Commit" for a newly hired software engineer.',
  },
  {
    pathSlug: 'cloud-engineering',
    stageNumber: 5,
    title: 'Design a Multi-Region Disaster Recovery Plan',
    description: 'Architect a cross-region failover strategy (us-east-1 to eu-west-1) utilizing Route 53 health checks and Aurora Global Databases.',
    deliverables: ['Architecture diagrams detailing the failover flow', 'Disaster Recovery Runbook document'],
    acceptanceCriteria: ['Defines RTO (Recovery Time Objective) and RPO (Recovery Point Objective)', 'Architecture supports automatic failover via DNS routing'],
    difficulty: 5,
    expectedOutput: 'An enterprise-level disaster recovery design document ensuring high availability across continents.',
    skillsExercised: ['Disaster Recovery (DR)', 'Multi-Region Architecture', 'Route 53 Failover Routing', 'Database Replication'],
    suggestedTools: ['draw.io', 'AWS Route 53', 'AWS RDS Global'],
    presentationTips: 'Clearly distinguish between Active-Active and Active-Passive DR strategies and justify your choice based on cost vs. availability.',
  },
  {
    pathSlug: 'cloud-engineering',
    stageNumber: 5,
    title: 'Write a Custom Terraform Provider',
    description: 'Develop a custom Terraform provider in Go that interfaces with a third-party internal API to manage custom resources via IaC.',
    deliverables: ['GitHub repository containing the Go code for the provider', 'Example `.tf` file utilizing the custom provider'],
    acceptanceCriteria: ['Provider supports full CRUD operations (Create, Read, Update, Delete)', 'Passes Terraform acceptance tests (`acctest`)'],
    difficulty: 5,
    expectedOutput: 'A highly advanced infrastructure tooling project demonstrating deep understanding of the Terraform plugin SDK.',
    skillsExercised: ['Go Programming', 'Terraform Plugin SDK', 'API Integration', 'Advanced IaC'],
    suggestedTools: ['Go', 'Terraform CLI'],
    presentationTips: 'Explain the state management logic—how your provider detects drift between the API state and the local Terraform state.',
  },

  // ════════════════════════════════════════════
  // 9. DIGITAL MARKETING
  // ════════════════════════════════════════════
  // Stage 4 (Metrics, Analytics & Experimentation)
  {
    pathSlug: 'digital-marketing',
    stageNumber: 4,
    title: 'End-to-End Campaign ROI Analysis',
    description: 'Analyze an export of marketing campaign data (spend, clicks, conversions) to calculate CAC, ROAS, and LTV, presenting optimization steps.',
    deliverables: ['Excel data analysis workbook', 'Executive summary presentation deck'],
    acceptanceCriteria: ['Accurately calculates Customer Acquisition Cost (CAC) and Return on Ad Spend (ROAS)', 'Reallocates budget based on performance data'],
    difficulty: 4,
    expectedOutput: 'A financial marketing report connecting advertising spend directly to business revenue.',
    skillsExercised: ['Marketing Analytics', 'ROAS / CAC Calculation', 'Budget Reallocation', 'Executive Reporting'],
    suggestedTools: ['Excel Pivot Tables', 'Google Data Studio / Looker'],
    presentationTips: 'Visualize the diminishing returns of scaling campaigns—explain why doubling the budget doesn\'t always double the sales.',
  },
  {
    pathSlug: 'digital-marketing',
    stageNumber: 4,
    title: 'Technical SEO Site Audit',
    description: 'Perform a deep technical SEO crawl of a website to identify indexation issues, canonical errors, and core web vitals drops.',
    deliverables: ['Technical SEO Audit Report', 'Prioritized fix list for engineering'],
    acceptanceCriteria: ['Analyzes robots.txt, XML sitemaps, and 404 error logs', 'Grades site speed metrics (LCP, FID, CLS)'],
    difficulty: 5,
    expectedOutput: 'An advanced technical diagnostic report improving search engine crawlability.',
    skillsExercised: ['Technical SEO', 'Crawl Analysis', 'Core Web Vitals', 'Indexation Strategy'],
    suggestedTools: ['Screaming Frog SEO Spider', 'Google Search Console', 'PageSpeed Insights'],
    presentationTips: 'Prioritize the engineering tickets heavily; don\'t give developers 50 tasks, give them the 5 that move the needle.',
  },
  {
    pathSlug: 'digital-marketing',
    stageNumber: 4,
    title: 'Conversion Rate Optimization (A/B Test Design)',
    description: 'Design a comprehensive CRO experiment for an e-commerce checkout page, detailing the hypothesis, mockups, and significance targets.',
    deliverables: ['A/B test proposal document', 'Figma mockups of the Control vs. Variant'],
    acceptanceCriteria: ['Hypothesis is rooted in psychological principles or heuristic data', 'Specifies the Minimum Detectable Effect (MDE)'],
    difficulty: 5,
    expectedOutput: 'A scientific testing proposal aimed at increasing conversion rates and revenue.',
    skillsExercised: ['Conversion Rate Optimization (CRO)', 'A/B Test Design', 'Statistical Significance', 'UX/UI Hypotheses'],
    suggestedTools: ['VWO Calculator', 'Figma', 'Google Optimize (concept)'],
    presentationTips: 'Explain the risk of "peeking" at test results too early and why statistical significance requires patience.',
  },
  {
    pathSlug: 'digital-marketing',
    stageNumber: 4,
    title: 'Develop a Multi-Channel Attribution Strategy',
    description: 'Design an attribution model (e.g., Data-Driven, Position-Based) for a brand spending across Google Ads, Meta, and Organic Search to solve tracking overlap.',
    deliverables: ['Attribution Strategy Document (PDF)'],
    acceptanceCriteria: ['Explains the flaws of Last-Click attribution', 'Proposes how to merge GA4 data with CRM data to track actual sales, not just leads'],
    difficulty: 5,
    expectedOutput: 'A high-level data strategy solving one of marketing\'s hardest problems: proving ROI across multiple touches.',
    skillsExercised: ['Marketing Attribution Models', 'Cross-Channel Tracking', 'Data Strategy', 'CRM Integrations'],
    suggestedTools: ['Google Analytics 4', 'HubSpot/Salesforce mapping'],
    presentationTips: 'Address the impact of iOS 14+ tracking restrictions (ITP) and how your model relies on first-party data.',
  },
  // Stage 5 (Go-To-Market, Growth & Product Leadership)
  {
    pathSlug: 'digital-marketing',
    stageNumber: 5,
    title: 'Programmatic Advertising & DSP Strategy',
    description: 'Develop a media buying strategy using Demand Side Platforms (DSPs) to execute programmatic display and connected TV (CTV) advertising.',
    deliverables: ['Media Buying Plan', 'Targeting parameter configurations'],
    acceptanceCriteria: ['Utilizes first-party and third-party data layers for precise audience targeting', 'Establishes frequency capping rules to prevent ad fatigue'],
    difficulty: 5,
    expectedOutput: 'An enterprise-scale digital ad buying strategy beyond standard social and search platforms.',
    skillsExercised: ['Programmatic Advertising', 'Demand Side Platforms (DSPs)', 'Data Management Platforms (DMPs)', 'Media Buying'],
    suggestedTools: ['The Trade Desk (concept)', 'Google Display & Video 360'],
    presentationTips: 'Explain how you will verify brand safety to ensure ads do not appear next to controversial content.',
  },
  {
    pathSlug: 'digital-marketing',
    stageNumber: 5,
    title: 'Predictive Customer Lifetime Value (pLTV) Modeling',
    description: 'Collaborate with data teams to build and apply a predictive LTV model, adjusting marketing acquisition bids based on the predicted future value of a lead.',
    deliverables: ['pLTV Implementation Strategy Document', 'Bid modification matrix based on audience cohorts'],
    acceptanceCriteria: ['Shifts strategy from minimizing CAC to maximizing LTV/CAC ratio', 'Uses predictive algorithms to score leads in real-time'],
    difficulty: 5,
    expectedOutput: 'A highly sophisticated marketing strategy that aligns acquisition cost perfectly with long-term profitability.',
    skillsExercised: ['Predictive LTV (pLTV)', 'Advanced Bid Strategies', 'Algorithmic Marketing', 'Cohort Valuation'],
    suggestedTools: ['Excel', 'Google Ads Value-Based Bidding'],
    presentationTips: 'Highlight how acquiring a customer for $500 is a massive success if their predicted LTV is $5000, shifting away from "cheap clicks".',
  },
  {
    pathSlug: 'digital-marketing',
    stageNumber: 5,
    title: 'Orchestrate a Global Product Launch Go-To-Market',
    description: 'Act as the Marketing Lead for a Tier 1 global product launch, defining the messaging hierarchy, channel mix, and cross-functional rollout timeline.',
    deliverables: ['GTM Master Launch Deck', 'Cross-channel marketing calendar spanning PR, Email, Paid Ads, and Organic'],
    acceptanceCriteria: ['Aligns Product, Sales, and Marketing teams around a unified launch date', 'Defines tiering strategy (Tier 1 vs Tier 2 launches)'],
    difficulty: 5,
    expectedOutput: 'An executive-level orchestration demonstrating the ability to manage massive budgets and inter-departmental dependencies.',
    skillsExercised: ['Go-To-Market (GTM) Orchestration', 'Cross-functional Leadership', 'Global Rollout Strategy', 'Campaign Management'],
    suggestedTools: ['Asana / Monday', 'Google Slides'],
    presentationTips: 'Include an "Internal Enablement" section showing how you will train the Sales and Support teams before the public launch.',
  },
  {
    pathSlug: 'digital-marketing',
    stageNumber: 5,
    title: 'Marketing Mix Modeling (MMM) Implementation',
    description: 'Implement a Marketing Mix Model (MMM) to analyze historical sales data and determine the incremental impact of each marketing channel without relying on cookies.',
    deliverables: ['MMM Strategy Brief', 'Budget reallocation plan based on model outputs'],
    acceptanceCriteria: ['Accounts for external factors (seasonality, macroeconomics)', 'Calculates the saturation point (diminishing returns) for key channels'],
    difficulty: 5,
    expectedOutput: 'The gold standard of enterprise marketing measurement, proving ROI in a privacy-first world.',
    skillsExercised: ['Marketing Mix Modeling (MMM)', 'Incrementality Testing', 'Econometrics for Marketing', 'Budget Optimization'],
    suggestedTools: ['Meta Robyn', 'Python'],
    presentationTips: 'Explain to stakeholders why MMM differs from standard Google Analytics tracking (Top-down statistical approach vs. Bottom-up tracking).',
  },

  // ════════════════════════════════════════════
  // 10. MACHINE LEARNING ENGINEERING
  // ════════════════════════════════════════════
  // Stage 4 (Metrics, Analytics & Experimentation)
  {
    pathSlug: 'machine-learning-engineering',
    stageNumber: 4,
    title: 'Automated MLOps Pipeline & Monitoring',
    description: 'Build an automated machine learning pipeline (Prefect or Kubeflow) that registers models in a registry (MLflow) and monitors drift.',
    deliverables: ['MLOps pipeline code repository', 'Drift monitoring logs output screenshots'],
    acceptanceCriteria: ['Pipeline executes automated data extraction, model training, and version registering', 'Tracks feature drift metrics'],
    difficulty: 5,
    expectedOutput: 'A production pipeline that automatically retrains and monitors models.',
    skillsExercised: ['MLOps Engineering', 'Model Registries (MLflow)', 'Data Drift Trackers', 'Pipeline Orchestration'],
    suggestedTools: ['MLflow', 'Prefect', 'Evidently AI', 'Docker'],
    presentationTips: 'Provide a system topology diagram illustrating data flow from database tables to MLflow and production nodes.',
  },
  {
    pathSlug: 'machine-learning-engineering',
    stageNumber: 4,
    title: 'Fine-Tune a Large Language Model (LLM)',
    description: 'Use LoRA (Low-Rank Adaptation) or QLoRA to fine-tune an open-source LLM (e.g., Llama 3 or Mistral) on a specific domain dataset.',
    deliverables: ['Hugging Face model repository link', 'Notebook demonstrating the fine-tuning process'],
    acceptanceCriteria: ['Successfully loads a quantized model to fit in consumer GPU memory', 'Demonstrates the model answering domain-specific prompts correctly after training'],
    difficulty: 5,
    expectedOutput: 'A custom-trained Generative AI model adapted for a specific business use case.',
    skillsExercised: ['LLM Fine-Tuning', 'PEFT (LoRA/QLoRA)', 'Hugging Face Transformers', 'Quantization'],
    suggestedTools: ['Hugging Face AutoTrain', 'PyTorch', 'Google Colab (A100/T4)'],
    presentationTips: 'Include side-by-side prompt responses showing the base model failing and your fine-tuned model succeeding on the same question.',
  },
  {
    pathSlug: 'machine-learning-engineering',
    stageNumber: 4,
    title: 'Build an End-to-End Recommendation System',
    description: 'Develop a hybrid recommendation engine using Collaborative Filtering and Content-Based Filtering to suggest products or movies to users.',
    deliverables: ['GitHub Repository', 'Jupyter Notebook with evaluation metrics (NDCG or MAP)'],
    acceptanceCriteria: ['Solves the "Cold Start" problem for new users', 'Matrix Factorization techniques are applied'],
    difficulty: 5,
    expectedOutput: 'A highly complex personalization engine similar to those used by Netflix or Amazon.',
    skillsExercised: ['Recommendation Systems', 'Collaborative Filtering', 'Matrix Factorization', 'Information Retrieval Metrics'],
    suggestedTools: ['Surprise Library', 'scikit-learn', 'TensorFlow Recommenders'],
    presentationTips: 'Explain exactly how the hybrid approach balances popular items against highly niche, personalized items.',
  },
  {
    pathSlug: 'machine-learning-engineering',
    stageNumber: 4,
    title: 'Deploy Model to Edge / Browser (TensorFlow.js)',
    description: 'Convert a trained deep learning model and deploy it directly into a web browser using TensorFlow.js or ONNX Web to run client-side inferences.',
    deliverables: ['Live webpage URL running the model', 'GitHub repository containing the conversion scripts'],
    acceptanceCriteria: ['Model runs locally in the browser utilizing WebGL or WebAssembly', 'Inference latency is under 100ms'],
    difficulty: 5,
    expectedOutput: 'A lightning-fast, privacy-preserving AI application running entirely on the user\'s device.',
    skillsExercised: ['Edge AI', 'TensorFlow.js / ONNX', 'Model Compression', 'Client-side Architecture'],
    suggestedTools: ['TensorFlow.js', 'ONNX Runtime Web', 'React / Vanilla JS'],
    presentationTips: 'Highlight the privacy benefits of your architecture—explain how no user data is sent to a backend server during inference.',
  },
  // Stage 5 (Go-To-Market, Growth & Product Leadership)
  {
    pathSlug: 'machine-learning-engineering',
    stageNumber: 5,
    title: 'Distributed Model Training Strategy',
    description: 'Configure and execute a distributed training job for a massive deep learning model across multiple GPUs or nodes using PyTorch DDP or DeepSpeed.',
    deliverables: ['Distributed training script repository', 'WandB/TensorBoard logs showing GPU utilization'],
    acceptanceCriteria: ['Successfully implements Data Parallelism or Tensor/Pipeline Parallelism', 'Synchronizes gradients across at least 2 distinct GPUs efficiently'],
    difficulty: 5,
    expectedOutput: 'An advanced infrastructural engineering feat required to train foundational AI models.',
    skillsExercised: ['Distributed Training', 'PyTorch DDP (DistributedDataParallel)', 'DeepSpeed', 'GPU Optimization'],
    suggestedTools: ['PyTorch', 'DeepSpeed', 'Weights & Biases (WandB)'],
    presentationTips: 'Document the bottlenecks you encountered—was the network bandwidth between GPUs the limiting factor, or was it the disk read speed?',
  },
  {
    pathSlug: 'machine-learning-engineering',
    stageNumber: 5,
    title: 'Retrieval-Augmented Generation (RAG) System Architecture',
    description: 'Architect and build an enterprise-grade RAG system combining a vector database (Pinecone/Milvus), an embedding model, and an LLM to answer questions securely based on internal company documents.',
    deliverables: ['Architecture Blueprint', 'Functional GitHub repository with a chat interface'],
    acceptanceCriteria: ['Implements semantic chunking and hybrid search (Dense + Sparse/BM25)', 'Cites specific source documents used in the generated answer'],
    difficulty: 5,
    expectedOutput: 'A production-ready Generative AI system that eliminates hallucinations by grounding answers in factual data.',
    skillsExercised: ['RAG Architecture', 'Vector Databases', 'Embedding Models', 'Semantic Search', 'LangChain/LlamaIndex'],
    suggestedTools: ['LangChain / LlamaIndex', 'Pinecone / Weaviate', 'OpenAI API'],
    presentationTips: 'Focus heavily on your chunking strategy—explain why you chose overlap and specific token limits to preserve document context.',
  },
  {
    pathSlug: 'machine-learning-engineering',
    stageNumber: 5,
    title: 'Model Quantization and Optimization for Production',
    description: 'Take a heavy, slow deep learning model and optimize it for high-throughput inference using TensorRT, ONNX Runtime, and INT8 Quantization without significant accuracy loss.',
    deliverables: ['Optimization scripts', 'Benchmark report comparing FP32 vs INT8 latency and accuracy'],
    acceptanceCriteria: ['Inference speed increases by >2x', 'Accuracy drop is maintained below 2%'],
    difficulty: 5,
    expectedOutput: 'A masterclass in making AI models economically viable to run in production by reducing computational overhead.',
    skillsExercised: ['Model Quantization (INT8/FP16)', 'TensorRT / ONNX Optimization', 'Inference Acceleration', 'Hardware Utilization'],
    suggestedTools: ['NVIDIA TensorRT', 'ONNX Runtime', 'PyTorch'],
    presentationTips: 'Translate the compute savings into dollars—show how optimizing the model saves $X,000 per month in AWS GPU costs.',
  },
  {
    pathSlug: 'machine-learning-engineering',
    stageNumber: 5,
    title: 'Lead AI Ethics & Bias Mitigation Strategy',
    description: 'Develop a framework to audit machine learning models for bias, fairness, and ethical compliance, applying it to an existing high-stakes model (e.g., loan approval).',
    deliverables: ['AI Fairness Audit Report', 'Bias Mitigation Action Plan'],
    acceptanceCriteria: ['Utilizes tools like Fairlearn to measure Disparate Impact and Equal Opportunity Difference', 'Proposes algorithmic interventions (re-weighting, adversarial debiasing) to correct the model'],
    difficulty: 5,
    expectedOutput: 'A strategic governance document ensuring AI systems are legally compliant, fair, and safe for public deployment.',
    skillsExercised: ['AI Ethics', 'Algorithmic Fairness', 'Bias Auditing', 'Regulatory Compliance'],
    suggestedTools: ['Fairlearn', 'AIF360', 'Python'],
    presentationTips: 'Acknowledge the mathematical trade-off between fairness and raw accuracy, providing a business justification for your chosen balance.',
  }
];
