export const TASKS_PART_1 = [
  // ════════════════════════════════════════════
  // 1. PRODUCT DESIGN
  // ════════════════════════════════════════════
  // Stage 1 (Beginner)
  {
    pathSlug: 'product-design',
    stageNumber: 1,
    title: 'Mobile App Screen Redesign',
    description: 'Pick a mobile app you use daily and redesign one of its core screens in Figma to improve layout and usability.',
    deliverables: ['High-fidelity Figma frame of the redesign', 'Before/after screen comparison', 'Written rationale of your UX decisions (200 words)'],
    acceptanceCriteria: ['Must submit a public Figma file link', 'All font styles and colors must be standardized', 'Rationale must explain why visual hierarchy was changed'],
    difficulty: 1,
    expectedOutput: 'A clean, modernized high-fidelity mobile UI screen in Figma with organized layers and auto-layout.',
    skillsExercised: ['Figma UI Design', 'Visual Hierarchy', 'Typography', 'Color Theory'],
    suggestedTools: ['Figma', 'Contrast Checker'],
    presentationTips: 'Group your elements using Figma Auto-layout and rename all frames cleanly.',
  },
  {
    pathSlug: 'product-design',
    stageNumber: 1,
    title: 'Create a Simple Design System',
    description: 'Build a foundational component library with buttons, text fields, and dropdowns using Figma styles.',
    deliverables: ['Figma library with at least 6 components', 'Light/dark mode color palettes defined'],
    acceptanceCriteria: ['All components must support hover, active, and disabled variants', 'Uses Figma components with properties'],
    difficulty: 2,
    expectedOutput: 'A shareable Figma file serving as a UI kit with typography guidelines, color variables, and interactive components.',
    skillsExercised: ['Figma Components', 'Design Systems', 'UI Kit Creation'],
    suggestedTools: ['Figma', 'Tailwind Colors'],
    presentationTips: 'Organize components in clean grids and label each state explicitly (default, hover, disabled).',
  },
  {
    pathSlug: 'product-design',
    stageNumber: 1,
    title: 'UX Flow Teardown & Critique',
    description: 'Analyze an existing onboarding flow of a popular web app, documenting friction points and proposing solutions.',
    deliverables: ['Slide deck or Notion document detailing the flow', '3 suggested UX improvements with mockups'],
    acceptanceCriteria: ['Document screenshots of every step in the flow', 'Critique utilizes established heuristic principles (e.g., Nielsen Norman)'],
    difficulty: 1,
    expectedOutput: 'A structured UX audit report with actionable insights for improvement.',
    skillsExercised: ['UX Auditing', 'Heuristic Evaluation', 'User Flow Analysis'],
    suggestedTools: ['Notion', 'Google Slides', 'Loom (optional)'],
    presentationTips: 'Use side-by-side screenshots highlighting specific UI elements that cause friction.',
  },
  {
    pathSlug: 'product-design',
    stageNumber: 1,
    title: 'Wireframing a Landing Page',
    description: 'Create low-fidelity wireframes for a SaaS product landing page focusing purely on layout and information architecture.',
    deliverables: ['Low-fidelity wireframe in Figma or Whimsical', 'Written explanation of the information architecture'],
    acceptanceCriteria: ['No colors or high-res images used (grayscale only)', 'Clear visual hierarchy and distinct content sections'],
    difficulty: 1,
    expectedOutput: 'A structural wireframe mapping out the placement of copy, images, and calls-to-action.',
    skillsExercised: ['Wireframing', 'Information Architecture', 'Layout Design'],
    suggestedTools: ['Balsamiq', 'Whimsical', 'Figma'],
    presentationTips: 'Focus on content layout and user reading patterns (F-pattern, Z-pattern).',
  },

  // Stage 2 (Intermediate)
  {
    pathSlug: 'product-design',
    stageNumber: 2,
    title: '4-Screen Interactive Prototype',
    description: 'Design a complete user flow (e.g. signup to checkout) using interactive components and state transitions in Figma.',
    deliverables: ['Working interactive prototype link', 'User flow diagram mapping user actions'],
    acceptanceCriteria: ['Prototype flow must connect at least 4 distinct pages/actions', 'Smart Animate transitions used correctly'],
    difficulty: 2,
    expectedOutput: 'A fully clickable interactive Figma prototype showing smooth transitions and micro-animations.',
    skillsExercised: ['Prototyping', 'Interaction Design', 'User Flow Mapping'],
    suggestedTools: ['Figma Prototype', 'Whimsical'],
    presentationTips: 'Make sure there are no dead-ends in your flow; every screen should offer an action to return or proceed.',
  },
  {
    pathSlug: 'product-design',
    stageNumber: 2,
    title: 'Usability Testing & Iteration Case Study',
    description: 'Run a usability test on your interactive prototype with at least 3 participants and write an iteration report.',
    deliverables: ['Usability testing guide', 'Summary of findings', 'Updated designs showing changes based on feedback'],
    acceptanceCriteria: ['Report outlines at least 3 usability friction points discovered', 'Designs are modified based on feedback'],
    difficulty: 3,
    expectedOutput: 'A usability report document with feedback summaries and side-by-side screenshots of the design iterations.',
    skillsExercised: ['User Research', 'Usability Testing', 'Design Iteration'],
    suggestedTools: ['Maze', 'Notion', 'Figma'],
    presentationTips: 'Use direct quotes from users and bar charts or tables to visually show their success rates or points of confusion.',
  },
  {
    pathSlug: 'product-design',
    stageNumber: 2,
    title: 'Responsive Dashboard Design',
    description: 'Create a complex data dashboard for both desktop and mobile viewports, emphasizing data visualization.',
    deliverables: ['Figma designs for Desktop (1440px) and Mobile (390px)', 'Style guide for charts and graphs'],
    acceptanceCriteria: ['Must use responsive grids (12-column desktop, 4-column mobile)', 'Data charts must follow accessibility contrast ratios'],
    difficulty: 3,
    expectedOutput: 'A polished, responsive dashboard UI highlighting data hierarchy and mobile constraints.',
    skillsExercised: ['Responsive Design', 'Data Visualization', 'Grid Systems'],
    suggestedTools: ['Figma', 'Figma Charts Plugin'],
    presentationTips: 'Ensure your mobile view prioritizes key metrics without cluttering the screen.',
  },
  {
    pathSlug: 'product-design',
    stageNumber: 2,
    title: 'Advanced Figma Auto-Layout Mastery',
    description: 'Rebuild a complex web page (like the GitHub or Airbnb homepage) using strictly Auto-Layout components.',
    deliverables: ['Figma file with the reconstructed page', 'All frames must scale fluidly without breaking'],
    acceptanceCriteria: ['Zero absolute positioning for structural elements', 'Components must use min/max width properties correctly'],
    difficulty: 3,
    expectedOutput: 'A deeply structured Figma file demonstrating mastery over modern layout properties.',
    skillsExercised: ['Advanced Auto-Layout', 'Responsive Components', 'Figma Variables'],
    suggestedTools: ['Figma'],
    presentationTips: 'Demonstrate the fluidity of your design by recording a short Loom video resizing the frames.',
  },

  // Stage 3 (Advanced)
  {
    pathSlug: 'product-design',
    stageNumber: 3,
    title: 'Full Product Design Specification & Brief',
    description: 'Write a comprehensive product specification doc for a new feature, outlining user problems, user stories, and feature designs.',
    deliverables: ['Detailed product design spec (PDF or Notion link)', 'Interactive high-fidelity prototype'],
    acceptanceCriteria: ['Includes at least 8 user stories with clear design requirements', 'Prototype handles complex edge cases'],
    difficulty: 4,
    expectedOutput: 'A production-ready design brief detailing scope, accessibility guidelines, and developer hand-off assets.',
    skillsExercised: ['Product Thinking', 'Developer Hand-off', 'Accessibility Design (WCAG)', 'Specification Writing'],
    suggestedTools: ['Notion', 'Figma Inspect', 'Zeplin'],
    presentationTips: 'Include an accessibility section checking color contrast ratios and explaining keyboard navigation flows for screen-readers.',
  },
  {
    pathSlug: 'product-design',
    stageNumber: 3,
    title: 'Complete SaaS Web App Interface Design',
    description: 'Design a dashboard layout for a complex SaaS application, displaying multiple data visualizations and settings screens.',
    deliverables: ['High-fidelity SaaS design link', 'Responsive grid system layout presentation'],
    acceptanceCriteria: ['Design includes a side navigation, stats charts, and responsive layouts for mobile and desktop'],
    difficulty: 5,
    expectedOutput: 'A complete desktop and mobile responsive UI layout of a web portal showing structured data dashboards.',
    skillsExercised: ['Dashboard Design', 'Information Architecture', 'Responsive Design', 'SaaS UX'],
    suggestedTools: ['Figma', 'Charts Plugin'],
    presentationTips: 'Focus on clear data hierarchy. Use distinct card layouts and subtle borders instead of heavy colorful backgrounds.',
  },
  {
    pathSlug: 'product-design',
    stageNumber: 3,
    title: 'End-to-End E-Commerce Experience Design',
    description: 'Design a complete e-commerce flow from product discovery, cart management, to a multi-step checkout process.',
    deliverables: ['Full interactive prototype of the purchase journey', 'Error state designs for payment failures'],
    acceptanceCriteria: ['Includes empty states, loading states, and error states', 'Checkout flow handles guest vs registered users'],
    difficulty: 5,
    expectedOutput: 'A highly complex, production-ready prototype covering all edge cases of an e-commerce platform.',
    skillsExercised: ['Complex Workflows', 'Error State Handling', 'E-Commerce UX', 'Micro-interactions'],
    suggestedTools: ['Figma', 'Protopie (optional)'],
    presentationTips: 'Document edge cases extensively (e.g., what happens if an item goes out of stock during checkout).',
  },
  {
    pathSlug: 'product-design',
    stageNumber: 3,
    title: 'Enterprise Design System Architecture',
    description: 'Architect a multi-brand design system using Figma Variables (tokens) that supports white-label theming.',
    deliverables: ['Figma file containing primitive and semantic tokens', 'Documentation for engineers on token usage'],
    acceptanceCriteria: ['Uses Figma variables for spacing, color, and typography', 'Demonstrates at least 2 distinct brand themes easily toggled'],
    difficulty: 5,
    expectedOutput: 'An advanced, scalable design system foundation ready for enterprise deployment.',
    skillsExercised: ['Design Tokens', 'Figma Variables', 'Design Architecture', 'Theming'],
    suggestedTools: ['Figma Variables', 'Tokens Studio Plugin', 'Storybook (concept)'],
    presentationTips: 'Clearly separate primitive tokens (e.g., blue-500) from semantic tokens (e.g., button-bg-primary) to show architectural maturity.',
  },

  // ════════════════════════════════════════════
  // 2. FRONTEND ENGINEERING
  // ════════════════════════════════════════════
  // Stage 1 (Beginner)
  {
    pathSlug: 'frontend-engineering',
    stageNumber: 1,
    title: 'Responsive Portfolio Website',
    description: 'Build a responsive personal portfolio website from scratch using semantic HTML and Vanilla CSS. No frameworks allowed.',
    deliverables: ['Link to public GitHub repository', 'Live site deployment URL'],
    acceptanceCriteria: ['Valid HTML5 syntax', 'Fully responsive on screens from 320px to 1440px wide', 'Includes contact form and project listings'],
    difficulty: 1,
    expectedOutput: 'A clean, fast-loading, mobile-friendly landing page with animations deployed to a public hosting service.',
    skillsExercised: ['HTML5', 'CSS Flexbox/Grid', 'Responsive Layouts', 'Git & Hosting'],
    suggestedTools: ['VS Code', 'GitHub Pages', 'Netlify', 'W3C Validator'],
    presentationTips: 'Host your code on GitHub and write a clean README containing details on the styling methodology used.',
  },
  {
    pathSlug: 'frontend-engineering',
    stageNumber: 1,
    title: 'JavaScript Interactive Calculator',
    description: 'Develop an interactive calculator app utilizing vanilla JavaScript for logic and operations.',
    deliverables: ['GitHub Repository', 'Live deployment URL'],
    acceptanceCriteria: ['Handles decimal calculations, clear operations, and error states (division by zero)', 'Interface styled cleanly with custom CSS'],
    difficulty: 2,
    expectedOutput: 'A fully functional desktop/mobile browser calculator that handles arithmetic operations correctly.',
    skillsExercised: ['Vanilla JavaScript', 'DOM Manipulation', 'Event Listeners', 'Logic Handling'],
    suggestedTools: ['VS Code', 'Google Chrome DevTools'],
    presentationTips: 'Add keyboard event support (e.g. pressing numbers or Enter triggers the calculation) to show attention to usability.',
  },
  {
    pathSlug: 'frontend-engineering',
    stageNumber: 1,
    title: 'Cookie Consent & Toast Notification Banner',
    description: 'Create a reusable, dismissible cookie consent banner and a system for triggering toast notifications using Vanilla JS.',
    deliverables: ['GitHub Repository', 'Live CodePen or deployment link'],
    acceptanceCriteria: ['Banner state is saved in LocalStorage', 'Toasts automatically disappear after 3 seconds with smooth CSS animations'],
    difficulty: 1,
    expectedOutput: 'A robust, animated UI component system showing basic DOM interaction and storage persistence.',
    skillsExercised: ['DOM Manipulation', 'CSS Animations', 'LocalStorage', 'Timeout Functions'],
    suggestedTools: ['HTML/CSS/JS', 'CodePen'],
    presentationTips: 'Ensure the animations are hardware-accelerated by animating the `transform` and `opacity` properties.',
  },
  {
    pathSlug: 'frontend-engineering',
    stageNumber: 1,
    title: 'Unit & Currency Converter',
    description: 'Build a utility tool that converts units (e.g. Metric to Imperial) and fetches real-time currency exchange rates from a public API.',
    deliverables: ['GitHub Repository', 'Live deployment link'],
    acceptanceCriteria: ['Fetches currency rates on load using `fetch` API', 'Updates conversion output instantly as the user types'],
    difficulty: 2,
    expectedOutput: 'An interactive conversion tool showing basic asynchronous JavaScript and dynamic DOM updates.',
    skillsExercised: ['Fetch API', 'Event Listeners (Input)', 'Data Formatting', 'Error Handling'],
    suggestedTools: ['ExchangeRate-API', 'Vanilla JS'],
    presentationTips: 'Add debounce logic to the input fields to prevent unnecessary recalculations if expanding to complex APIs.',
  },

  // Stage 2 (Intermediate)
  {
    pathSlug: 'frontend-engineering',
    stageNumber: 2,
    title: 'Dynamic Weather Dashboard API Integration',
    description: 'Build a weather dashboard in React or vanilla JS that calls a third-party weather API and shows forecast data dynamically.',
    deliverables: ['GitHub Repository link', 'Live website URL'],
    acceptanceCriteria: ['Performs API fetch requests and handles loading/error states', 'Displays current weather and 5-day forecasts'],
    difficulty: 2,
    expectedOutput: 'A responsive dashboard displaying dynamically fetched data with location search capabilities.',
    skillsExercised: ['API Integration', 'Async JavaScript (Fetch/Axios)', 'React Hooks', 'State Management'],
    suggestedTools: ['React', 'Vite', 'OpenWeatherMap API'],
    presentationTips: 'Implement search input debouncing to prevent excessive API calls and optimize loading times.',
  },
  {
    pathSlug: 'frontend-engineering',
    stageNumber: 2,
    title: 'Full-Featured Task Management App',
    description: 'Create a task manager app in React with tasks stored in localStorage. Implement task lists, categories, edit options, and filter controls.',
    deliverables: ['GitHub Repository', 'Live demo link'],
    acceptanceCriteria: ['Supports full CRUD operations', 'Persistent data storage in local storage', 'Filters for completed/pending tasks'],
    difficulty: 3,
    expectedOutput: 'A React application featuring robust interactive state management and data persistence.',
    skillsExercised: ['React Component Design', 'Local Storage Persistence', 'Conditional Rendering', 'TailwindCSS / CSS Modules'],
    suggestedTools: ['React', 'TailwindCSS', 'Lucide React Icons'],
    presentationTips: 'Design a detailed dashboard layout with progress indicators displaying the ratio of completed tasks.',
  },
  {
    pathSlug: 'frontend-engineering',
    stageNumber: 2,
    title: 'Interactive Quiz Application',
    description: 'Develop a timed multiple-choice quiz app in React that tracks score, handles question progression, and outputs a final grade.',
    deliverables: ['GitHub Repository link', 'Live deployment URL'],
    acceptanceCriteria: ['Prevents users from skipping questions without answering', 'Includes a countdown timer that forces submission when it hits 0'],
    difficulty: 3,
    expectedOutput: 'A state-heavy interactive application showcasing complex React state flows and side-effects (intervals).',
    skillsExercised: ['React State (useState/useReducer)', 'useEffect (Timers)', 'Conditional UIs', 'Array Mapping'],
    suggestedTools: ['React', 'Open Trivia Database API (optional)'],
    presentationTips: 'Clean up your interval timers in the `useEffect` return function to demonstrate memory-leak prevention.',
  },
  {
    pathSlug: 'frontend-engineering',
    stageNumber: 2,
    title: 'E-Commerce Product Search & Filter Interface',
    description: 'Build a complex product catalog view with a sidebar containing filters (categories, price ranges, ratings) that update the UI instantly.',
    deliverables: ['GitHub Repository link', 'Live demo URL'],
    acceptanceCriteria: ['Filters can be combined (e.g. "Electronics" + "$50-$100")', 'Pagination or infinite scrolling implemented'],
    difficulty: 3,
    expectedOutput: 'A fast, client-side filtered product grid mirroring modern e-commerce sites.',
    skillsExercised: ['Array Filtering/Sorting', 'Complex State Management', 'Pagination', 'UI Feedback'],
    suggestedTools: ['React', 'FakeStore API', 'Framer Motion (for list transitions)'],
    presentationTips: 'Use URL query parameters to store the filter state so that users can share links to specific filtered views.',
  },

  // Stage 3 (Advanced)
  {
    pathSlug: 'frontend-engineering',
    stageNumber: 3,
    title: 'Deploy a Full-Stack Next.js Application',
    description: 'Develop a full-stack Next.js web application utilizing App Router, Server Actions, and a backend database integration.',
    deliverables: ['GitHub repository', 'Live URL deployed to Vercel'],
    acceptanceCriteria: ['Uses database storage for records', 'Protected user routes requiring session/auth', 'Optimized build with server-side rendering'],
    difficulty: 4,
    expectedOutput: 'A production-deployed Next.js application showing server-side rendering and database integration.',
    skillsExercised: ['Next.js App Router', 'Server Actions', 'Database Integration (Prisma)', 'Vercel Deployment'],
    suggestedTools: ['Next.js', 'Prisma ORM', 'Supabase PostgreSQL', 'NextAuth.js'],
    presentationTips: 'Enable Next.js route optimizations and provide a README detailing the architecture structure.',
  },
  {
    pathSlug: 'frontend-engineering',
    stageNumber: 3,
    title: 'React Performance Audit & Component Suite',
    description: 'Audit and optimize an existing slow React application, refactoring it to prevent re-renders, and implementing a suite of unit tests.',
    deliverables: ['Optimized GitHub repository link', 'Performance comparison audit report (lighthouse scores, Profiler traces)'],
    acceptanceCriteria: ['App displays lighthouse performance score above 90', 'Includes at least 10 React unit and integration tests (React Testing Library)'],
    difficulty: 5,
    expectedOutput: 'A highly optimized, fully tested React component suite with zero unnecessary re-renders.',
    skillsExercised: ['React Performance Tuning', 'useMemo / useCallback', 'Unit Testing (Jest/Vitest)', 'Lighthouse Audits'],
    suggestedTools: ['React DevTools Profiler', 'Vitest', 'Testing Library', 'Google Lighthouse'],
    presentationTips: 'Show clear before/after metrics of page load speeds and JavaScript bundle sizes in your README.',
  },
  {
    pathSlug: 'frontend-engineering',
    stageNumber: 3,
    title: 'Real-time Collaborative Whiteboard (WebSockets)',
    description: 'Build a real-time collaborative drawing or sticky-note application using WebSockets or a real-time database.',
    deliverables: ['GitHub repository link', 'Live deployed application URL'],
    acceptanceCriteria: ['Multiple users can join a room and see cursor movements and edits in real-time', 'Handles connection drops gracefully'],
    difficulty: 5,
    expectedOutput: 'A complex, multi-user synchronous application demonstrating advanced networking over WebSockets.',
    skillsExercised: ['WebSockets / Socket.io', 'Canvas API / SVG rendering', 'Real-time State Syncing', 'Conflict Resolution'],
    suggestedTools: ['Next.js', 'Socket.io', 'Supabase Realtime', 'Liveblocks'],
    presentationTips: 'Explain how you handle latency or optimistic UI updates in your project documentation.',
  },
  {
    pathSlug: 'frontend-engineering',
    stageNumber: 3,
    title: 'Custom React Component Library (NPM Package)',
    description: 'Build, document, and publish your own UI component library (buttons, modals, tooltips) as an NPM package.',
    deliverables: ['Link to the published NPM package', 'Storybook documentation site URL'],
    acceptanceCriteria: ['Package is successfully published and installable via `npm install`', 'Includes Storybook documentation with interactive playgrounds'],
    difficulty: 5,
    expectedOutput: 'A fully open-source React UI library complete with build tooling (Rollup/Vite) and docs.',
    skillsExercised: ['Library Packaging', 'Rollup/Vite Build Configs', 'Storybook', 'Semantic Versioning (NPM)'],
    suggestedTools: ['React', 'Storybook', 'Rollup', 'TailwindCSS'],
    presentationTips: 'Ensure your components support Tree Shaking so users only import the code they actually use.',
  },

  // ════════════════════════════════════════════
  // 3. DATA ANALYSIS
  // ════════════════════════════════════════════
  // Stage 1 (Beginner)
  {
    pathSlug: 'data-analysis',
    stageNumber: 1,
    title: 'Spreadsheet Exploratory Analysis',
    description: 'Analyze a public sales dataset in Google Sheets or Excel, building pivot tables, cleaning records, and creating charts.',
    deliverables: ['Link to shared online spreadsheet', 'Summary report detailing 3 key observations (300 words)'],
    acceptanceCriteria: ['Dataset contains >500 rows', 'Includes at least 2 distinct pivot charts', 'Data cleaning steps are documented'],
    difficulty: 1,
    expectedOutput: 'An organized spreadsheet workbook containing clean structured data, formulas, and dashboards.',
    skillsExercised: ['Spreadsheet Formulas', 'Pivot Tables', 'Data Visualization', 'Data Cleaning'],
    suggestedTools: ['Google Sheets', 'Microsoft Excel'],
    presentationTips: 'Use a clean corporate color theme for your charts and avoid overly colorful formatting in the data grid.',
  },
  {
    pathSlug: 'data-analysis',
    stageNumber: 1,
    title: 'SQL Business Metrics Queries',
    description: 'Write complex SQL queries on a business schema to extract metrics like Monthly Recurring Revenue (MRR), Customer Acquisition Cost (CAC), and user retention.',
    deliverables: ['SQL script file containing annotated queries', 'Query results outputs (screenshots or CSVs)'],
    acceptanceCriteria: ['Queries utilize JOINs, aggregations, CTEs, and window functions', 'Queries answer specific business performance questions'],
    difficulty: 2,
    expectedOutput: 'A SQL script answering business performance questions through complex database queries.',
    skillsExercised: ['SQL Query Writing', 'Relational Databases', 'CTEs & Window Functions', 'Business Metrics'],
    suggestedTools: ['PostgreSQL', 'DBeaver', 'BigQuery'],
    presentationTips: 'Write comments in your SQL files explaining the logic of your calculations (especially around complex aggregates).',
  },
  {
    pathSlug: 'data-analysis',
    stageNumber: 1,
    title: 'Data Cleaning & Validation Project',
    description: 'Take a notoriously messy public dataset (like Titanic or NYC Taxi data) and clean it using Python (pandas) or SQL.',
    deliverables: ['Cleaned CSV dataset export', 'Script or notebook showing the cleaning process'],
    acceptanceCriteria: ['Handles null values, deduplicates records, and standardizes date/string formats', 'Includes data dictionary'],
    difficulty: 1,
    expectedOutput: 'A perfectly formatted dataset ready for advanced modeling or visualization.',
    skillsExercised: ['Data Cleaning', 'Data Imputation', 'Data Type Formatting', 'Validation'],
    suggestedTools: ['Python pandas', 'Jupyter', 'OpenRefine'],
    presentationTips: 'Document your assumptions clearly—why did you choose to fill nulls with the median instead of dropping the rows?',
  },
  {
    pathSlug: 'data-analysis',
    stageNumber: 1,
    title: 'Descriptive Statistics Dashboard',
    description: 'Calculate mean, median, mode, variance, and standard deviation for key metrics in a dataset, visualizing the distribution.',
    deliverables: ['PDF report of the statistical findings', 'Histograms and box plots showing data distributions'],
    acceptanceCriteria: ['Correctly identifies outliers using IQR or Z-scores', 'Visualizes distributions clearly'],
    difficulty: 2,
    expectedOutput: 'A foundational statistical report summarizing the central tendencies and spreads of the data.',
    skillsExercised: ['Descriptive Statistics', 'Outlier Detection', 'Distribution Plotting'],
    suggestedTools: ['Excel', 'Python (matplotlib)', 'Tableau'],
    presentationTips: 'Explain what the standard deviation means in the context of the business problem, avoiding purely academic jargon.',
  },

  // Stage 2 (Intermediate)
  {
    pathSlug: 'data-analysis',
    stageNumber: 2,
    title: 'Python Explanatory Data Study',
    description: 'Perform an Exploratory Data Analysis (EDA) on a dataset using Jupyter Notebook, pandas, and matplotlib, outputting key trends.',
    deliverables: ['Jupyter Notebook file on GitHub', 'Clean PDF export of the notebook'],
    acceptanceCriteria: ['Uses pandas for dataset cleaning and descriptive stats', 'Includes at least 5 meaningful data visualizations'],
    difficulty: 2,
    expectedOutput: 'A clean Jupyter notebook showing documented python steps for loading, cleaning, and visualizing data.',
    skillsExercised: ['Python Programming', 'pandas DataFrames', 'matplotlib / seaborn', 'EDA Workflow'],
    suggestedTools: ['Jupyter Notebook', 'pandas', 'seaborn', 'Kaggle Datasets'],
    presentationTips: 'Format the notebook professionally with Markdown headers to structure the analytical flow like a story.',
  },
  {
    pathSlug: 'data-analysis',
    stageNumber: 2,
    title: 'Interactive BI Dashboard Project',
    description: 'Build an interactive BI dashboard (Tableau or Power BI) showing business operations, enabling user filters and drill-downs.',
    deliverables: ['Link to published Tableau Public workbook or Power BI file'],
    acceptanceCriteria: ['Dashboard displays at least 4 coordinated charts', 'Includes filters for time, region, and categories'],
    difficulty: 3,
    expectedOutput: 'A publicly viewable interactive data portal showing key performance indicators.',
    skillsExercised: ['BI Tooling', 'Dashboard Layouts', 'Interactive Filters', 'KPI Tracking'],
    suggestedTools: ['Tableau Public', 'Power BI'],
    presentationTips: 'Position your primary KPI cards in the top-left area where users naturally start reading the page.',
  },
  {
    pathSlug: 'data-analysis',
    stageNumber: 2,
    title: 'A/B Test Results Evaluation',
    description: 'Analyze the results of an A/B test dataset, performing a two-sample t-test or chi-square test to determine statistical significance.',
    deliverables: ['Jupyter Notebook or Excel file with calculations', 'Executive summary of the results'],
    acceptanceCriteria: ['Calculates p-value correctly', 'Clearly states whether to reject or fail to reject the null hypothesis'],
    difficulty: 3,
    expectedOutput: 'A scientific analysis of a business experiment, providing a concrete go/no-go decision.',
    skillsExercised: ['Hypothesis Testing', 'Statistical Significance (p-values)', 'A/B Test Analysis'],
    suggestedTools: ['Python (SciPy)', 'Excel Data Analysis Toolpak'],
    presentationTips: 'Include a recommendation on whether the lift (if any) justifies the engineering cost of deploying the winning variant.',
  },
  {
    pathSlug: 'data-analysis',
    stageNumber: 2,
    title: 'Time Series Forecasting Basics',
    description: 'Analyze seasonal sales data and perform a basic time series forecast to predict next quarter\'s metrics.',
    deliverables: ['Forecast charts (line graphs with confidence intervals)', 'Notebook with the ARIMA or Prophet model implementation'],
    acceptanceCriteria: ['Data is decomposed into trend, seasonality, and noise', 'Forecast includes evaluation metrics like MAE or RMSE'],
    difficulty: 3,
    expectedOutput: 'A predictive report projecting future business trends based on historical data.',
    skillsExercised: ['Time Series Analysis', 'Forecasting Models', 'Seasonality Decomposition', 'Trend Tracking'],
    suggestedTools: ['Python (statsmodels / Prophet)', 'Tableau Forecasting'],
    presentationTips: 'Highlight any major anomalies in the historical data (like a pandemic spike) and explain how you handled them in the model.',
  },

  // Stage 3 (Advanced)
  {
    pathSlug: 'data-analysis',
    stageNumber: 3,
    title: 'Production Data Pipeline & ETL',
    description: 'Create an automated data pipeline using Python that extracts data from an API, transforms it, and loads it into a database.',
    deliverables: ['GitHub repository with the ETL python scripts', 'Database schema export', 'Cron schedule setup configuration details'],
    acceptanceCriteria: ['Pipeline runs successfully and handles API response errors', 'Logs database load status and cleans invalid inputs'],
    difficulty: 4,
    expectedOutput: 'A structured python ETL project that runs automatically and persists parsed data.',
    skillsExercised: ['ETL Pipelines', 'Python Scripting', 'API Consumption', 'Database Upserts'],
    suggestedTools: ['Python', 'SQLAlchemy', 'PostgreSQL', 'GitHub Actions'],
    presentationTips: 'Use object-relational mapping (ORM) and connection pooling to show industry-standard backend habits.',
  },
  {
    pathSlug: 'data-analysis',
    stageNumber: 3,
    title: 'Cohort Analysis & Retention Report',
    description: 'Perform a comprehensive cohort analysis on transaction logs to evaluate monthly customer retention rates.',
    deliverables: ['Analytical report document (PDF or Notion link)', 'Jupyter Notebook with Python calculations'],
    acceptanceCriteria: ['Includes retention cohort heatmap visualization', 'Contains actionable recommendations to increase retention based on data findings'],
    difficulty: 5,
    expectedOutput: 'A professional executive report containing structured cohort analyses and business logic recommendations.',
    skillsExercised: ['Cohort Analysis', 'User Retention Logic', 'Advanced pandas', 'Executive Reporting'],
    suggestedTools: ['Python pandas', 'seaborn heatmap', 'Notion'],
    presentationTips: 'Highlight the distinction between organic growth and retention drop-offs, giving concrete product suggestions for improvement.',
  },
  {
    pathSlug: 'data-analysis',
    stageNumber: 3,
    title: 'Customer Segmentation (RFM Modeling)',
    description: 'Use Recency, Frequency, Monetary (RFM) analysis and K-Means clustering to segment a customer base into actionable marketing groups.',
    deliverables: ['Jupyter Notebook with clustering models', 'Presentation deck defining the 3-5 distinct customer personas discovered'],
    acceptanceCriteria: ['Utilizes K-Means clustering with optimal K determined via Elbow method', 'Assigns clear business labels to each cluster'],
    difficulty: 5,
    expectedOutput: 'An advanced marketing analytics model that translates mathematical clusters into real-world business segments.',
    skillsExercised: ['RFM Analysis', 'K-Means Clustering', 'Unsupervised Learning', 'Business Persona Mapping'],
    suggestedTools: ['Python (scikit-learn)', 'Tableau (for cluster vis)'],
    presentationTips: 'Give your clusters catchy names (e.g., "Whales", "Churn Risks", "Loyalists") to make the data digestible for marketing teams.',
  },
  {
    pathSlug: 'data-analysis',
    stageNumber: 3,
    title: 'Deploy an Interactive Data Web App',
    description: 'Wrap your analytical model or dashboard into a fully functional web application using Streamlit or Dash and deploy it.',
    deliverables: ['GitHub Repository link', 'Live URL of the deployed data application'],
    acceptanceCriteria: ['App allows users to upload custom CSVs or adjust model parameters via sliders', 'Deployed to a cloud provider'],
    difficulty: 5,
    expectedOutput: 'A production-grade, interactive web application that makes your data models accessible to non-technical users.',
    skillsExercised: ['Streamlit / Dash Frameworks', 'Web App Deployment', 'Interactive Data Tools', 'Cloud Hosting'],
    suggestedTools: ['Python (Streamlit)', 'Heroku', 'Streamlit Community Cloud'],
    presentationTips: 'Add a sidebar to your app explaining the methodology and limits of the underlying model.',
  },

  // ════════════════════════════════════════════
  // 4. PRODUCT MANAGEMENT
  // ════════════════════════════════════════════
  // Stage 1 (Beginner)
  {
    pathSlug: 'product-management',
    stageNumber: 1,
    title: 'Mobile App Feature Teardown',
    description: 'Deconstruct a feature in a popular mobile app, writing a product teardown detailing its target users, metrics, and gaps.',
    deliverables: ['1-page teardown document (PDF or Notion)'],
    acceptanceCriteria: ['Identifies at least 2 distinct user personas', 'Lists 3 primary telemetry metrics tracked', 'Suggests 1 user-centric UX improvement'],
    difficulty: 1,
    expectedOutput: 'A formatted product breakdown analyzing user behavior, feature mechanics, and potential changes.',
    skillsExercised: ['Product Analysis', 'Persona Mapping', 'Feature Telemetry', 'UX Critique'],
    suggestedTools: ['Notion', 'Figma (optional)'],
    presentationTips: 'Use structural subheadings like User Persona, Feature Flow, Gaps, and Solutions to keep your critique structured.',
  },
  {
    pathSlug: 'product-management',
    stageNumber: 1,
    title: 'User Interview Study & Insights',
    description: 'Run user interviews with at least 3 target customers to explore a specific problem space, synthesising findings.',
    deliverables: ['User interview guide script', 'Raw interview notes summary', 'Synthesis report showing core themes'],
    acceptanceCriteria: ['Interviews last >15 mins', 'Report lists at least 3 recurring customer pain points'],
    difficulty: 2,
    expectedOutput: 'A user research summary showing interview inputs and categorized customer needs.',
    skillsExercised: ['User Interviewing', 'Qualitative Analysis', 'Synthesis', 'Active Listening'],
    suggestedTools: ['Google Docs', 'Otter.ai', 'Notion'],
    presentationTips: 'Add callout boxes displaying direct user quotes to make user needs feel authentic to recruiters.',
  },
  {
    pathSlug: 'product-management',
    stageNumber: 1,
    title: 'Competitor Matrix & SWOT Analysis',
    description: 'Map out the competitive landscape for a specific SaaS sector, conducting a SWOT analysis for the top 3 players.',
    deliverables: ['Competitor feature matrix spreadsheet', 'SWOT analysis presentation slide deck'],
    acceptanceCriteria: ['Matrix covers at least 5 key feature axes', 'Identifies an underserved market gap'],
    difficulty: 1,
    expectedOutput: 'A strategic document mapping out market positioning and identifying areas for product differentiation.',
    skillsExercised: ['Market Research', 'Competitive Analysis', 'SWOT Framework', 'Strategic Positioning'],
    suggestedTools: ['Google Sheets', 'Miro', 'Canva'],
    presentationTips: 'Use Harvey balls or checkmarks in your matrix to visually show feature parity across competitors.',
  },
  {
    pathSlug: 'product-management',
    stageNumber: 1,
    title: 'Write User Stories & Acceptance Criteria',
    description: 'Take a high-level feature concept (e.g., "Add Apple Pay") and break it down into 5-10 detailed Agile user stories.',
    deliverables: ['Backlog board link or document with the stories'],
    acceptanceCriteria: ['Follows the "As a... I want to... So that..." format', 'Each story has clear, testable acceptance criteria'],
    difficulty: 1,
    expectedOutput: 'A clean product backlog ready for a sprint planning session.',
    skillsExercised: ['Agile Methodology', 'User Story Writing', 'Acceptance Criteria Definition', 'Scope Management'],
    suggestedTools: ['Jira', 'Trello', 'Linear'],
    presentationTips: 'Ensure your stories are small enough (investable) that engineers could complete them within a single sprint.',
  },

  // Stage 2 (Intermediate)
  {
    pathSlug: 'product-management',
    stageNumber: 2,
    title: 'Product Strategy & Roadmap Project',
    description: 'Create a 6-month product roadmap for a digital product with explicit prioritization frameworks (e.g. RICE).',
    deliverables: ['Visual product roadmap diagram', 'Prioritization matrix documentation page'],
    acceptanceCriteria: ['Roadmap covers at least 3 feature themes', 'RICE scores are calculated and explained for each feature'],
    difficulty: 2,
    expectedOutput: 'A detailed interactive roadmap timeline showing features, horizons, and product strategy goals.',
    skillsExercised: ['Product Roadmapping', 'Prioritization (RICE/Kano)', 'Strategy Definition', 'Timeline Planning'],
    suggestedTools: ['Figma', 'Miro', 'Productboard'],
    presentationTips: 'Design the roadmap around product outcomes (e.g., "Increase checkouts") rather than output lists (e.g., "Build checkout button").',
  },
  {
    pathSlug: 'product-management',
    stageNumber: 2,
    title: 'Feature Specs & PRD Writing',
    description: 'Write a comprehensive Product Requirements Document (PRD) for a new digital product feature.',
    deliverables: ['Detailed PRD document'],
    acceptanceCriteria: ['Includes user stories, acceptance criteria, wireframe flows, telemetry tracking, and edge cases'],
    difficulty: 3,
    expectedOutput: 'A complete spec sheet ready for designers and software developers.',
    skillsExercised: ['PRD Writing', 'User Story Writing', 'Edge Case Mapping', 'Telemetry Specifying'],
    suggestedTools: ['Notion', 'Confluence'],
    presentationTips: 'Outline success metrics as both primary (leading) and guardrail (lagging) indicators to show business focus.',
  },
  {
    pathSlug: 'product-management',
    stageNumber: 2,
    title: 'Define North Star & Product Metrics Tree',
    description: 'Define the North Star metric for a popular product (like Spotify or Slack) and break it down into a constellation metric tree.',
    deliverables: ['Visual metric tree diagram', 'Definitions document for each metric'],
    acceptanceCriteria: ['Tree connects high-level business goals (e.g., Revenue) to actionable product metrics (e.g., Daily Active Listeners)'],
    difficulty: 2,
    expectedOutput: 'A strategic framework that connects daily engineering work to high-level company valuation.',
    skillsExercised: ['North Star Metrics', 'KPI Definition', 'Data Strategy', 'Metric Trees'],
    suggestedTools: ['Miro', 'Whimsical', 'Amplitude Docs'],
    presentationTips: 'Clearly distinguish between input metrics (things you can change directly) and output metrics (things that result from changes).',
  },
  {
    pathSlug: 'product-management',
    stageNumber: 2,
    title: 'Sprint Planning & Backlog Grooming Simulation',
    description: 'Given a list of 20 unprioritized bugs and features, conduct a prioritization exercise and build a 2-week sprint plan.',
    deliverables: ['Prioritized sprint backlog (Trello or Jira board link)', 'Rationale document for what was cut'],
    acceptanceCriteria: ['Estimates story points for each ticket', 'Calculates team velocity and ensures the sprint is not over-capacity'],
    difficulty: 3,
    expectedOutput: 'A realistic simulation of Agile ceremonies, demonstrating strong scope negotiation skills.',
    skillsExercised: ['Sprint Planning', 'Agile Estimation (Story Points)', 'Scope Negotiation', 'Backlog Grooming'],
    suggestedTools: ['Jira', 'Linear', 'Trello'],
    presentationTips: 'Include a section on trade-offs explaining why a popular feature request was delayed in favor of a critical security patch.',
  },

  // Stage 3 (Advanced)
  {
    pathSlug: 'product-management',
    stageNumber: 3,
    title: 'Product Launch & GTM Plan',
    description: 'Develop a Go-To-Market (GTM) strategy plan for launching a new SaaS product, detailing positioning and metrics.',
    deliverables: ['Go-To-Market launch strategy deck (PDF link)'],
    acceptanceCriteria: ['Defines positioning statement, target pricing tiers, distribution channels, and launch KPIs'],
    difficulty: 4,
    expectedOutput: 'A high-impact business slide deck outlining the GTM launch strategy.',
    skillsExercised: ['Go-To-Market Strategy', 'Product Positioning', 'Pricing Architecture', 'Marketing Channels'],
    suggestedTools: ['Google Slides', 'Canva', 'Notion'],
    presentationTips: 'Include a slide with a week-by-week timeline of launch activities (pre-launch, launch day, post-launch).',
  },
  {
    pathSlug: 'product-management',
    stageNumber: 3,
    title: 'A/B Test Design & Metrics Spec',
    description: 'Design a structured A/B test proposal to optimize a conversion funnel, outlining hypotheses and sample size calculations.',
    deliverables: ['A/B testing spec document'],
    acceptanceCriteria: ['Includes baseline metrics, hypothesis, variant UI mocks, sample size, and statistical significance conditions'],
    difficulty: 5,
    expectedOutput: 'A technical testing plan document detailing hypothesis statements and statistical evaluation thresholds.',
    skillsExercised: ['A/B Testing Design', 'Statistical Significance', 'Conversion Funnels', 'Hypothesis Testing'],
    suggestedTools: ['Notion', 'Optimizely Calculator', 'Figma'],
    presentationTips: 'Explain the MDE (Minimum Detectable Effect) and how it affects the runtime duration of your proposed test.',
  },
  {
    pathSlug: 'product-management',
    stageNumber: 3,
    title: 'Build a Post-Mortem / Incident Report',
    description: 'Write a professional post-mortem for a hypothetical major production outage (e.g., payment gateway failure).',
    deliverables: ['Post-mortem document (Blameless culture style)'],
    acceptanceCriteria: ['Follows the "5 Whys" root cause analysis framework', 'Details a timeline of events and actionable preventative measures'],
    difficulty: 4,
    expectedOutput: 'A mature operational document proving your ability to handle crisis management and process improvement.',
    skillsExercised: ['Crisis Management', 'Root Cause Analysis (5 Whys)', 'Operational Process', 'Stakeholder Communication'],
    suggestedTools: ['Google Docs', 'Confluence Incident Templates'],
    presentationTips: 'Emphasize systemic failures over individual blame to demonstrate modern engineering leadership traits.',
  },
  {
    pathSlug: 'product-management',
    stageNumber: 3,
    title: 'Strategic Buy vs. Build vs. Partner Analysis',
    description: 'Evaluate a major strategic decision for a tech company: whether to build a feature in-house, buy a startup, or partner.',
    deliverables: ['Strategic memo (2-3 pages) detailing the financial and technical analysis'],
    acceptanceCriteria: ['Analyzes time-to-market, total cost of ownership (TCO), and core competency alignment', 'Provides a firm executive recommendation'],
    difficulty: 5,
    expectedOutput: 'An executive-level strategy memo that mirrors discussions held in C-suite product leadership meetings.',
    skillsExercised: ['Corporate Strategy', 'Financial Modeling (TCO)', 'Executive Communication', 'Buy vs Build Analysis'],
    suggestedTools: ['Notion', 'Excel (for TCO estimates)'],
    presentationTips: 'Start with a TL;DR Executive Summary at the very top—executives want the recommendation before the details.',
  },

  // ════════════════════════════════════════════
  // 5. CONTENT STRATEGY
  // ════════════════════════════════════════════
  // Stage 1 (Beginner)
  {
    pathSlug: 'content-strategy',
    stageNumber: 1,
    title: 'UX Writing & Copy Refactoring',
    description: 'Critique and rewrite three examples of confusing interface copy (error states, modals, onboarding) from live apps.',
    deliverables: ['Before/after comparison table', 'Explanation of changes (Plain Language guidelines)'],
    acceptanceCriteria: ['Explanations point to readability and tone standards', 'Final copies are clear and accessible'],
    difficulty: 1,
    expectedOutput: 'A side-by-side refactoring study showing improved visual readability and shorter word counts.',
    skillsExercised: ['UX Writing', 'Plain Language Principles', 'Tone Refinement', 'Critique Writing'],
    suggestedTools: ['Notion', 'Figma'],
    presentationTips: 'Provide mockups showing the original vs. rewritten copy in context on a screen overlay.',
  },
  {
    pathSlug: 'content-strategy',
    stageNumber: 1,
    title: 'Content Audit Spreadsheet',
    description: 'Perform a comprehensive content audit of at least 20 articles or pages of a brand, grading readability and metadata.',
    deliverables: ['Audit database spreadsheet link', 'Brief analysis report detailing 3 recommendations (300 words)'],
    acceptanceCriteria: ['Audits at least 20 content assets', 'Categorizes content by format, target audience, and performance'],
    difficulty: 2,
    expectedOutput: 'An structured audit sheet showing graded content scores and SEO recommendations.',
    skillsExercised: ['Content Auditing', 'Grading Frameworks', 'SEO Analysis', 'Content Recommendation'],
    suggestedTools: ['Google Sheets', 'Airtable'],
    presentationTips: 'Use conditional formatting (e.g. red, yellow, green) to color-code content quality scores for quick scanning.',
  },
  {
    pathSlug: 'content-strategy',
    stageNumber: 1,
    title: 'Brand Voice & Tone Guidelines',
    description: 'Create a foundational voice and tone guide for a fictional or existing startup, detailing how they sound across channels.',
    deliverables: ['Brand Voice Guide Document'],
    acceptanceCriteria: ['Defines 3-4 core voice pillars', 'Includes a "We sound like X, but not Y" chart', 'Provides writing samples for social, email, and blog'],
    difficulty: 1,
    expectedOutput: 'A practical, actionable style guide that freelance writers could immediately use to write on-brand copy.',
    skillsExercised: ['Brand Voice Definition', 'Tone Mapping', 'Style Guide Creation'],
    suggestedTools: ['Canva', 'Notion'],
    presentationTips: 'Make it highly visual. Text-heavy style guides are rarely read; use examples heavily.',
  },
  {
    pathSlug: 'content-strategy',
    stageNumber: 1,
    title: 'Write a High-Converting Landing Page',
    description: 'Write the complete copy for a B2B SaaS landing page, focusing on value propositions, benefits, and strong CTAs.',
    deliverables: ['Wireframed copy document mapping out sections (Hero, Features, Testimonials, CTA)'],
    acceptanceCriteria: ['Hero section includes a clear H1, sub-headline, and primary CTA', 'Focuses on benefits over features'],
    difficulty: 2,
    expectedOutput: 'A persuasive, conversion-optimized copy document ready for a web designer.',
    skillsExercised: ['Copywriting', 'Conversion Rate Optimization (CRO)', 'Value Propositions'],
    suggestedTools: ['Google Docs', 'Balsamiq (for layout mapping)'],
    presentationTips: 'Write out the specific microcopy for buttons (e.g., "Start Your Free 14-Day Trial") instead of just saying "Button".',
  },

  // Stage 2 (Intermediate)
  {
    pathSlug: 'content-strategy',
    stageNumber: 2,
    title: 'Search Optimization Refactoring',
    description: 'Select two blog articles and optimize their structures, headings, titles, and meta descriptions for search visibility.',
    deliverables: ['SEO optimized copy documents', 'Keyword research map page'],
    acceptanceCriteria: ['Includes targeted keyword mappings, optimized H1/H2 structures, title tags, and meta descriptions'],
    difficulty: 2,
    expectedOutput: 'SEO-ready content documents showing keyword usage and search engine snippet configurations.',
    skillsExercised: ['Search Engine Optimization (SEO)', 'Keyword Mapping', 'Meta Tag Formatting', 'Content Structuring'],
    suggestedTools: ['Google Docs', 'Ahrefs', 'Semrush'],
    presentationTips: 'Write out the title tags and meta descriptions within the character limit guidelines (e.g. titles under 60 chars).',
  },
  {
    pathSlug: 'content-strategy',
    stageNumber: 2,
    title: 'Editorial Calendar & Brand Kit',
    description: 'Build a comprehensive 1-month editorial calendar and content pipeline aligned to a brand voice style guide.',
    deliverables: ['1-month editorial calendar (Notion or Airtable)', 'Brand voice style guide sheet'],
    acceptanceCriteria: ['Calendar schedules at least 8 distinct content assets', 'Style guide details tone descriptors and formatting guidelines'],
    difficulty: 3,
    expectedOutput: 'A complete content production plan detailing timeline, resources, and publishing channels.',
    skillsExercised: ['Editorial Planning', 'Brand Style Guides', 'Content Distribution', 'Resource Planning'],
    suggestedTools: ['Notion', 'Airtable', 'Trello'],
    presentationTips: 'Add a "Do" and "Don\'t" section for writing examples in the style guide to make it highly practical.',
  },
  {
    pathSlug: 'content-strategy',
    stageNumber: 2,
    title: 'Content Gap Analysis',
    description: 'Compare a brand’s existing content library against target user journey phases to identify missing content types.',
    deliverables: ['Content Gap Matrix (Spreadsheet)', 'Strategy brief proposing 3 new major content pieces'],
    acceptanceCriteria: ['Maps content to TOFU, MOFU, and BOFU stages', 'Identifies specific search intent gaps compared to competitors'],
    difficulty: 3,
    expectedOutput: 'A strategic gap analysis that directs future content production efforts effectively.',
    skillsExercised: ['Funnel Mapping (TOFU/MOFU/BOFU)', 'Competitive Content Analysis', 'Strategic Planning'],
    suggestedTools: ['Excel', 'SEMrush (Content Gap Tool)'],
    presentationTips: 'Highlight the business risk of the missing content (e.g., "Competitor X is capturing all high-intent conversion traffic").',
  },
  {
    pathSlug: 'content-strategy',
    stageNumber: 2,
    title: 'Design a Multi-Channel Repurposing Workflow',
    description: 'Take one cornerstone piece of content (e.g., a whitepaper or webinar) and design a workflow to repurpose it into 10+ assets.',
    deliverables: ['Workflow diagram', 'Sample assets (1 Twitter thread, 1 LinkedIn post, 1 Newsletter intro)'],
    acceptanceCriteria: ['Workflow maps out how the core asset is sliced into video, text, and graphic formats across channels'],
    difficulty: 3,
    expectedOutput: 'A scalable content multiplication strategy that maximizes ROI on large content investments.',
    skillsExercised: ['Content Repurposing', 'Social Media Copywriting', 'Distribution Strategy'],
    suggestedTools: ['Miro', 'Notion'],
    presentationTips: 'Ensure the tone shifts appropriately for each channel (e.g., professional for LinkedIn, conversational for Twitter).',
  },

  // Stage 3 (Advanced)
  {
    pathSlug: 'content-strategy',
    stageNumber: 3,
    title: '4-Week Newsletter Launch Campaign',
    description: 'Design, write, and launch a 4-week email newsletter campaign on a specific topic, showing audience growth metrics.',
    deliverables: ['Public newsletter page link', 'PDF copies of all 4 sent newsletters', 'Launch growth report'],
    acceptanceCriteria: ['Each newsletter issue is >300 words of original content', 'Campaign includes growth metrics (subscribers, click rates)'],
    difficulty: 4,
    expectedOutput: 'A series of sent newsletters showing professional email layouts and copywriting strategies.',
    skillsExercised: ['Email Copywriting', 'Newsletter Optimization', 'Audience Growth', 'Performance Metrics'],
    suggestedTools: ['Substack', 'MailerLite', 'ConvertKit'],
    presentationTips: 'Explain the open rates and click rates, detailing what changes you made to the subject lines to boost performance.',
  },
  {
    pathSlug: 'content-strategy',
    stageNumber: 3,
    title: 'Comprehensive Content Marketing Strategy',
    description: 'Formulate an end-to-end content marketing campaign proposal for a brand, detailing strategy, execution channels, and KPIs.',
    deliverables: ['Campaign strategy document (PDF or Notion)'],
    acceptanceCriteria: ['Outlines user personas, funnel stages, content formats, distribution channels, and analytics tracking metrics'],
    difficulty: 5,
    expectedOutput: 'A strategic document mapping content assets to the customer acquisition funnel.',
    skillsExercised: ['Content Marketing', 'Acquisition Funnels', 'Multi-channel Distribution', 'Marketing Analytics'],
    suggestedTools: ['Notion', 'Google Slides'],
    presentationTips: 'Include a visual diagram mapping out how top-of-funnel (TOFU) blog traffic flows to bottom-of-funnel (BOFU) product landing pages.',
  },
  {
    pathSlug: 'content-strategy',
    stageNumber: 3,
    title: 'Information Architecture (IA) Overhaul',
    description: 'Redesign the information architecture and navigation taxonomy for a complex, 100+ page enterprise website.',
    deliverables: ['Sitemap diagram (Before & After)', 'Tree testing results report validating the new structure'],
    acceptanceCriteria: ['Reduces navigation depth (clicks to destination)', 'Categories are mutually exclusive and collectively exhaustive (MECE)'],
    difficulty: 5,
    expectedOutput: 'A robust structural mapping that improves website discoverability and SEO crawling.',
    skillsExercised: ['Information Architecture', 'Taxonomy Design', 'Tree Testing', 'Sitemap Mapping'],
    suggestedTools: ['Optimal Workshop', 'Slickplan', 'Miro'],
    presentationTips: 'Demonstrate how the new taxonomy aligns with the mental models of your users, not just internal company jargon.',
  },
  {
    pathSlug: 'content-strategy',
    stageNumber: 3,
    title: 'Develop a Content Governance Model',
    description: 'Create a governance framework outlining how content is requested, created, approved, published, and archived in a large organization.',
    deliverables: ['Governance workflow document', 'Roles and responsibilities matrix (RACI)'],
    acceptanceCriteria: ['Clearly defines who owns content accuracy vs. formatting', 'Establishes an archiving/updating cadence for stale content'],
    difficulty: 5,
    expectedOutput: 'An operational playbook that prevents content bloat and maintains quality at enterprise scale.',
    skillsExercised: ['Content Operations (ContentOps)', 'Governance Models', 'RACI Frameworks', 'Lifecycle Management'],
    suggestedTools: ['Confluence', 'Lucidchart'],
    presentationTips: 'Highlight the "Archive/Delete" phase of the lifecycle—many brands forget to delete old content, hurting SEO.',
  }
];
